--main 1
return {
	{
		Name = "Exine", --STAPLES!
		Cost = 25,
		CardsInPack = 4,
		CardPackId = 490218339,
		Description = "Filled with only good cards, Exine is a great place to get a good deck fast.",
		Cards = {
			"Training Dummy",
			"Samksoon321",
			"Brycen27",
			"AsrielMemer",
			"Razuatix",
			"Korblox Shaman",
			"Bearded Captain",
			"Card Hoarder",
			"Pizzablawk",
			"FatalWing",
			"VetexGames",
			"tbradm",
			"Olafisawesome100",
			"DairingPoopHead",
			"ROBLOX",
			"TheGamer101",
			"StayBlue",
			"Taymaster",
			"Rinicye",
			"MLGSPONGE",
			"PEEPSTERS",
			"mickymack",
			"WarbearNomkins",
			"HatdaCat",
			"Grand Pirate King",
			"Typheus the Whelp",
			"Nymn the Redrune Leader",
			"Megalodon the Dragon-Shark",
			"Plushie Mummy",
			"Divine Favor",
			"Ozzypig",
			"Weaven",
			"Murtic",
			"Arceusdon",
			"Chiefjustus",
			"Toy Truck",
			"Necromantic Acolyte",
			"Acolyte of the Rift",
			"Infernal Acolyte",
			"Lunar Acolyte",
			"Fried Acolyte",
			"Lady RedNight",
			"KingShadowCrow",
			"Burning Phoenix",
			"Spikle",
			"Gato Luz",
			"Jayson13",
			"Berezaa",
			"Titano's Cavern",
			"PolyHex",
			"Ripull",
			"JackInTheBlox",
			"zPikmon",
			"Pirate",
			"Odin",
			"KasoduS",
			"Cluck Buck",
			"Blockerwiz",
			"ShyLightness",
			"Redcliff Messenger",
			"Psychotic",
			"Tomfl",
			"Lord Tethamet",
			"Leitris",
			"Crossroads",
			"Shamrock Doge",
			"Korblox Deathknight",
			"Korblox Archer",
			"Byte",
			"DrKig",
			"Shedletsky the Fried One",
			"Ejob",
			"Zombie Summoner",
			"Zombie Cultist",
			"Stud",
			"Mitpaul",
			"KrocoStar",
			"DerpDerpyness",
			"Bloxy Tea Party",
			"Visleaf",
			"TheChakraTree",
			"Sylrath",
			"SimpleBeings",
			"Player",
			"Oz",
			"Oozlebachr",
			"Guest",
			"Mag",
			"Maelstronomer",
			"JackinatorMG",
			"ZacAttackk",
			"Assist Trophy",
			"Rukiryo",
			"XiaoXiaoMan",
			"Thunder Bolt",
			"Rhysmon",
			"Nexx",
			"Lohit",
			"Ambamby",
			"Cowboy",
			"Rad",
			"Anderson",
			"FatherChristmaz",
			"DerptasticDevil",
			"Langz",
			"Bob",
			"Cillow",
			"Glaecium",
			"Life Potion",
			"Zolerus",
			"Ice",
			"RiceStorage",
			"Regimen",
			"Finland",
			"TeeVee",
			"Robic",
			"Tarfful",
			"Latchie",
			"SoftCollision",
			"Uias",
			"Valletta",
			"GemInNight",
			"Bowl of Greed",
			"Froot Ninja",
			"Glaciem Mage",
			"DeadZoneHark",
			"Dayren",
			"FuuTuu",
			"PixelPistol",
			"Ninja Elite",
			"AntiSammeh",
			"Meebling Infestation",
			"MekaX",
			"Duckywow",
			"Inventor1116",
			"Preston",
			"Toxic",
			"Loogi",
			"Qdhxx",
			"Sammeh",
			"Noob Attack! Ninja Stars!",
			"PhireFox",
			"SharpTH",
			"Mike",
			"Fuchsia Eyes Red Dragon",
			"Dignity",
			"Blue Eyes Indigo Dragon",
			"Sand Eyes Yellow Dragon",
			"MisterObvious",
			"Teal Eyes Green Dragon",
			"Exine",
			"IcyTea",
			"Drager",
			"Eye Spy",
			"FuryBlocks",
		},
	}; 
	{
		Name = "Dominion", --RED!
		Cost = 30,
		CardsInPack = 4,
		CardPackId = 465492503,
		Description = "Red is the colour of power, ambition, and control. Dominion packs contain cards that cost red!",
		Cards = {
			"iiMasant",
			"Dwarvern Sentry: MAX",
			"Dwarvern Sentry: Delta",
			"Dwarvern Sentry: Gamma",
			"Dwarvern Sentry: Beta",
			"Dwarvern Sentry: Alpha",
			"Dwarvern Captain",
			"Dwarvern Scientist",
			"Dwarvern Mathematician",
			"Dwarvern Engineer",
			"Dwarvern Energist",
			"Dwarvern Miner",
			"Winchester Rotomo",
			"mrawesomecarter",
			"JavierCollin88Poppin",
			"Mohawk2275",
			"Prisman",
			"FabulousMettaton123",
			"666",
			"WoodReviewer",
			"One4utwo4me",
			[[One_Thousand_Deaths]],
			"Burning_Soul_Blade",
			"Cooldude4851",
			"Cotton Cavalier",
			"Arashi Pikemen",
			"HeyItsColin",
			"BerskererPredator450",
			"DrPepperSlayer",
			"MUTO2014",
			"Meeboid Champion",
			"NerfModder",
			"Beam Sword",
			"ClanAtlas",
			"KurosakiDXenos",
			"Doneyes",
			"Skarra the DragonSlayer",
			"Forbidden Power",
			"Sibs",
			"SomaticMizuSan",
			"Moon Rabbit's Rage",
			"UAE",
			"Kit of Deception",
			"Robloxian255",
			"UristMcSparks",
			"zKevin",
			"Explode1",
			"Ultoris Tenebrae",
			"Ultoris NOOBrae",
			"TheSteelEagle",
			"ROBLOXADOR!!",
			"XxFreezerFlamesxX",
			"LordVasco",
			"Isaac0333",
			"Alkalola",
			"Nikilis",
			"Rockybow",
			"Crazynoggin",
			"Hoshpup",
			"Aife",
			"Duel Axe Monster",
			"ScriptMasTime",
			"Redcliff Rogue",
			"Anti-Fave",
			"Super Bacon",
			"legoseed",
			"Taymaster",
			"TheAmazeMan",
			"Rinicye",
			"AllStarBren",
			"Paranormanbiggestfan",
			"Deathaman211",
			"Grand Ignis Mage",
			"MrDoombringer",
			"Fleskhjerta",
			"Dragon's Charm",
			"Nymn the Redrune Leader",
			"Titan of the Infernal Abyss",
			"Inferno!",
			"Redcliff: Decimate!",
			"Redcliff: Rise!",
			"Divine Favor",
			"Dodgeball Player Red",
			"Ozzypig",
			"Papasmurf",
			"Redrune Raider",
			"The Vlad",
			"Chiefjustus",
			"Infernal Acolyte",
			"SirAdurite",
			"Totem of Pixel",
			"PassTheToiletPaper",
			"Luck o The Lobsters",
			"Lady RedNight",
			"FishBubble1002",
			"Fallen Guardian",
			"BuzzHamtaro",
			"Primal Gato",
			"Jayson13",
			"The Stalker",
			"Zedreadr",
			"Drakobloxxer",
			"WafflzDude",
			"Odin",
			"KennedyLeDog",
			"Connoisseur",
			"ChosenCoast",
			"Blockerwiz",
			"Redcliff Enforcer",
			"Redcliff Mauler",
			"Redcliff Elite Commander",
			"Redcliff Messenger",
			"SkySpell",
			"Tomfl",
			"Grandmasters Ninja Dojo",
			"Redcliff Archer",
			"DrKig",
			"Right Leg of the Fried One",
			"Mitpaul",
			"WhiteScarf",
			"RoboticMob",
			"Player",
			"Plankton124",
			"Pixellus",
			"Oz",
			"Mag",
			"HyperVoxel",
			"DataRaven",
			"BUTQUNA",
			"ZacAttackk",
			"Sorry",
			"HashtagWatermelon",
			"Ambamby",
			"Cowboy",
			"Ignis Mage",
			"Kamov",
			"Ninja",
			"Rad",
			"Anderson",
			"Cherie",
			"FatherChristmaz",
			"Tomspick",
			"DerptasticDevil",
			"PixelFlame",
			"FuuTuu",
			"BloodSpilled",
			"Hodif",
			"Ninja Elite",
			"Ninja Trainee",
			"Ninja Assailant",
			"Ninja Combatant",
			"Teeny Ninja",
			"AntiSammeh",
			"Sammeh",
			"Noob Attack! Ninja Stars!",
			"SirDapper",
			"DIY Biggerhead",
			"BlazerC",
			"Fuchsia Eyes Red Dragon",
			"Dignity",
			"Fave",
			"Exine",
			"Bloxy Victory",
		},
	}; 
	{
		Name = "Vitality", --GREEN!
		Cost = 30,
		CardsInPack = 4,
		CardPackId = 465492570,
		Description = "Green is the colour of life, growth, and the primal forces. Vitality packs contain cards that cost green!",
		Cards = {
			"HyperBlue",
			"rhomlevko",
			"__________",
			"Smart Planner",
			"Zombie",
			"Brick_Man",
			"Uncreativename123",
			"pa00",
			"Overseer Drake",
			"Tankbomer",
			"InceptionTime",
			"Aceguy100",
			"Mariochocolatemilk",
			"HasTheHero",
			"Korblox Shadowmage",
			"Redcliff Heretic",
			"stereoplexus",
			"Cat's Eye Wing Flock",
			"Cat's Eye Corpse Stealer",
			"Cat's Eye, Master of Perception",
			"iAsuka",
			"TigerCode",
			"APlayerOfGames",
			"Samksoon321",
			"ST Leader Keeler1",
			"Brymmy",
			"Brycen27",
			"Bad Bread",
			"Razuatix",
			"Rainbowjewelninga785",
			"Mrbeanbean2",
			"Bearded Captain",
			"Keeler1",
			"FatalWing",
			"EfanPlayz",
			"inechi",
			"BroRubik",
			"1337",
			"Picopicoman",
			"Beeism",
			"Alapz",
			"Blockhaak",
			"MLGSPONGE",
			"GreenHearted",
			"ReverseBackwards",
			"Gangmanstyle556",
			"Vermin's Caress",
			"Accursed Gate",
			"Rat King",
			"Grand Meeboid Totem",
			"Myrmiredon",
			"JJ5x5",
			"Monkey",
			"Zerax the Untameable",
			"Overseer's Steed",
			"Oddman's Gambit",
			"Titan of the Dying Forest",
			"Mass Epidemic",
			"Divine Favor",
			"Mummy Peasant",
			"Weaven",
			"Zom-nobi",
			"XxWonderzxX",
			"Witch's True Brew",
			"Murtic",
			"Fancy Arachnid",
			"Construction Zombie",
			"Traumatic Clown",
			"Jeptem",
			"Necromantic Acolyte",
			"Eye of Overseer",
			"Overseer Beast",
			"Overseer General",
			"Overseer Prophet",
			"LuckyTux",
			"Medic Kit",
			"KingShadowCrow",
			"Bereghost",
			"PolyHex",
			"Spikle",
			"1x1x1x1",
			"Biostream",
			"Ripull",
			"Pirate",
			"KasoduS",
			"WaddleTom",
			"Leitris",
			"Boogerguy123",
			"Byte",
			"Left Leg of the Fried One",
			"Zombie King",
			"Zombie Summoner",
			"Zombie Cultist",
			"KingCactaur",
			"DerpDerpyness",
			"Pillager",
			"Oozlebachr",
			"MrMaxi23",
			"Nicolas1015",
			"MiloCortez",
			"StickMasterLuke",
			"XiaoXiaoMan",
			"Quenty",
			"MyDadIsAGuest",
			"IlIll",
			"Meeboid",
			"Langz",
			"Krazy Koala",
			"Bob",
			"Chef",
			"Cillow",
			"Otub",
			"Robber",
			"BO0M",
			"Burglar",
			"Glaecium",
			"Life Potion",
			"Zolerus",
			"Meeboid Cultist",
			"Meebling",
			"NatzHakz",
			"Faultful",
			"Saiier",
			"MekaX",
			"Duckywow",
			"Inventor1116",
			"Luchador",
			"TZSara",
			"BadBreadMaker",
			"Calirolls",
			"Camo Joe",
			"Chaoszeroomega",
			"Meeboid King",
			"Summon! Meeboid Titano!",
			"Hoote",
			"NICCO",
			"Wustard",
			"Tom's Beans",
			"PhireFox",
			"Awful Good",
			"Deadeye",
			"DIY Dominus",
			"Teal Eyes Green Dragon",
			"Icepielover23",
		},
	}; 
	{
		Name = "Thought", --BLUE!
		Cost = 30,
		CardsInPack = 4,
		CardPackId = 465492637,
		Description = "Blue is the colour of logic, order, and structure. Thought packs contain cards that cost blue!",
		Cards = {
			"Yoshius",
			"Nopants99",
			"CIA Man",
			"FabulousBench",
			"Stevenl15",
			"B0BBA",
			"Razikai",
			"Fenrier",
			"JaikKaik",
			"Gravity Inspector",
			"LordFlanz",
			"TheEnderCorp",
			"ShockingRobux",
			"HuntarioRBLX",
			"Cyandude585",
			"Coordinated Attack",
			"Erik.Cassel",
			"Febrezer",
			"Paraselene Sage",
			"Luckymaxer",
			"Crystal Snare",
			"AsrielMemer",
			"RukatuKDH",
			"Gravity Collapse",
			"BuildIntoGames",
			"BlueShadic90",
			"Her0z",
			"xXVitalityVoidXx",
			"Dodgeball Player Blue",
			"Regular_Show",
			"Vitality Potion",
			"bengbeng14",
			"Korblox Shaman",
			"SuperCloud9",
			"Isaac0333-V2",
			"Brick Bacon",
			"Meme Thief",
			"Amber",
			"Materking",
			"tbradm",
			"4.0 Robloxian",
			"lando64000",
			"Owen0202",
			"VetexGames",
			"DrTrayBlox",
			"destruction5033",
			"Olafisawesome100",
			"puffytenter12",
			"ClanDrone",
			"Tinfoilbot",
			"bincent",
			"DairingPoopHead",
			"StayBlue",
			"Teaism",
			"Skullsten",
			"wer8888",
			"Voidsealer",
			"BlackSymphony",
			"HatdaCat",
			"BlizzardCreeper",
			"Consume Dream",
			"Traumaturge",
			"Bee",
			"Beehive",
			"Swarm",
			"Beekeeper",
			"Queen Bee",
			"True Hivemind",
			"Delusionist",
			"Grand Glaciem Mage",
			"LeetWizard",
			"Bebee2",
			"ItssPaladin",
			"Frosty The Snowman",
			"Megalodon the Dragon-Shark",
			"Titan of the Deep Below",
			"Depths of the Nether",
			"Divine Favor",
			"Alexnewtron",
			"Theawesomist19",
			"Skeleton Armada",
			"Arceusdon",
			"Acolyte of the Rift",
			"Witch",
			"Police Combatant",
			"Police Officer",
			"Serhat12",
			"Liz",
			"Hideaki",
			"Frozen Phoenix",
			"DominatedLegacy",
			"Bloo",
			"Gato Luz",
			"NobleDragon",
			"JackInTheBlox",
			"zPikmon",
			"Metal Bloxxer",
			"Cyclist",
			"GamesBloxx",
			"ShyLightness",
			"Psychotic",
			"Hamstermon",
			"Lord Tethamet",
			"Disaster Survival",
			"Korblox Archmage",
			"Korblox Deathknight",
			"Korblox Deathkeeper",
			"Korblox General",
			"Korblox Defender",
			"Korblox Archer",
			"JadeFlames",
			"Right Arm of the Fried One",
			"Soul Release",
			"Spiderboy",
			"KrocoStar",
			"Halo4master233",
			"FancyFame",
			"WildSpeedy",
			"Tiny Tank",
			"Sylrath",
			"SwatPhantom",
			"Spark",
			"SimpleBeings",
			"MICHIKUSCHI",
			"Luigifan103",
			"JackinatorMG",
			"DeathETM",
			"Thunder Bolt",
			"Master Josue",
			"Lebron",
			"Lohit",
			"Samurai Shock",
			"Daisy",
			"Ice",
			"Developer",
			"Newbie",
			"RiceStorage",
			"Salesman",
			"Bloated",
			"DDude",
			"Kago",
			"Regimen",
			"Froot Ninja",
			"Subata",
			"Glaciem Mage",
			"EzCheez",
			"Snowskateer",
			"Brunito",
			"Mackerel",
			"2Hex",
			"CinematicMind",
			"DeadZoneHark",
			"SharpTH",
			"Gaomon94",
			"Darpeh",
			"Mike",
			"KnightDude",
			"DIY Azurewrath",
			"Y05H1M4N",
			"Blue Eyes Indigo Dragon",
			"Dued1",
			"IcyTea",
			"EpicLatiosLord",
			"EXLatios",
			"Eye Spy",
			"FuryBlocks",
		},
	}; 
	{
		Name = "Revel", --YELLOW!
		Cost = 30,
		CardsInPack = 4,
		CardPackId = 465492745,
		Description = "Yellow is the colour of community, satisfaction, and society. Revel packs contain cards that cost yellow!",
		Cards = {
			"PencilWizard",
			"YotamTiti",
			"Divine_Pengu",
			"JayTheCoder",
			"Monopoly Man",
			"Friend Request Spammer",
			"Luck Warrior of Pure Gold",
			"Zaquille",
			"The Piece Breaker",
			"Mr.O the Traveling Merchant",
			"Pancake Break",
			"BLOXER787",
			"Aurichalcum",
			"BrackioTops",
			"Cat's Eye Cultist",
			"Cat's Eye Nexus",
			"Lilmanofsalem",
			"animallogic",
			"Training Dummy",
			"Western Bandit",
			"Mzh3000",
			"NearMiss TFW",
			"Miked",
			"wi_sh",
			"Ultra Doregriffon",
			"Renaud800",
			"Uberubert",
			"Prestwick",
			"Lopous",
			"Dun_Goof",
			"John and Jane",
			"MustagedWorldYT",
			"President Duck",
			"Lorenzo77555",
			"Card Hoarder",
			"MinePix110",
			"SirSorin",
			"Flufflefunz",
			"One BLOX Man",
			"Lilly_S",
			"MuPower",
			"popcornhebe",
			"CellBloxTango",
			"Saprasam",
			"MajorMattias",
			"Radello",
			"CALL OF DOGE!?!",
			"Doge Hound",
			"Maplestick",
			"Evil Wood Grain",
			"Uncomfortably",
			"Mysterious UFO",
			"ROBLOX",
			"Widgeon",
			"TheGamer101",
			"Seranok",
			"BrightEyes",
			"SolarCrane",
			"OstrichSized",
			"Spooksletsky",
			"agodlypancake",
			"zachattack83",
			"Eldevin",
			"PEEPSTERS",
			"Kolby2020",
			"Chickenduckbird",
			"mickymack",
			"WarbearNomkins",
			"Grand Chicken Lord",
			"Matt Dusek",
			"Gusmanak",
			"Plushie Santa",
			"Plushie Elf",
			"Plushie Snowman",
			"Typheus the Whelp",
			"Plushie Lion",
			"Plushie Mummy",
			"Plushie Panda",
			"Plushie Polar Bear",
			"Plushie Tiger",
			"Plushie Hula Dog",
			"Plushie Leprechaun",
			"Plushie Dino",
			"Plushie Unicorn",
			"Titan of the Fried One",
			"Divine Favor",
			"Wrath of the Fried One",
			"Telamon",
			"Sophisticated Bat",
			"JackofMostTrades",
			"HomingBeacon",
			"Hopelesssly",
			"Hallows Treats",
			"Jack-O-Bat",
			"Builderman",
			"Toy Plane",
			"Toy Teeth",
			"Toy Car",
			"Toy Train",
			"Toy Boss Dino",
			"Toy Remote",
			"Call of the Teddy Bear",
			"Toy Truck",
			"Fried Acolyte",
			"Guest",
			"Haydebug2003",
			"Burning Phoenix",
			"AVote",
			"TrollTideTroll",
			"Ultimate Bowl of Greed",
			"Unlimxted",
			"Combine Garrison",
			"Cluck Buck",
			"Youngtan",
			"Scrub",
			"Shamrock Doge",
			"Uncle Doge",
			"Captain Doge",
			"Abraham Doge",
			"JoeDev",
			"Left Arm of the Fried One",
			"Ejob",
			"RandomRobloxTV",
			"PowerCat123",
			"Visleaf",
			"TheNStar",
			"TheChakraTree",
			"Split Ego",
			"Reggie",
			"Pilot",
			"Majora7",
			"Maelstronomer",
			"ChildofGiotto",
			"Xlzeck",
			"Rhysmon",
			"Nexx",
			"MahBucket",
			"Finland",
			"Noob",
			"TeeVee",
			"Robic",
			"Lyv",
			"Tarfful",
			"Latchie",
			"QuisMo",
			"SoftCollision",
			"Uias",
			"Valletta",
			"GemInNight",
			"Mister Tea",
			"Dextromer",
			"Bowl of Greed",
			"Preston",
			"Toxic",
			"Loogi",
			"Qdhxx",
			"Volttt",
			"DIY Headphones",
			"Sand Eyes Yellow Dragon",
			"Drager",
			"Lord of Greed",
			"Doge",
			"GalaxyFlame",
		},
	}; 
	{
		Name = "Obvious", --NEW / WHITE! All cards before Wingman8 rotate out once a new card comes in. Related cards rotate out at the same time.
		Cost = 50,
		CardsInPack = 4,
		CardPackId = 434684079,
		Description = "Obvious Packs contain only white cards, joke cards and new cards. You must have 10 wins to open these packs.",
		Cards = {
			"Wolfbitten Noob",
			"iiMasant",
			"PencilWizard",
			"Nopants99",
			"Dwarvern Sentry: MAX",
			"Dwarvern Sentry: Delta",
			"Dwarvern Sentry: Gamma",
			"Dwarvern Sentry: Beta",
			"Dwarvern Sentry: Alpha",
			"Dwarvern Captain",
			"Dwarvern Scientist",
			"Dwarvern Mathematician",
			"Dwarvern Engineer",
			"Dwarvern Energist",
			"Dwarvern Miner",
			"CIA Man",
			"HyperBlue",
			"Winchester Rotomo",
			"rhomlevko",
			"mrawesomecarter",
			"__________",
			"JavierCollin88Poppin",
			"YotamTiti",
			"Mohawk2275",
			"Divine_Pengu",
			"Prisman",
			"Yoshius",
			"JayTheCoder",
			"Monopoly Man",
			"Friend Request Spammer",
			"Smart Planner",
			"Stevenl15",
			"Luck Warrior of Pure Gold",
			"Zaquille",
			"Brick_Man",
			"B0BBA",
			"Uncreativename123",
			"Razikai",
			"pa00",
			"666",
			"Overseer Drake",
			"WoodReviewer",
			"Tankbomer",
			"The Piece Breaker",
			"Mr.O the Traveling Merchant",
			"One4utwo4me",
			"InceptionTime",
			"Cooldude4851",
			"Jimminus",
			"Aceguy100",
			"Mariochocolatemilk",
			"HasTheHero",
			"Korblox Shadowmage",
			"Redcliff Heretic",
			"stereoplexus",
			"Cat's Eye Wing Flock",
			"Cat's Eye Corpse Stealer",
			"Cat's Eye, Master of Perception",
			"iAsuka",
			"Samksoon321",
			"ST Leader Keeler1",
			"Brycen27",
			"Bad Bread",
			"Cotton Cavalier",
			"Arashi Pikemen",
			"BerskererPredator450",
			"Meeboid Champion",
			"NerfModder",
			"ClanAtlas",
			"KurosakiDXenos",
			"Skarra the DragonSlayer",
			"Forbidden Power",
			"Sibs",
			"Moon Rabbit's Rage",
			"Pancake Break",
			"BLOXER787",
			"Aurichalcum",
			"BrackioTops",
			"Lilmanofsalem",
			"animallogic",
			"Mzh3000",
			"Miked",
			"Fenrier",
			"JaikKaik",
			"Gravity Inspector",
			"LordFlanz",
			"TheEnderCorp",
			"HuntarioRBLX",
			"Cyandude585",
			"Febrezer",
			"Paraselene Sage",
			"President Duck",
			"Wingman8",
			"Body Guards",
			"Giftsplosion",
			"DrPepperSlayer",
			"Blue Fanatic",
			"Heatlands Vortex",
			"Noob Golem",
			"Green Icon Tree",
			"Kmansong2",
			"Nova",
			"SaxoAttack",
			"Unwanted Trend",
			"Clockwork",
			"Calamity Box",
			"Xor's Lab",
			"Usering",
			"Imaginz00",
			"Scripter",
			"HatHelper",
			"GRAND DAD",
			"RachelDubs",
			"Bling Noob",
			"Clone Fave",
			"Dr.Fave",
			"Cow",
			"Cup O Tea",
			"Fat Cat",
			"Great Lord Egotist",
			"WishNite",
			"Grand Pirate King",
			"TheInnovative",
			"Robot",
			"Greygnarl",
			"Grimclaw the Unholy",
			"Titan's Stone",
			"Titan of the Holy Chamber",
			"Recruiter of the Titans",
			"Divine Favor",
			"Tweety The Twitter Bird",
			"Heavy Rain",
			"BlueTaslem",
			"Nenjas",
			"ASeal",
			"Sorcus",
			"MegaSmiley",
			"Bread Factory",
			"Dragon Horde",
			"Lunar Acolyte",
			"Lunar Warrior",
			"Mimic",
			"Berezaa",
			"Titano's Cavern",
			"Sword Fights on the Heights",
			"Haunted Mansion",
			"Crossroads",
			"Stud",
			"Bloxy Tea Party",
			"Birthday Suprise",
			"SonozakiRaito",
			"Bobaman1",
			"Rukiryo",
			"Moded",
			"Godlysinha",
			"Crystal Cultist",
			"MisterObvious",
			"Bloxikin Horde",
		},
	};
}
-- V2s that need adding into Aife: 
--MahBucket, Ninja, DIY Dominus, Quenty, 
--Pixelflame, Divine Favor, Myrmiredon, 
--Mass Destruction, Stickmasterluke, Stalker, 
--BlazerC, Polyhex, KingShadowCrow, Lando64000, 
--Ripull, Gravity Collapse, NerfModder, Gravity Inspector, 
--Aurichalcum