--main 1
return {
	{
		Name = "Main 1",
		Cost = 25,
		CardsInPack = 3,
		CardPackId = 263658643, 
		Description = "The most basic of all the packs, the noob pack! See if YOU can get a Legendary!",
		Common = {"Training Dummy","Western Bandit","Brymmy","Brycen27","Renaud800","xXVitalityVoidXx","Rainbowjewelninga785","Mrbeanbean2","Keeler1","MajorMattias","Olafisawesome100","ScriptMasTime","DairingPoopHead","Bee","Swarm","Bebee2","BlueTaslem","Jack-O-Bat","Construction Zombie","Toy Remote","Witch","Police Officer","Guest","FishBubble1002","Eye of Overseer","Spikle","Gato Luz","Titano's Cavern","Grandmasters Ninja Dojo","Blockerwiz","Youngtan","Redcliff Messenger","Boogerguy123","Korblox Defender","Korblox General","Korblox Archer","Abraham Doge","Captain Doge","Uncle Doge","Shamrock Doge","Mitpaul","Halo4master233","Godlysinha","Pillager","TheChakraTree","Sylrath","SwatPhantom","Spark","RoboticMob","Pilot","MrMaxi23","Mag","Xlzeck","Sorry","MyDadIsAGuest","Master Josue","Lohit","EXLatios","GalaxyFlame","EpicLatiosLord","DeadZoneHark","DerptasticDevil","Cherie","DDude","Regimen","Zolerus","Tomspick","Kago","FatherChristmaz","Samurai Shock","Anderson","Salesman","RiceStorage","Ninja","Rad","Burglar","TeeVee","Robber","Noob","Otub","Kamov","Ignis Mage","Developer","Newbie","BO0M","Robic","Bob","Cillow","Cowboy","Chef","Ice","Krazy Koala","Langz","Ambamby","Finland","Meeboid","Daisy","Bloated","Life Potion",}, 
		Uncommon = {"Meeboid Champion","TigerCode","Beam Sword","Samksoon321","KurosakiDXenos","Miked","Unwanted Trend","Moon Rabbit's Rage","BlueShadic90","HungryBloxBoy","Robloxian255","Ultoris NOOBrae","Isaac0333-V2","President Duck","Lorenzo77555","Bearded Captain","LordVasco","Pizzablawk","EfanPlayz","MuPower","PEEPSTERS","Saprasam","4.0 Robloxian","popcornhebe","destruction5033","bincent","StayBlue","Beekeeper","Redcliff: Rise!","Redcliff: Decimate!","Inferno!","Wrath of the Fried One","Depths of the Nether","Toy Truck","Toy Plane","Toy Teeth","Toy Car","Bread Factory","Fried Acolyte","Infernal Acolyte","DominatedLegacy","BuzzHamtaro","Bloo","Meebling Infestation","Snowskateer","Teeny Ninja","Ninja Combatant","Ninja Assailant","Ninja Trainee","Ninja Elite","Zedreadr","zPikmon","Unlimxted","GamesBloxx","ChosenCoast","ShyLightness","Redcliff Mauler","Sword Fights on the Heights","Redcliff Archer","Zombie Summoner","Zombie Cultist","Stud","PowerCat123","DerpDerpyness","Mackerel","WildSpeedy","SimpleBeings","Plankton124","Pixellus","Oozlebachr","Oz","Majora7","MICHIKUSCHI","Luigifan103","JackinatorMG","Bobaman1","DeathETM","BUTQUNA","Bowl of Greed","2Hex","Doge","Lebron","MahBucket","HashtagWatermelon","Icepielover23","AntiSammeh","FuryBlocks","Eye Spy","Camo Joe","CinematicMind","Crystal Cultist","Froot Ninja","Dextromer","Glaecium","BadBreadMaker","Calirolls","Brunito","PixelFlameV2","TZSara","Mister Tea","Inventor1116","Luchador","Duckywow","PixelPistol","Uias","Valletta","SoftCollision","QuisMo","MekaX","Latchie","Hodif","BloodSpilled","Tarfful","FuuTuu","PixelFlame","Glaciem Mage","Subata","Saiier","NatzHakz","Dayren","EzCheez","Faultful","Lyv",},
		Rare = {"Coordinated Attack","Febrezer","APlayerOfGames","Wingman8","Forbidden Power","Lopous","zKevin","Card Hoarder","Consume Dream","Accursed Gate","Uberubert","Kit of Deception","Dodgeball Player Blue","Dun_Goof","Korblox Shaman","Brick Bacon","GRAND DAD","MustagedWorldYT","XxFreezerFlamesxX","FatalWing","SirSorin","Flufflefunz","Meme Thief","Crazynoggin","Picopicoman","Doge Hound","CALL OF DOGE!?!","Duel Axe Monster","puffytenter12","Evil Wood Grain","ClanDrone","Mysterious UFO","Cow","Uncomfortably","Beehive","Divine Favor","Fancy Arachnid","Jeptem","ASeal","Toy Train","Serhat12","Dragon Horde","Police Combatant","PassTheToiletPaper","Overseer General","Medic Kit","Liz","Lady RedNight","KingShadowCrow","Hideaki","Fallen Guardian","AVote","Summon! Meeboid Titano!","Meeboid King","Meebling","Meeboid Cultist","Noob Attack! Ninja Stars!","TrollTideTroll","WafflzDude","Odin","Metal Bloxxer","KennedyLeDog","Cyclist","Connoisseur","Cluck Buck","SkySpell","Tomfl","Psychotic","Redcliff Enforcer","Hamstermon","Haunted Mansion","Scrub","Leitris","Lord Tethamet","Byte","JadeFlames","Korblox Archmage","KrocoStar","KingCactaur","Soul Release","Spiderboy","RandomRobloxTV","FancyFame","Bloxy Tea Party","KnightDude","WhiteScarf","Tiny Tank","TheNStar","Split Ego","Reggie","Nicolas1015","MiloCortez","Maelstronomer","HyperVoxel","DataRaven","Assist Trophy","Awful Good","IlIll","ChildofGiotto","Deadeye","DIY Azurewrath","DIY Biggerhead","DIY Dominus","DIY Headphones","Volttt","SirDapper","PhireFox","Mike","Darpeh","GemInNight","Wustard","NICCO","Hoote","Sammeh","Gaomon94","SharpTH","Preston","Toxic","Loogi","Qdhxx","Tom's Beans",}, 
		Epic = {"SaxoAttack","Doneyes","Imaginz00","Gravity Collapse","BuildIntoGames","Prestwick","bengbeng14","UristMcSparks","Scripter","Explode1","SuperCloud9","John and Jane","MinePix110","Isaac0333","Nikilis","Lilly_S","CellBloxTango","RachelDubs","BroRubik","VetexGames","Radello","Maplestick","tbradm","Tinfoilbot","Redcliff Rogue","Widgeon","Dr.Fave","Super Bacon","Anti-Fave","Queen Bee","Mass Epidemic","JackofMostTrades","Witch's True Brew","Traumatic Clown","The Vlad","Chiefjustus","MegaSmiley","Toy Boss Dino","Mimic","Totem of Pixel","Overseer Beast","Luck o The Lobsters","Haydebug2003","Frozen Phoenix","Burning Phoenix","Redcliff Elite Commander","BlazerCV2","KasoduS","Combine Garrison","WaddleTom","Disaster Survival","Crossroads","SonozakiRaito","ZacAttackk","JoeDev","Korblox Deathknight","Korblox Deathkeeper","Right Leg of the Fried One","Left Leg of the Fried One","Right Arm of the Fried One","Left Arm of the Fried One","Ejob","Zombie King","BlazerC","Visleaf","Player","QuentyV2","Bloxikin Horde","Moded","Nexx","Quenty","Rhysmon","Thunder Bolt","XiaoXiaoMan","Dignity","MisterObvious","Fuchsia Eyes Red Dragon","Dued1","Sand Eyes Yellow Dragon","Y05H1M4N","Blue Eyes Indigo Dragon","Teal Eyes Green Dragon",}, 
		Legendary = {"MUTO2014","Erik.Cassel","Mzh3000","Luckymaxer","Paraselene Sage","NearMiss TFW","ST Leader Keeler1","ClanAtlas","Skarra the DragonSlayer","Ultra Doregriffon","Clockwork","RipullV2","Sibs","RukatuKDH","UAE","Her0z","Razuatix","Regular_Show","Vitality Potion","Ultoris Tenebrae","TheSteelEagle","HatHelper","ROBLOXADOR!!","Alkalola","Rockybow","One BLOX Man","inechi","Materking","Hoshpup","1337","Amber","Owen0202","lando64000","DrTrayBlox","legoseed","TheGamer101","ROBLOX","Clone Fave","WishNite","XxWonderzxX","Hopelesssly","HomingBeacon","Nenjas","Murtic","Hallows Treats","Skeleton Armada","Arceusdon","Sorcus","Builderman","Call of the Teddy Bear","Bereghost","PolyHexV2","Berezaa","Biostream","DrKig","JackInTheBlox","The Stalker","NobleDragon","Ripull","Shedletsky the Fried One","Fave","Exine","Bloxy Victory","Rukiryo","StickMasterLuke",}, 
	};
	{
		Name = "Main 2",
		Cost = 25,
		CardsInPack = 3,
		CardPackId = 263658643, 
		Description = "The most basic of all the packs, the noob pack! See if YOU can get a Legendary!",
		Common = {"Training Dummy","Western Bandit","Brymmy","Brycen27","Renaud800","xXVitalityVoidXx","Rainbowjewelninga785","Mrbeanbean2","Keeler1","MajorMattias","Olafisawesome100","ScriptMasTime","DairingPoopHead","Bee","Swarm","Bebee2","BlueTaslem","Jack-O-Bat","Construction Zombie","Toy Remote","Witch","Police Officer","Guest","FishBubble1002","Eye of Overseer","Spikle","Gato Luz","Titano's Cavern","Grandmasters Ninja Dojo","Blockerwiz","Youngtan","Redcliff Messenger","Boogerguy123","Korblox Defender","Korblox General","Korblox Archer","Abraham Doge","Captain Doge","Uncle Doge","Shamrock Doge","Mitpaul","Halo4master233","Godlysinha","Pillager","TheChakraTree","Sylrath","SwatPhantom","Spark","RoboticMob","Pilot","MrMaxi23","Mag","Xlzeck","Sorry","MyDadIsAGuest","Master Josue","Lohit","EXLatios","GalaxyFlame","EpicLatiosLord","DeadZoneHark","DerptasticDevil","Cherie","DDude","Regimen","Zolerus","Tomspick","Kago","FatherChristmaz","Samurai Shock","Anderson","Salesman","RiceStorage","Ninja","Rad","Burglar","TeeVee","Robber","Noob","Otub","Kamov","Ignis Mage","Developer","Newbie","BO0M","Robic","Bob","Cillow","Cowboy","Chef","Ice","Krazy Koala","Langz","Ambamby","Finland","Meeboid","Daisy","Bloated","Life Potion",}, 
		Uncommon = {"Meeboid Champion","TigerCode","Beam Sword","Samksoon321","KurosakiDXenos","Miked","Unwanted Trend","Moon Rabbit's Rage","BlueShadic90","HungryBloxBoy","Robloxian255","Ultoris NOOBrae","Isaac0333-V2","President Duck","Lorenzo77555","Bearded Captain","LordVasco","Pizzablawk","EfanPlayz","MuPower","PEEPSTERS","Saprasam","4.0 Robloxian","popcornhebe","destruction5033","bincent","StayBlue","Beekeeper","Redcliff: Rise!","Redcliff: Decimate!","Inferno!","Wrath of the Fried One","Depths of the Nether","Toy Truck","Toy Plane","Toy Teeth","Toy Car","Bread Factory","Fried Acolyte","Infernal Acolyte","DominatedLegacy","BuzzHamtaro","Bloo","Meebling Infestation","Snowskateer","Teeny Ninja","Ninja Combatant","Ninja Assailant","Ninja Trainee","Ninja Elite","Zedreadr","zPikmon","Unlimxted","GamesBloxx","ChosenCoast","ShyLightness","Redcliff Mauler","Sword Fights on the Heights","Redcliff Archer","Zombie Summoner","Zombie Cultist","Stud","PowerCat123","DerpDerpyness","Mackerel","WildSpeedy","SimpleBeings","Plankton124","Pixellus","Oozlebachr","Oz","Majora7","MICHIKUSCHI","Luigifan103","JackinatorMG","Bobaman1","DeathETM","BUTQUNA","Bowl of Greed","2Hex","Doge","Lebron","MahBucket","HashtagWatermelon","Icepielover23","AntiSammeh","FuryBlocks","Eye Spy","Camo Joe","CinematicMind","Crystal Cultist","Froot Ninja","Dextromer","Glaecium","BadBreadMaker","Calirolls","Brunito","PixelFlameV2","TZSara","Mister Tea","Inventor1116","Luchador","Duckywow","PixelPistol","Uias","Valletta","SoftCollision","QuisMo","MekaX","Latchie","Hodif","BloodSpilled","Tarfful","FuuTuu","PixelFlame","Glaciem Mage","Subata","Saiier","NatzHakz","Dayren","EzCheez","Faultful","Lyv",},
		Rare = {"Coordinated Attack","Febrezer","APlayerOfGames","Wingman8","Forbidden Power","Lopous","zKevin","Card Hoarder","Consume Dream","Accursed Gate","Uberubert","Kit of Deception","Dodgeball Player Blue","Dun_Goof","Korblox Shaman","Brick Bacon","GRAND DAD","MustagedWorldYT","XxFreezerFlamesxX","FatalWing","SirSorin","Flufflefunz","Meme Thief","Crazynoggin","Picopicoman","Doge Hound","CALL OF DOGE!?!","Duel Axe Monster","puffytenter12","Evil Wood Grain","ClanDrone","Mysterious UFO","Cow","Uncomfortably","Beehive","Divine Favor","Fancy Arachnid","Jeptem","ASeal","Toy Train","Serhat12","Dragon Horde","Police Combatant","PassTheToiletPaper","Overseer General","Medic Kit","Liz","Lady RedNight","KingShadowCrow","Hideaki","Fallen Guardian","AVote","Summon! Meeboid Titano!","Meeboid King","Meebling","Meeboid Cultist","Noob Attack! Ninja Stars!","TrollTideTroll","WafflzDude","Odin","Metal Bloxxer","KennedyLeDog","Cyclist","Connoisseur","Cluck Buck","SkySpell","Tomfl","Psychotic","Redcliff Enforcer","Hamstermon","Haunted Mansion","Scrub","Leitris","Lord Tethamet","Byte","JadeFlames","Korblox Archmage","KrocoStar","KingCactaur","Soul Release","Spiderboy","RandomRobloxTV","FancyFame","Bloxy Tea Party","KnightDude","WhiteScarf","Tiny Tank","TheNStar","Split Ego","Reggie","Nicolas1015","MiloCortez","Maelstronomer","HyperVoxel","DataRaven","Assist Trophy","Awful Good","IlIll","ChildofGiotto","Deadeye","DIY Azurewrath","DIY Biggerhead","DIY Dominus","DIY Headphones","Volttt","SirDapper","PhireFox","Mike","Darpeh","GemInNight","Wustard","NICCO","Hoote","Sammeh","Gaomon94","SharpTH","Preston","Toxic","Loogi","Qdhxx","Tom's Beans",}, 
		Epic = {"SaxoAttack","Doneyes","Imaginz00","Gravity Collapse","BuildIntoGames","Prestwick","bengbeng14","UristMcSparks","Scripter","Explode1","SuperCloud9","John and Jane","MinePix110","Isaac0333","Nikilis","Lilly_S","CellBloxTango","RachelDubs","BroRubik","VetexGames","Radello","Maplestick","tbradm","Tinfoilbot","Redcliff Rogue","Widgeon","Dr.Fave","Super Bacon","Anti-Fave","Queen Bee","Mass Epidemic","JackofMostTrades","Witch's True Brew","Traumatic Clown","The Vlad","Chiefjustus","MegaSmiley","Toy Boss Dino","Mimic","Totem of Pixel","Overseer Beast","Luck o The Lobsters","Haydebug2003","Frozen Phoenix","Burning Phoenix","Redcliff Elite Commander","BlazerCV2","KasoduS","Combine Garrison","WaddleTom","Disaster Survival","Crossroads","SonozakiRaito","ZacAttackk","JoeDev","Korblox Deathknight","Korblox Deathkeeper","Right Leg of the Fried One","Left Leg of the Fried One","Right Arm of the Fried One","Left Arm of the Fried One","Ejob","Zombie King","BlazerC","Visleaf","Player","QuentyV2","Bloxikin Horde","Moded","Nexx","Quenty","Rhysmon","Thunder Bolt","XiaoXiaoMan","Dignity","MisterObvious","Fuchsia Eyes Red Dragon","Dued1","Sand Eyes Yellow Dragon","Y05H1M4N","Blue Eyes Indigo Dragon","Teal Eyes Green Dragon",}, 
		Legendary = {"MUTO2014","Erik.Cassel","Mzh3000","Luckymaxer","Paraselene Sage","NearMiss TFW","ST Leader Keeler1","ClanAtlas","Skarra the DragonSlayer","Ultra Doregriffon","Clockwork","RipullV2","Sibs","RukatuKDH","UAE","Her0z","Razuatix","Regular_Show","Vitality Potion","Ultoris Tenebrae","TheSteelEagle","HatHelper","ROBLOXADOR!!","Alkalola","Rockybow","One BLOX Man","inechi","Materking","Hoshpup","1337","Amber","Owen0202","lando64000","DrTrayBlox","legoseed","TheGamer101","ROBLOX","Clone Fave","WishNite","XxWonderzxX","Hopelesssly","HomingBeacon","Nenjas","Murtic","Hallows Treats","Skeleton Armada","Arceusdon","Sorcus","Builderman","Call of the Teddy Bear","Bereghost","PolyHexV2","Berezaa","Biostream","DrKig","JackInTheBlox","The Stalker","NobleDragon","Ripull","Shedletsky the Fried One","Fave","Exine","Bloxy Victory","Rukiryo","StickMasterLuke",}, 
	};
	{
		Name = "Obvious",
		Cost = 50,
		CardsInPack = 3,
		CardPackId = 434684079, 
		Description = "Do you have what it takes to buy a pack from MisterObvious' store? Find out! Price will lower overtime.",
		Common = {"Training Dummy","Western Bandit","Brymmy","Brycen27","SomaticMizuSan","Renaud800","xXVitalityVoidXx","Rainbowjewelninga785","HatdaCat","Bee","Swarm","Bebee2","Titan's Stone","Jack-O-Bat","BlueTaslem","Dodgeball Player Red","Construction Zombie"},
		Uncommon = {"Meeboid Champion","TigerCode","Beam Sword","Samksoon321","KurosakiDXenos","Miked","Unwanted Trend","Moon Rabbit's Rage","BlueShadic90","HungryBloxBoy","Robloxian255","Ultoris NOOBrae","EfanPlayz","Vermin's Caress","Traumaturge","Rat King","Plushie Tiger","Recruiter of the Titans","Redcliff: Rise!","Redcliff: Decimate!","Inferno!","Wrath of the Fried One","Depths of the Nether","Cluck Buck","Psychotic","Theawesomist19"},
		Rare = {"Coordinated Attack","Febrezer","APlayerOfGames","Wingman8","Forbidden Power","Uberubert","Kit of Deception","Dodgeball Player Blue","Lopous","zKevin","Card Hoarder","Consume Dream","Accursed Gate","Grand Ignis Mage","Grand Glaciem Mage","Grand Chicken Lord","JJ5x5","Frosty The Snowman","Dragon's Charm","Plushie Snowman","Robot","Fleskhjerta","Plushie Hula Dog","Plushie Leprechaun","Plushie Panda","Oddman's Gambit","Overseer's Steed","Titan of the Holy Chamber","Titan of the Fried One","Titan of the Dying Forest","Titan of the Deep Below","Titan of the Infernal Abyss","Divine Favor","Fancy Arachnid","Jeptem","ASeal","Mummy Peasant","Weaven","Sophisticated Bat"},
		Epic = {"SaxoAttack","Doneyes","Gravity Collapse","BuildIntoGames","Vitality Potion","Prestwick","bengbeng14","UristMcSparks","Explode1","SuperCloud9","RachelDubs","Myrmiredon","MrDoombringer","TheInnovative","LeetWizard","Plushie Dino","Mass Epidemic","JackofMostTrades","The Vlad","Chiefjustus","Redrune Raider","Zom-nobi","Alexnewtron","Witch's True Brew","Traumatic Clown","The Vlad"},
		Legendary = {"MUTO2014","Erik.Cassel","Mzh3000","Luckymaxer","Paraselene Sage","NearMiss TFW","ST Leader Keeler1","ClanAtlas","Skarra the DragonSlayer","Ultra Doregriffon","Clockwork","RipullV2","Sibs","TheSteelEagle","Amber","Great Lord Egotist","RukatuKDH","UAE","Her0z","Razuatix","Regular_Show","Vitality Potion","Ultoris Tenebrae","HatHelper","ROBLOXADOR!!","Alkalola","Rockybow","One BLOX Man","inechi","Materking","Hoshpup","1337","Amber","Owen0202","lando64000","DrTrayBlox","legoseed","TheGamer101","ROBLOX","Clone Fave","WishNite","XxWonderzxX","Hopelesssly","HomingBeacon","Nenjas","Murtic","Hallows Treats","Skeleton Armada","Arceusdon","Sorcus","Builderman","Call of the Teddy Bear","Bereghost","PolyHexV2","Berezaa","Biostream","DrKig","JackInTheBlox","The Stalker","NobleDragon","Ripull","Shedletsky the Fried One","Fave","Exine","Bloxy Victory","Rukiryo","StickMasterLuke",},
	};
	{
		Name = "Vis",
		Cost = 25,
		CardsInPack = 3,
		CardPackId = 263658643, 
		Description = "The most basic of all the packs, the noob pack! See if YOU can get a Legendary!",
		Common = {"Training Dummy","Western Bandit","Brymmy","Brycen27","Renaud800","xXVitalityVoidXx","Rainbowjewelninga785","Mrbeanbean2","Keeler1","MajorMattias","Olafisawesome100","ScriptMasTime","DairingPoopHead","Bee","Swarm","Bebee2","BlueTaslem","Jack-O-Bat","Construction Zombie","Toy Remote","Witch","Police Officer","Guest","FishBubble1002","Eye of Overseer","Spikle","Gato Luz","Titano's Cavern","Grandmasters Ninja Dojo","Blockerwiz","Youngtan","Redcliff Messenger","Boogerguy123","Korblox Defender","Korblox General","Korblox Archer","Abraham Doge","Captain Doge","Uncle Doge","Shamrock Doge","Mitpaul","Halo4master233","Godlysinha","Pillager","TheChakraTree","Sylrath","SwatPhantom","Spark","RoboticMob","Pilot","MrMaxi23","Mag","Xlzeck","Sorry","MyDadIsAGuest","Master Josue","Lohit","EXLatios","GalaxyFlame","EpicLatiosLord","DeadZoneHark","DerptasticDevil","Cherie","DDude","Regimen","Zolerus","Tomspick","Kago","FatherChristmaz","Samurai Shock","Anderson","Salesman","RiceStorage","Ninja","Rad","Burglar","TeeVee","Robber","Noob","Otub","Kamov","Ignis Mage","Developer","Newbie","BO0M","Robic","Bob","Cillow","Cowboy","Chef","Ice","Krazy Koala","Langz","Ambamby","Finland","Meeboid","Daisy","Bloated","Life Potion",}, 
		Uncommon = {"Meeboid Champion","TigerCode","Beam Sword","Samksoon321","KurosakiDXenos","Miked","Unwanted Trend","Moon Rabbit's Rage","BlueShadic90","HungryBloxBoy","Robloxian255","Ultoris NOOBrae","Isaac0333-V2","President Duck","Lorenzo77555","Bearded Captain","LordVasco","Pizzablawk","EfanPlayz","MuPower","PEEPSTERS","Saprasam","4.0 Robloxian","popcornhebe","destruction5033","bincent","StayBlue","Beekeeper","Redcliff: Rise!","Redcliff: Decimate!","Inferno!","Wrath of the Fried One","Depths of the Nether","Toy Truck","Toy Plane","Toy Teeth","Toy Car","Bread Factory","Fried Acolyte","Infernal Acolyte","DominatedLegacy","BuzzHamtaro","Bloo","Meebling Infestation","Snowskateer","Teeny Ninja","Ninja Combatant","Ninja Assailant","Ninja Trainee","Ninja Elite","Zedreadr","zPikmon","Unlimxted","GamesBloxx","ChosenCoast","ShyLightness","Redcliff Mauler","Sword Fights on the Heights","Redcliff Archer","Zombie Summoner","Zombie Cultist","Stud","PowerCat123","DerpDerpyness","Mackerel","WildSpeedy","SimpleBeings","Plankton124","Pixellus","Oozlebachr","Oz","Majora7","MICHIKUSCHI","Luigifan103","JackinatorMG","Bobaman1","DeathETM","BUTQUNA","Bowl of Greed","2Hex","Doge","Lebron","MahBucket","HashtagWatermelon","Icepielover23","AntiSammeh","FuryBlocks","Eye Spy","Camo Joe","CinematicMind","Crystal Cultist","Froot Ninja","Dextromer","Glaecium","BadBreadMaker","Calirolls","Brunito","PixelFlameV2","TZSara","Mister Tea","Inventor1116","Luchador","Duckywow","PixelPistol","Uias","Valletta","SoftCollision","QuisMo","MekaX","Latchie","Hodif","BloodSpilled","Tarfful","FuuTuu","PixelFlame","Glaciem Mage","Subata","Saiier","NatzHakz","Dayren","EzCheez","Faultful","Lyv",},
		Rare = {"Coordinated Attack","Febrezer","APlayerOfGames","Wingman8","Forbidden Power","Lopous","zKevin","Card Hoarder","Consume Dream","Accursed Gate","Uberubert","Kit of Deception","Dodgeball Player Blue","Dun_Goof","Korblox Shaman","Brick Bacon","GRAND DAD","MustagedWorldYT","XxFreezerFlamesxX","FatalWing","SirSorin","Flufflefunz","Meme Thief","Crazynoggin","Picopicoman","Doge Hound","CALL OF DOGE!?!","Duel Axe Monster","puffytenter12","Evil Wood Grain","ClanDrone","Mysterious UFO","Cow","Uncomfortably","Beehive","Divine Favor","Fancy Arachnid","Jeptem","ASeal","Toy Train","Serhat12","Dragon Horde","Police Combatant","PassTheToiletPaper","Overseer General","Medic Kit","Liz","Lady RedNight","KingShadowCrow","Hideaki","Fallen Guardian","AVote","Summon! Meeboid Titano!","Meeboid King","Meebling","Meeboid Cultist","Noob Attack! Ninja Stars!","TrollTideTroll","WafflzDude","Odin","Metal Bloxxer","KennedyLeDog","Cyclist","Connoisseur","Cluck Buck","SkySpell","Tomfl","Psychotic","Redcliff Enforcer","Hamstermon","Haunted Mansion","Scrub","Leitris","Lord Tethamet","Byte","JadeFlames","Korblox Archmage","KrocoStar","KingCactaur","Soul Release","Spiderboy","RandomRobloxTV","FancyFame","Bloxy Tea Party","KnightDude","WhiteScarf","Tiny Tank","TheNStar","Split Ego","Reggie","Nicolas1015","MiloCortez","Maelstronomer","HyperVoxel","DataRaven","Assist Trophy","Awful Good","IlIll","ChildofGiotto","Deadeye","DIY Azurewrath","DIY Biggerhead","DIY Dominus","DIY Headphones","Volttt","SirDapper","PhireFox","Mike","Darpeh","GemInNight","Wustard","NICCO","Hoote","Sammeh","Gaomon94","SharpTH","Preston","Toxic","Loogi","Qdhxx","Tom's Beans",}, 
		Epic = {"SaxoAttack","Doneyes","Imaginz00","Gravity Collapse","BuildIntoGames","Prestwick","bengbeng14","UristMcSparks","Scripter","Explode1","SuperCloud9","John and Jane","MinePix110","Isaac0333","Nikilis","Lilly_S","CellBloxTango","RachelDubs","BroRubik","VetexGames","Radello","Maplestick","tbradm","Tinfoilbot","Redcliff Rogue","Widgeon","Dr.Fave","Super Bacon","Anti-Fave","Queen Bee","Mass Epidemic","JackofMostTrades","Witch's True Brew","Traumatic Clown","The Vlad","Chiefjustus","MegaSmiley","Toy Boss Dino","Mimic","Totem of Pixel","Overseer Beast","Luck o The Lobsters","Haydebug2003","Frozen Phoenix","Burning Phoenix","Redcliff Elite Commander","BlazerCV2","KasoduS","Combine Garrison","WaddleTom","Disaster Survival","Crossroads","SonozakiRaito","ZacAttackk","JoeDev","Korblox Deathknight","Korblox Deathkeeper","Right Leg of the Fried One","Left Leg of the Fried One","Right Arm of the Fried One","Left Arm of the Fried One","Ejob","Zombie King","BlazerC","Visleaf","Player","QuentyV2","Bloxikin Horde","Moded","Nexx","Quenty","Rhysmon","Thunder Bolt","XiaoXiaoMan","Dignity","MisterObvious","Fuchsia Eyes Red Dragon","Dued1","Sand Eyes Yellow Dragon","Y05H1M4N","Blue Eyes Indigo Dragon","Teal Eyes Green Dragon",}, 
		Legendary = {"MUTO2014","Erik.Cassel","Mzh3000","Luckymaxer","Paraselene Sage","NearMiss TFW","ST Leader Keeler1","ClanAtlas","Skarra the DragonSlayer","Ultra Doregriffon","Clockwork","RipullV2","Sibs","RukatuKDH","UAE","Her0z","Razuatix","Regular_Show","Vitality Potion","Ultoris Tenebrae","TheSteelEagle","HatHelper","ROBLOXADOR!!","Alkalola","Rockybow","One BLOX Man","inechi","Materking","Hoshpup","1337","Amber","Owen0202","lando64000","DrTrayBlox","legoseed","TheGamer101","ROBLOX","Clone Fave","WishNite","XxWonderzxX","Hopelesssly","HomingBeacon","Nenjas","Murtic","Hallows Treats","Skeleton Armada","Arceusdon","Sorcus","Builderman","Call of the Teddy Bear","Bereghost","PolyHexV2","Berezaa","Biostream","DrKig","JackInTheBlox","The Stalker","NobleDragon","Ripull","Shedletsky the Fried One","Fave","Exine","Bloxy Victory","Rukiryo","StickMasterLuke",}, 
	}
}