--main 1
local packs = {
	{
		Name = "Exine", --STAPLES!
		PriceInBloxBux = 25,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 596205187,
		Description = "Curated by the best players of the game, Exine contains only good cards.",
		Cards = {
			-- Important Staples; don't take out of this pack.
			"Thunder Bolt",
			"Luck o the Lobsters",
			"Mass Epidemic",
			"Hallows Treats",
			"Divine Favor",
			"Stud",
			"Lunar Acolyte",
			"Titano's Cavern",
			"Exine", -- The kids are gonna want the card in the pack cover, y'know?
			-- Each section has nine commons, seven uncommons, five rares, three epics and three legendaries.
			-- Blue Commons
			"Icerain",
			"DeadZoneHark",
			"Jimminus",
			"Korblox Archer",
			"Razikai",
			"Spiderboy",
			"wer8888",
			"DairingPoopHead",
			"Spark",
			-- Blue Uncommons
			"Acolyte of the Rift",
			"Glaciem Mage",
			"HuntarioRBLX",
			"JackinatorMG",
			"AsrielMemer",
			"Froot Ninja",
			"Skullsten",
			-- Blue Rares
			"KrocoStar",
			"SharpTH",
			"Mike",
			"Lord Tethamet",
			"Korblox Archmage",
			-- Blue Epics
			"tbradm",
			"B0BBA",
			"VetexGames",
			-- Blue Legendaries
			"Silver_Semtexagon",
			"DrTrayBlox",
			"Megalodon the Dragon-Shark",
			-- Red Commons
			"Ambamby",
			"Anderson",
			"Cowboy",
			"DerptasticDevil",
			"Dodgeball Player Red",
			"Rad",
			"ThatGrimGuy",
			"Mag",
			"Redcliff Messenger",
			-- Red Uncommons
			"Pixellus",
			"Mitpaul",
			"Dayren",
			"Damaging26",
			"Infernal Acolyte",
			"Ninja Elite",
			"Oz",
			-- Red Rares
			"Lady RedNight",
			"AVote",
			"Rinicye",
			"Crazynoggin",
			"Odin",
			-- Red Epics
			"Player",
			"Taymaster",
			"ChosenCoast",
			-- Red Legendaries
			"The Stalker",
			"Jayson13",
			"Nymn the Redrune Leader",
			-- Green Commons
			"Langz",
			"Chef",
			"Boogerguy123",
			"Spikle",
			"Keeler1",
			"Glaecium",
			"Pillager",
			"MyDadIsAGuest",
			"Eye of Overseer",
			-- Green Uncommons
			"Necromantic Acolyte",
			"Oozlebachr",
			"Duckywow",
			"Inventor1116",
			"Luchador",
			"Samksoon321",
			"Kcbeast666",
			-- Green Rares
			"IlIll",
			"Wustard",
			"Tom's Beans",
			"KingCactaur",
			"Overseer General",
			-- Green Epics
			"Brick_Man",
			"XiaoXiaoMan",
			"KasoduS",
			-- Green Legendaries
			"PolyHexV2",
			"Blockhaak",
			"Zerax the Untameable",
			-- Yellow Commons
			"Guest",
			"Graalgamer",
			"Finland",
			"TeeVee",
			"TheChakraTree",
			"Western Bandit",
			"Pilgrim",
			"Bigtank_s",
			"Shamrock Doge",
			-- Yellow Uncommons
			"Latchie",
			"animallogic",
			"Valletta",
			"Lyv",
			"MahBucket",
			"Fried Acolyte",
			"Pikachukiller101",
			-- Yellow Rares
			"Qdhxx",
			"DIY Headphones",
			"Card Hoarder",
			"Uberubert",
			"Cluck Buck",
			-- Yellow Epics
			"Visleaf",
			"Ejob",
			"MinePix110",
			-- Yellow Legendaries
			"JayTheCoder",
			"TheGamer101",
			"Typheus the Whelp",
		},
	}; 
	{
		Name = "Dominion", --RED!
		PriceInBloxBux = 30,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 842435184, --721400845,
		Description = "Red is the colour of power, ambition, and control. Dominion packs contain cards that cost red!",
		Cards = {
			"DoomedAdventurer",
			"Magical Girl Histor",
			"Vinrole",
			"Melon Desu",
			"ZeDerpyDonal",
			"Sands of Purgatory",
			"rachjumper",
			"Steel Chair",
			"DrWeaseI",
			"stormmaster7722",
			"ThatGrimGuy",
			"iamlogic",
			"B550",
			"Damaging26, Flaming Fighter",
			"Alar Myrmidon",
			"Alar Blade Chaser",
			"Alar Herald",
			"ProjectSlayer",
			"Histor, Blood Warrior",
			"Aesura",
			"superkicker2005",
			"AMerryCan",
			"Shard Master",
			"Beyondthegong",
			"Damaging26",
			"MarissaKitty04",
			"ChaoticCommando",
			"how_inconvenient",
			"TheJazzCat22",
			"Cindering",
			"HungryBloxBoy",
			"SoulSearch",
			"Eye of Heaven",
			"UHunterU",
			"Roblox Gift Card",
			"MagikalYawn",
			"SubZeroExtaByte0",
			"Javier Killer",
			"Peika Sammai",
			"Treas0ner-L",
			"74Riley",
			"Thesupernessiiiii",
			"Has",
			"LeTruth",
			"AVote",
			"Epic Sauce",
			"NullSenseStudio",
			"Burning Tree",
			"Dodgeball Gambler Red",
			"Kinnis97",
			"Tone",
			"Ninja Kitty",
			"KnitJa",
			"Fire Fighter",
			"Drager Bot",
			"Supersky712",
			"BoomAtack",
			"Mafia Grunt",
			"Tricky Magician",
			"iiMasant",
			"Dwarvern Sentry: MAX",
			"Dwarvern Sentry: Delta",
			"Dwarvern Sentry: Gamma",
			"Dwarvern Sentry: Beta",
			"Dwarvern Sentry: Alpha",
			"Dwarvern Captain",
			"Dwarvern Scientist",
			"Dwarvern Mathematician",
			"Dwarvern Engineer",
			"Dwarvern Energist",
			"Dwarvern Miner",
			"Winchester Rotomo",
			"mrawesomecarter",
			"JavierCollin88Poppin",
			"Mohawk2275",
			"Prisman",
			"FabulousMettaton123",
			"666",
			"WoodReviewer",
			"One4utwo4me",
			[[One_Thousand_Deaths]],
			"Burning_Soul_Blade",
			"Cooldude4851",
			"Crazyblox",
			"Cotton Cavalier",
			"Arashi Pikemen",
			"HeyItsColin",
			"BerskererPredator450",
			"DrPepperSlayer",
			"MUTO2014",
			"Meeboid Champion",
			"NerfModder",
			"Beam Sword",
			"ClanAtlas",
			"KurosakiDXenos",
			"Doneyes",
			"Skarra the DragonSlayer",
			"Forbidden Power",
			"Sibs",
			"SomaticMizuSan",
			"Moon Rabbit's Rage",
			"UAE",
			"Kit of Deception",
			"Robloxian255",
			"UristMcSparks",
			"zKevin",
			"Explode1",
			"Ultoris Tenebrae",
			"TheSteelEagle",
			"ROBLOXADOR!!",
			"XxFreezerFlamesxX",
			"LordVasco",
			"Isaac0333",
			"Alkalola",
			"Nikilis",
			"Rockybow",
			"Crazynoggin",
			"Hoshpup",
			"Aife",
			"Duel Axe Monster",
			"ScriptMasTime",
			"Redcliff Rogue",
			"Anti-Fave",
			"Super Bacon",
			"legoseed",
			"Taymaster",
			"TheAmazeMan",
			"Rinicye",
			"AllStarBren",
			"Paranormanbiggestfan",
			"Deathaman211",
			"Grand Ignis Mage",
			"MrDoombringer",
			"Fleskhjerta",
			"Dragon's Charm",
			"Nymn the Redrune Leader",
			"Titan of the Infernal Abyss",
			"Inferno!",
			"Redcliff: Decimate!",
			"Redcliff: Rise!",
			"Divine Favor",
			"Dodgeball Player Red",
			"Ozzypig",
			"Papasmurf",
			"Redrune Raider",
			"The Vlad",
			"Chiefjustus",
			"Infernal Acolyte",
			"SirAdurite",
			"Totem of Pixel",
			"PassTheToiletPaper",
			"Luck o The Lobsters",
			"Lady RedNight",
			"FishBubble1002",
			"Fallen Guardian",
			"BuzzHamtaro",
			"Primal Gato",
			"Jayson13",
			"The Stalker",
			"Zedreadr",
			"Drakobloxxer",
			"WafflzDude",
			"Odin",
			"KennedyLeDog",
			"Connoisseur",
			"ChosenCoast",
			"Blockerwiz",
			"Redcliff Enforcer",
			"Redcliff Mauler",
			"Redcliff Elite Commander",
			"Redcliff Messenger",
			"SkySpell",
			"Tomfl",
			"Grandmasters Ninja Dojo",
			"Redcliff Archer",
			"DrKig",
			"Right Leg of the Fried One",
			"Mitpaul",
			"WhiteScarf",
			"RoboticMob",
			"Player",
			"Plankton124",
			"Pixellus",
			"Oz",
			"Mag",
			"HyperVoxel",
			"DataRaven",
			"BUTQUNA",
			"ZacAttackk",
			"Sorry",
			"HashtagWatermelon",
			"Ambamby",
			"Cowboy",
			"Ignis Mage",
			"Kamov",
			"Ninja",
			"Rad",
			"Anderson",
			"Cherie",
			"FatherChristmaz",
			"Tomspick",
			"DerptasticDevil",
			"PixelFlame",
			"FuuTuu",
			"BloodSpilled",
			"Hodif",
			"BO0M",
			"Ninja Elite",
			"Ninja Trainee",
			"Ninja Assailant",
			"Ninja Combatant",
			"Teeny Ninja",
			"AntiSammeh",
			"Sammeh",
			"PixelPistol",
			"Noob Attack! Ninja Stars!",
			"SirDapper",
			"DIY Biggerhead",
			"BlazerC",
			"Fuchsia Eyes Red Dragon",
			"Dignity",
			"Fave",
			"Exine",
			"Bloxy Victory",
		},
	}; 
	{
		Name = "Vitality", --GREEN!
		PriceInBloxBux = 30,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 721399805,
		Description = "Green is the colour of life, growth, and the primal forces. Vitality packs contain cards that cost green!",
		Cards = {
			"zabiehunter",
			"Roundawsome",
			"Tootso",
			"SnailMan39",
			"Darr1432",
			"Haunted Mansion",
			"jojobinks321",
			"Enriched Neutrinous",
			"Damarioguy",
			"Walyn",
			"BandiheartYT",
			"Indoorsnowball",
			"Shaylan007",
			"Wooden Chair",
			"Tl_rd",
			"ThePestilentOne",
			"Yggdrasil Faerie",
			"Wizardguy34",
			"CjMcGamingYT",
			"vanjohnson",
			"ChaseThePsycho",
			"Alar Sentinel",
			"Alar Blade Archer",
			"Alar Trainee",
			"Neutrinous",
			"Turtleuser3",
			"Superland6",
			"iSpaceDonut",
			"Enderlox1",
			"Lord_Gizmo",
			"Wrath of King Gecko",
			"iiSmolToaster",
			"Saprasam",
			"BonesMcCormick",
			"Kariu",
			"madattak",
			"CrazyCaleb77",
			"Uncreation",
			"WebGL3D",
			"CorgiParade",
			"brickmason",
			"Classy Bear",
			"Cat Ears Maid",
			"HyperBlue",
			"rhomlevko",
			"__________",
			"Smart Planner",
			"Zombie",
			"Brick_Man",
			"Uncreativename123",
			"pa00",
			"Overseer Drake",
			"Tankbomer",
			"InceptionTime",
			"Aceguy100",
			"Mariochocolatemilk",
			"HasTheHero",
			"Korblox Shadowmage",
			"Redcliff Heretic",
			"stereoplexus",
			"Cat's Eye Wing Flock",
			"Cat's Eye Corpse Stealer",
			"Cat's Eye, Master of Perception",
			"iAsuka",
			"TigerCode",
			"APlayerOfGames",
			"Samksoon321",
			"ST Leader Keeler1",
			"Brymmy",
			"Brycen27",
			"Bad Bread",
			"Razuatix",
			"Mrbeanbean2",
			"Bearded Captain",
			"Keeler1",
			"FatalWing",
			"EfanPlayz",
			"inechi",
			"BroRubik",
			"1337",
			"Picopicoman",
			"Beeism",
			"Alapz",
			"Blockhaak",
			"MLGSPONGE",
			"GreenHearted",
			"ReverseBackwards",
			"Gangmanstyle556",
			"Vermin's Caress",
			"Accursed Gate",
			"Rat King",
			"Grand Meeboid Totem",
			"Myrmiredon",
			"JJ5x5",
			"Monkey",
			"Zerax the Untameable",
			"Overseer's Steed",
			"Oddman's Gambit",
			"Titan of the Dying Forest",
			"Mass Epidemic",
			"Divine Favor",
			"Mummy Peasant",
			"Zom-nobi",
			"XxWonderzxX",
			"Witch's True Brew",
			"Murtic",
			"Fancy Arachnid",
			"Construction Zombie",
			"Traumatic Clown",
			"Jeptem",
			"Necromantic Acolyte",
			"Eye of Overseer",
			"Overseer Beast",
			"Overseer General",
			"Overseer Prophet",
			"LuckyTux",
			"Medic Kit",
			"KingShadowCrow",
			"Bereghost",
			"PolyHex",
			"Spikle",
			"1x1x1x1",
			"Biostream",
			"Ripull",
			"Pirate",
			"KasoduS",
			"WaddleTom",
			"Leitris",
			"Boogerguy123",
			"Byte",
			"Left Leg of the Fried One",
			"Zombie King",
			"Zombie Summoner",
			"Zombie Cultist",
			"KingCactaur",
			"DerpDerpyness",
			"Pillager",
			"Oozlebachr",
			"MrMaxi23",
			"Nicolas1015",
			"MiloCortez",
			"StickMasterLuke",
			"XiaoXiaoMan",
			"Quenty",
			"MyDadIsAGuest",
			"IlIll",
			"Meeboid",
			"Langz",
			"Krazy Koala",
			"Bob",
			"Chef",
			"Cillow",
			"Otub",
			"Robber",
			"Burglar",
			"Glaecium",
			"Life Potion",
			"Zolerus",
			"Meeboid Cultist",
			"Meebling",
			"Meebling Infestation",
			"NatzHakz",
			"Faultful",
			"Saiier",
			"MekaX",
			"Duckywow",
			"Inventor1116",
			"Luchador",
			"TZSara",
			"BadBreadMaker",
			"Calirolls",
			"Camo Joe",
			"Chaoszeroomega",
			"Meeboid King",
			"Summon! Meeboid Titano!",
			"Hoote",
			"NICCO",
			"Wustard",
			"Tom's Beans",
			"PhireFox",
			"Awful Good",
			"Deadeye",
			"DIY Dominus",
			"Teal Eyes Green Dragon",
			"Icepielover23",
			"Fate_Sealed",
			"Jimmyin1",
		},
	}; 
	{
		Name = "Thought", --BLUE!
		PriceInBloxBux = 30,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 721399466,
		Description = "Blue is the colour of logic, order, and structure. Thought packs contain cards that cost blue!",
		Cards = {
			"WrathOfAzure",
			"CopperGlow",
			"Frosted Shaman Marissa",
			"WookieCookieHD",
			"SpacielChiald",
			"Police Taskmaster",
			"PurpleBoy329",
			"President Duck", --Rapid Response
			"MyCutenesskills",
			"DunclubDuncan",
			"Creeperkiller510",
			"Modern Chair",
			"Permafrost Storm",
			"MesouricPhantom976",
			"Silver_Semtexagon",
			"Arte71",
			"AMerryCan",
			"kickertoken",
			"ImaUMBREON",
			"caone",
			"xiVirtual",
			"Killar1234567",
			"EvilJacobthehero2013",
			"Regular_Talkshow",
			"wikiwakiwoirier",
			"Your_Name",
			"Friaza",
			"Deadly Dicey Duo",
			"hyp3rdeath",
			"Steam Razikai",
			"Fenfie08",
			"Jimminus",
			"Bearded Captain",
 			"Rollernaut",
			"SONICTHEHEDGEHOGXXX",
			"Razikai's Exploration",
			"Ghost Dragon",
			"madkey900",
			"RaveTea",
			"Xenotrent",
			"Icerain",
			"Deep Sea Diver",
			"Dicey Drake",
			"Stravant",
			"Ship Raider",
			"DJ Kangaroo",
			"Aesthetical",
			"CalmFoxz",
			"The Gentlemaniac",
			"ReeseMcBlox",
			"Yoshius",
			"Nopants99",
			"CIA Man",
			"FabulousBench",
			"Stevenl15",
			"B0BBA",
			"Razikai",
			"Fenrier",
			"JaikKaik",
			"Gravity Inspector",
			"LordFlanz",
			"TheEnderCorp",
			"ShockingRobux",
			"HuntarioRBLX",
			"Cyandude585",
			"Coordinated Attack",
			"Erik.Cassel",
			"Febrezer",
			"Paraselene Sage",
			"Luckymaxer",
			"Crystal Snare",
			"AsrielMemer",
			"RukatuKDH",
			"Gravity Collapse",
			"BuildIntoGames",
			"BlueShadic90",
			"Her0z",
			"xXVitalityVoidXx",
			"Dodgeball Player Blue",
			"Regular_Show",
			"Vitality Potion",
			"bengbeng14",
			"Korblox Shaman",
			"SuperCloud9",
			"Isaac0333-V2",
			"Brick Bacon",
			"Meme Thief",
			"The Famous Destruction5033",
			"Amber",
			"Materking",
			"tbradm",
			"4.0 Robloxian",
			"lando64000",
			"Owen0202",
			"VetexGames",
			"DrTrayBlox",
			"destruction5033",
			"Olafisawesome100",
			"puffytenter12",
			"ClanDrone",
			"Tinfoilbot",
			"bincent",
			"DairingPoopHead",
			"StayBlue",
			"Teaism",
			"Skullsten",
			"wer8888",
			"Voidsealer",
			"BlackSymphony",
			"HatdaCat",
			"BlizzardCreeper",
			"Consume Dream",
			"Traumaturge",
			"Bee",
			"Beehive",
			"Swarm",
			"Beekeeper",
			"Queen Bee",
			"True Hivemind",
			"Delusionist",
			"Grand Glaciem Mage",
			"LeetWizard",
			"Bebee2",
			"ItssPaladin",
			"Frosty The Snowman",
			"Megalodon the Dragon-Shark",
			"Titan of the Deep Below",
			"Depths of the Nether",
			"Divine Favor",
			"Alexnewtron",
			"Theawesomist19",
			"Skeleton Armada",
			"Arceusdon",
			"Acolyte of the Rift",
			"Witch",
			"Police Combatant",
			"Police Officer",
			"Serhat12",
			"Liz",
			"Hideaki",
			"Frozen Phoenix",
			"DominatedLegacy",
			"Bloo",
			"Gato Luz",
			"NobleDragon",
			"JackInTheBlox",
			"zPikmon",
			"Metal Bloxxer",
			"Cyclist",
			"GamesBloxx",
			"ShyLightness",
			"Psychotic",
			"Hamstermon",
			"Lord Tethamet",
			"Disaster Survival",
			"Korblox Squire",
			"Korblox Archmage",
			"Korblox Deathknight",
			"Korblox Deathkeeper",
			"Korblox General",
			"Korblox Defender",
			"Korblox Archer",
			"JadeFlames",
			"Right Arm of the Fried One",
			"Soul Release",
			"Spiderboy",
			"KrocoStar",
			"Halo4master233",
			"FancyFame",
			"WildSpeedy",
			"Tiny Tank",
			"Sylrath",
			"SwatPhantom",
			"Spark",
			"SimpleBeings",
			"MICHIKUSCHI",
			"Luigifan103",
			"JackinatorMG",
			"DeathETM",
			"Thunder Bolt",
			"Master Josue",
			"Lebron",
			"Lohit",
			"Samurai Shock",
			"Daisy",
			"Ice",
			"Developer",
			"Newbie",
			"RiceStorage",
			"Salesman",
			"Bloated",
			"DDude",
			"Regimen",
			"Froot Ninja",
			"Subata",
			"Glaciem Mage",
			"EzCheez",
			"Snowskateer",
			"Brunito",
			"Mackerel",
			"2Hex",
			"CinematicMind",
			"DeadZoneHark",
			"SharpTH",
			"Gaomon94",
			"Darpeh",
			"Pizzablawk",
			"Mike",
			"KnightDude",
			"DIY Azurewrath",
			"Y05H1M4N",
			"Blue Eyes Indigo Dragon",
			"Dued1",
			"IcyTea",
			"EpicLatiosLord",
			"EXLatios",
			"Eye Spy",
			"FuryBlocks",
			"Sharksie",
			"PlaceRebuilder",
			"litozinnamon",
		},
	}; 
	{
		Name = "Revel", --YELLOW!
		PriceInBloxBux = 30,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 721400239,
		Description = "Yellow is the colour of chaos, emotion, and society. Revel packs contain cards that cost yellow!",
		Cards = {
			"ScareAndCrow",
			"MesoSad",
			"Unc, Uncorrupted",
			"SmashDude88",
			"lilBismarck",
			"poke631",
			"ianmossaboss",
			"Toy Jet Fighter",
			"Cheesycakes",
			"Kago",
			"BrandonOccult",
			"SpeedySeat",
			"Royal Chair",
			"lolbeniceok",
			"ExtolYT",
			"midastheking123",
			"FourXIV",
			"Elioofsheep",
			"Bucket of Bees",
			"Blitzwolfer",
			"Bigtank_s",
			"Pikachukiller101",
			"Dairingpoophead, Tix God",
			"AII_Dragon",
			"emilvita",
			"DominiusConfabricor",
			"Defaultio",
			"Histor",
			"Jeeeeesus",
			"Dicey Dave",
			"Wild Reporter Tracy",
			"Happy Clown",
			"Den_S",
			"Egg Eyes Batter Dragon",
			"CloneTrooper1019",
			"Baby Noob",
			"Graalgamer",
			"Revelling Satyr",
			"ChickenduckbirdV2",
			"Noob's Play Box",
			"Safe Chat",
			"Noob Gunner",
			"Merely",
			"Golden Turkey",
			"Pilgrim",
			"Turkey Cannon",
			"Thanksgiving Feast",
			"Turkey",
			"Turkeytron",
			"Gobble Squad",
			"Frenemy's Bargain",
			"Happy Clown",
			"Den_S",
			"AII_Duck",
			"Helperbot",
			"PencilWizard",
			"YotamTiti",
			"Divine_Pengu",
			"JayTheCoder",
			"Monopoly Man",
			"Friend Request Spammer",
			"Luck Warrior of Pure Gold",
			"Zaquille",
			"The Piece Breaker",
			"Mr.O the Traveling Merchant",
			"Pancake Break",
			"BLOXER787",
			"Aurichalcum",
			"BrackioTops",
			"Cat's Eye Cultist",
			"Cat's Eye Nexus",
			"Lilmanofsalem",
			"animallogic",
			"Training Dummy",
			"Western Bandit",
			"Mzh3000",
			"NearMiss TFW",
			"Miked",
			"wi_sh",
			"Ultra Doregriffon",
			"Renaud800",
			"Uberubert",
			"Prestwick",
			"Lopous",
			"Dun_Goof",
			"John and Jane",
			"MustagedWorldYT",
			"Lorenzo77555",
			"Card Hoarder",
			"MinePix110",
			"SirSorin",
			"Flufflefunz",
			"ROBLOXian Reborn",
			"One BLOX Man",
			"Lilly_S",
			"MuPower",
			"popcornhebe",
			"CellBloxTango",
			"MajorMattias",
			"Radello",
			"CALL OF DOGE!?!",
			"Doge Hound",
			"Maplestick",
			"Evil Wood Grain",
			"Uncomfortably",
			"Mysterious UFO",
			"ROBLOX",
			"Widgeon",
			"TheGamer101",
			"Seranok",
			"BrightEyes",
			"SolarCrane",
			"OstrichSized",
			"Spooksletsky",
			"agodlypancake",
			"zachattack83",
			"Eldevin",
			"PEEPSTERS",
			"Kolby2020",
			"Chickenduckbird",
			"mickymack",
			"WarbearNomkins",
			"Grand Chicken Lord",
			"Matt Dusek",
			"Gusmanak",
			"Plushie Santa",
			"Plushie Elf",
			"Plushie Snowman",
			"Typheus the Whelp",
			"Plushie Lion",
			"Plushie Mummy",
			"Plushie Panda",
			"Plushie Polar Bear",
			"Plushie Tiger",
			"Plushie Hula Dog",
			"Plushie Leprechaun",
			"Plushie Dino",
			"Plushie Unicorn",
			"Titan of the Fried One",
			"Divine Favor",
			"Wrath of the Fried One",
			"Telamon",
			"Sophisticated Bat",
			"JackofMostTrades",
			"HomingBeacon",
			"Hopelesssly",
			"Hallows Treats",
			"Jack-O-Bat",
			"Builderman",
			"Toy Plane",
			"Toy Teeth",
			"Toy Car",
			"Toy Train",
			"Toy Boss Dino",
			"Toy Remote",
			"Call of the Teddy Bear",
			"Toy Truck",
			"Fried Acolyte",
			"Guest",
			"Haydebug2003",
			"Burning Phoenix",
			"TrollTideTroll",
			"Ultimate Bowl of Greed",
			"Unlimxted",
			"Combine Garrison",
			"Cluck Buck",
			"Youngtan",
			"Scrub",
			"Shamrock Doge",
			"Uncle Doge",
			"Captain Doge",
			"Abraham Doge",
			"JoeDev",
			"Left Arm of the Fried One",
			"Ejob",
			"RandomRobloxTV",
			"PowerCat123",
			"Visleaf",
			"TheNStar",
			"TheChakraTree",
			"Split Ego",
			"Reggie",
			"Pilot",
			"Majora7",
			"Maelstronomer",
			"ChildofGiotto",
			"Xlzeck",
			"Rhysmon",
			"Nexx",
			"MahBucket",
			"Finland",
			"Noob",
			"TeeVee",
			"Robic",
			"Lyv",
			"Tarfful",
			"Latchie",
			"QuisMo",
			"SoftCollision",
			"Uias",
			"Valletta",
			"GemInNight",
			"Mister Tea",
			"Dextromer",
			"Bowl of Greed",
			"Preston",
			"Toxic",
			"Loogi",
			"Qdhxx",
			"Volttt",
			"DIY Headphones",
			"Sand Eyes Yellow Dragon",
			"Drager",
			"Lord of Greed",
			"Lord of Auctions",
			"Doge",
			"GalaxyFlame",
			"Weaven",
			"StaceyD07",
		},
	}; 
	{
		Name = "Exotic", --NEW / WHITE! All cards before the break point rotate out once a new card comes in. Related cards rotate out at the same time.
		PriceInBloxBux = 50,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 1251993699,
		Description = "Exotic new cards from the black market! White cards and joke cards! It's all yours, as long as you have 10 wins!",
		WinRequirement = 10;
		Cards = {
			"StaceyD07",
			"MesoSad",
			"Korblox Squire",
			"Call to Arms",
			"Magical Girl Histor",
			"Unc, Uncorrupted",
			"SnailMan39",
			"Vinrole",
			"CopperGlow",
			"Frosted Shaman Marissa",
			"Darr1432",
			"WookieCookieHD",
			"SpacielChiald",
			"Melon Desu",
			"PurpleBoy329",
			"SmashDude88",
			"lilBismarck",
			"poke631",
			"ianmossaboss",
			"MyCutenesskills",
			"Toy Jet Fighter",
			"saud20",
			"Cheesycakes",
			"ZeDerpyDonal",
			"jojobinks321",
			"Sands of Purgatory",
			"Enriched Neutrinous",
			"rachjumper",
			"DunclubDuncan",
			"Damarioguy",
			"Creeperkiller510",
			"Tl_rd",
			"ThePestilentOne",
			"SpeedySeat",
			"DrWeaseI",
			"lolbeniceok",
			"stormmaster7722",
			"Permafrost Storm",
			"ThatGrimGuy",
			"B550",
			"MesouricPhantom976",
			"Yggdrasil Faerie",
			"ExtolYT",
			"Silver_Semtexagon",
			"vanjohnson",
			"midastheking123",
			"FourXIV",
			"Damaging26, Flaming Fighter",
			"ChaseThePsycho",
			"Dukran the Celestial",
			"Alar Trainee",
			"Alar Herald",
			"Alar Blade Chaser",
			"Alar Blade Archer",
			"Alar Sentinel",
			"Alar Myrmidon",
			"Elioofsheep",
			"Bucket of Bees",
			"Neutrinous",
			"Turtleuser3",
			"Arte71",
			"Jimmyin1",
			"how_inconvenient",
			"Blitzwolfer",
			"The Famous Destruction5033",
			"Superland6",
			"Lord of Auctions",
			"Fate_Sealed",
			"ImaUMBREON",
			"iSpaceDonut",
			"Bigtank_s",
			"ProjectSlayer",
			"caone",
			"Histor, Blood Warrior",
			"Enderlox1",
			"xiVirtual",
			"kickertoken",
			"superkicker2005",
			"Killar1234567",
			-- PAST THIS POINT IS FOR WHITE CARDS AND JOKE CARDS ONLY. I'M LOOKING AT YOU, BLITZ.
			"Despacito",
			"ScareAndCrow",
			"DoomedAdventurer",
			"Tootso",
			"WrathOfAzure",
			"saud20",
			"SpeedySeat",
			"Dukran the Celestial",
			"Wingman8",
			"Games",
			"Nexx",
			"Suicide Bomber",
			"CanadianSanic",
			"Ultra Bestower",
			"Ultra Enhancer",
			"Ultra Otherer",
			"Ultra Beseecher",
			"Ultra Desirer",
			"Ultra Severer",
			"Ultra Depriver",
			"Ultra Vanquisher",
			"Ultra Orator",
			"Ultra Obliterator",
			"Ultra Annihilator",
			"Satyr Firemaster",
			"Great Paraselene Sage",
			"Delirious Ooze",
			"Confusion Elemental?",
			"colesans16",
			"Exotic Murtic",
			"wowwow2211",
			"BrokenBone",
			"Retro Gangster",
			"Rainbowjewelninga785",
			"Body Guards",
			"Giftsplosion",
			"DrPepperSlayer",
			"Blue Fanatic",
			"Heatlands Vortex",
			"Noob Golem",
			"Green Icon Tree",
			"Kmansong2",
			"Nova",
			"SaxoAttack",
			"Unwanted Trend",
			"Clockwork",
			"Calamity Box",
			"Xor's Lab",
			"Assist Trophy",
			"Usering",
			"Imaginz00",
			"Scripter",
			"HatHelper",
			"GRAND DAD",
			"RachelDubs",
			"Clone Fave",
			"Dr.Fave",
			"Cow",
			"Cup O Tea",
			"Fat Cat",
			"Great Lord Egotist",
			"WishNite",
			"Grand Pirate King",
			"TheInnovative",
			"Robot",
			"Greygnarl",
			"Grimclaw the Unholy",
			"Titan's Stone",
			"Titan of the Holy Chamber",
			"Recruiter of the Titans",
			"Divine Favor",
			"Tweety The Twitter Bird",
			"Heavy Rain",
			"BlueTaslem",
			"Nenjas",
			"ASeal",
			"Sorcus",
			"MegaSmiley",
			"Bread Factory",
			"Dragon Horde",
			"Lunar Acolyte",
			"Lunar Warrior",
			"Mimic",
			"Berezaa",
			"Sands of Purgatory",
			"Titano's Cavern",
			"Sword Fights on the Heights",
			"Haunted Mansion",
			"Crossroads",
			"Stud",
			"Bloxy Tea Party",
			"Birthday Suprise",
			"SonozakiRaito",
			"Bobaman1",
			"Rukiryo",
			"Moded",
			"Godlysinha",
			"Crystal Cultist",
			"MisterObvious",
			"Bloxikin Horde",
			"Shedletsky the Fried One",
			"FixingFailure",
			"Haggie125",
			"The Gentlemaniac",
			"Razikai's Exploration",
		},
		
	};
	{
		Name = "Ancient Stirrings", --SPOOPY SCARY SKELETONS
		PriceInBloxBux = 60,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 721399106,
		Description = "Priestess Zanzel has corrupted this world. Do you have the gall to stop her? You must have 10 wins to open this pack.",
		WinRequirement = 10;
		--[[DateConstraint = {
			month = 10};
		};--]]
		Cards = {
			"Hallow's Boon",
			"Hallow's Eradicator",
			"Hallow's Knight",
			"Undead Teddy",
			"Treasured Unicorn",
			"Graboid",
			"LovecraftWizard",
			"Bedsheet Ghost",
			"DoeDoe",
			"Tooth Decay",
			"Carniverous Death Moth",
			"Dead Tree",
			"Possessed Skull",
			"Jason Voorhees",
			"Candy Robber",
			"DIY: Dark Dominus",
			"Abhorrant Skull",
			"Fearmiredon",
			"Victor Sinister",
			"Kalman Sinister",
			"Ghoost",
			"Korblox Skeleton",
			"Glaciem Knight",
			"Patric Sinister",
			"Slenderman",
			"Pyramid Head",
			"Haunted Redcliff Armor",
			"Headless Horseman",
			"Ignis Knight",
			"Gentle Elder",
			"Infected Mushrooms",
			"KillCactaur",
			"Haunted Overseer Armor",
			"Haunted Doge Head",
			"Hacker",
			"Apheliotropic Syzygy",
			"Waspism",
			"Smiling Golem",
			"Unresting Tombstone",
			"Mitcrawl",
			"Beast Within",
			"Sugar Skull",
			"Supercomputer's Skull",
			"Pumpkin Bomb",
			"RoboLoleris",
			"Unplumbed Lead",
			"Pumpkin Carver",
			"Stormchaser's Gambit",
			"Verisimilitudal Dissonance",
			"Swarm of Bats",
			"Nerf Zombie",
			"Psychotic Freak",
			"Spicy Lollipop",
			"The Skull Collector",
			"Priestess Zanzel, the Promised One",
			"Stranglevines",
			"Toxic Goo",
			"Noxious Gas",
			"Quan Sinister",
			"Terry Sinister",
			"Script Robber",
			"Disturbing Thoughts",
			"Mad Scientist",
			"Ye Old Arte",
			"Horse Breeder",
			"Trick or Treat",
			"Hidden Razor",
			"Hallow, the Sugarlord",
			"Horrarceusdon",
			"Horrarceusdon",
			"Gooplast",
			"Inexorable Goo Tide",
			"Haunted Korblox Armor",
			"Grim Reaper",
			"Grey Goo Scenario",
			"Eisenhower, the Alchemist",
			"Evil Prince",
			"Lumberjack",
			"Wolfbitten Noob",
			"Paraselene Ascetic",
			"Blessed Acolyte",
			"Homeless Man",
			"Wolven Blitz",
			"Unspeakable Summoning",
			"It that was Silenced",
			"Final Tree",
			"Groucho Mask",
			"Goo Golem",
			"Hallow's Enforcer",
			"Explosive Toad",
			"Death-Defying Demon",
			"Doll House",
			"Edgelord",
			"Frankenstein",
			"Final Revels",
			"Enrage",
			"Fried One Cultist",
			"Failed Expirement",
			"Dredger980",
			"Dun_Boof",
			"Cheshire Cat",
			"Bribery",
			"Cringeleaf",
			"Brothers Grotesque",
			"Claudia Sinister",
			"Cotton Candy Lion",
			"Creepy Toy",
			"Corrupt Guest",
			"DairingSpookHead",
			"Cereal Killer",
			"Dark Book of Spells",
			"Little Girl",
			"Liechtenauer's Sophistry",
		},
	};
	
	{
		Name = "Tribal", --ARCHETYPES!
		PriceInBloxBux = 50,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 622832971,
		Description = "Filled with only cards belonging to an archetype, this pack can help you finish your deck provided you have at least 10 wins.",
		WinRequirement = 10;
		Cards = {
			"MyCutenesskills",
			"ZeDerpyDonal",
			"AMerryCan",
			"Creeperkiller510",
			"Alar Myrmidon",
			"Alar Sentinel",
			"Alar Blade Archer",
			"Alar Blade Chaser",
			"Alar Herald",
			"Alar Trainee",
			"Dukran the Celestial",
			"Bucket of Bees",
			"Themediamogul99",
			"Abhorrant Skull",
			"Possessed Skull",
			"Frankenstein",
			"Psychotic Freak",
			"StayBlue",
			"Glaciem Knight",
			"JaikKaik",
			"Her0z",
			"Eisenhower, the Alchemist",
			"Edgelord",
			"Ignis Knight",
			"Fleskhjerta",
			"__________",
			"Captain Doge",
			"Shamrock Doge",
			"Abraham Doge",
			"Uncle Doge",
			"Doge",
			"PEEPSTERS",
			"TrollTideTroll",
			"Doge Hound",
			"Haunted Doge Head",
			"Kolby2020",
			"CALL OF DOGE!?!",
			"Nova",
			"Lunar Warrior",
			"Lunar Acolyte",
			"Dragon Horde",
			"Egg Eyes Batter Dragon",
			"Greygnarl",
			"Acolyte of the Rift",
			"Blue Eyes Indigo Dragon",
			"Megalodon the Dragon-Shark",
			"NobleDragon",
			"Infernal Acolyte",
			"Dragon's Charm",
			"Redrune Raider",
			"Fuchsia Eyes Red Dragon",
			"Skarra the DragonSlayer",
			"Nymn the Redrune Leader",
			"Necromantic Acolyte",
			"Teal Eyes Green Dragon",
			"Zerax the Untameable",
			"Fried Acolyte",
			"Sand Eyes Yellow Dragon",
			"Typheus the Whelp",
			"Dwarvern Sentry: MAX",
			"Dwarvern Sentry: Delta",
			"Dwarvern Sentry: Gamma",
			"Dwarvern Sentry: Beta",
			"Dwarvern Sentry: Alpha",
			"Dwarvern Captain",
			"Dwarvern Scientist",
			"Dwarvern Mathematician",
			"Dwarvern Engineer",
			"Dwarvern Energist",
			"Dwarvern Miner",
			"Korblox Squire",
			"Korblox Archer",
			"Korblox General",
			"Korblox Skeleton",
			"Korblox Shadowmage",
			"Korblox Defender",
			"Haunted Korblox Armor",
			"Korblox Shaman",
			"Serhat12",
			"Korblox Archmage",
			"Korblox Deathkeeper",
			"Korblox Deathknight",
			"Meeboid",
			"Meebling",
			"Meeboid Cultist",
			"Meebling Infestation",
			"Meeboid Champion",
			"Jeptem",
			"Grand Meeboid Totem",
			"Meeboid King",
			"Summon! Meeboid Titano!",
			"Toxic Goo",
			"Gooplast",
			"Ghoost",
			"Goo Golem",
			"Inexorable Goo Tide",
			"Grey Goo Scenario",
			"Verisimilitudal Dissonance",
			"Liechtenauer's Sophistry",
			"Apheliotropic Syzygy",
			"Great Lord Egotist",
			"Ye Old Arte",
			"Traumaturge",
			"Delusionist",
			"Consume Dream",
			"Gravity Collapse",
			"Disturbing Thoughts",
			"Forbidden Power",
			"Rat King",
			"Vermin's Caress",
			"Accursed Gate",
			"Uncreativename123",
			"Uncreation",
			"jojobinks321",
			"Grandmasters Ninja Dojo",
			"Froot Ninja",
			"Snowskateer",
			"Arashi Pikemen",
			"BlueShadic90",
			"KnitJa",
			"Ninja Kitty",
			"Ninja",
			"Teeny Ninja",
			"Ninja Assailant",
			"Ninja Elite",
			"Ninja Trainee",
			"Ninja Combatant",
			"Noob Attack! Ninja Stars!",
			"WhiteScarf",
			"BlazerC",
			"One_Thousand_Deaths",
			"Overseer Drake",
			"Eye of Overseer",
			"stereoplexus",
			"Overseer Prophet",
			"Overseer's Steed",
			"Haunted Overseer Armor",
			"Oddman's Gambit",
			"Overseer General",
			"Overseer Beast",
			"Bereghost",
			"Police Officer",
			"HatdaCat",
			"Luigifan103",
			"President Duck",
			"Isaac0333",
			"Isaac0333-V2",
			"Police Combatant",
			"Aesthetical",
			"Gravity Inspector",
			"Redcliff Messenger",
			"Redcliff Mauler",
			"Redcliff Archer",
			"Redcliff Heretic",
			"Redcliff: Rise!",
			"Redcliff: Decimate!",
			"Haunted Redcliff Armor",
			"Redcliff Enforcer",
			"Redcliff Rogue",
			"Redcliff Elite Commander",
			"Victor Sinister",
			"Kalman Sinister",
			"Patric Sinister",
			"Claudia Sinister",
			"Quan Sinister",
			"xXVitalityVoidXx",
			"Skullsten",
			"Skeleton Armada",
			"Supercomputer's Skull",
			"Sugar Skull",
			"The Skull Collector",
			"Titan's Stone",
			"Recruiter of the Titans",
			"Titan of the Holy Chamber",
			"Titan of the Deep Below",
			"Titan of the Infernal Abyss",
			"Titan of the Dying Forest",
			"Titan of the Fried One",
			"Toy Remote",
			"Toy Teeth",
			"Toy Plane",
			"Toy Truck",
			"Toy Car",
			"Toy Train",
			"Toy Jet Fighter",
			"Toy Boss Dino",
			"Call of the Teddy Bear",
			"Zombie",
			"Nerf Zombie",
			"Construction Zombie",
			"Unresting Tombstone",
			"Zombie Cultist",
			"Zombie Summoner",
			"Zom-nobi",
			"Zombie King",
			"Bee",
			"Swarm",
			"CalmFoxz",
			"Beehive",
			"Queen Bee",
			"Beekeeper",
			"Waspism",
			"True Hivemind",
			"Cat's Eye Wing Flock",
			"Cat's Eye Corpse Stealer",
			"Cat's Eye, Master of Perception",
			"Cat's Eye Cultist",
			"Cat's Eye Nexus",
			"Scripter",
			"Lebron",
			"wer8888",
			"Script Robber",
			"Mad Scientist",
			"destruction5033",
			"MICHIKUSCHI",
			"Erik.Cassel",
			"JaikKaik",
			"Stravant",
			"Tinfoilbot",
			"Tomspick",
			"LordVasco",
			"mrawesomecarter",
			"Paraselene Sage",
			"PassTheToiletPaper",
			"MUTO2014",
			"TheSteelEagle",
			"Tone",
			"Master Josue",
			"Has",
			"Forbidden Power",
			"Cherie",
			"HashtagWatermelon",
			"PixelFlame",
			"zKevin",
			"666",
			"NerfModder",
			"HeyItsColin",
			"UAE",
			"Majora7",
			"Lopous",
			"Scrub",
			"Lilly_S",
			"CloneTrooper1019",
			"DDude",
			"DominatedLegacy",
			"Fancy Arachnid",
			"NatzHakz",
			"KillCactaur",
			"HyperBlue",
			"InceptionTime",
			"Ghost Dragon",
			"madattak",
		},
	};
	
	{
		Name = "Innovative", --those meme alts or something i guess
		Hidden = false;
		PriceInBloxBux = 1337,
		PriceInRobux = 0;
		CardsInPack = 1,
		CardPackId = 1532232174,
		Description = "Appearing only on the 1st, 12th, and 23rd of a month, the Innovative pack contains incredibly rare bling. Requires 100 wins.",
		WinRequirement = 100;
		DateConstraint = {
			day = {1,12,23};
		};
		Cards = {
			"CreativeName123",
			"CandyStream",
			"It",
			"SoulSearchEngine",
			"Noobwolfer",
			"jarjarbinks321",
			"Leaf",
			"Arceus",
			"PoopHead",
			"Yoshi",
			"Pencil",
			"Histor, Memecraft Slayer",
			"IcyBee",
			"Bee Ninja",
			"Newbee",
			"Beestor",
			"Tom's Bees",
			"MrBeeBee2",
			"Beeskateer",
			"WarnomBearkins",
		},
	};
	{
		Name = "Teaism's Gifts", --CHRISTMAS!
		Hidden = false;
		PriceInBloxBux = 1000;
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 1248737582,
		Description = "Teaism's special gift, just for you. Merry Christmas. (You need 10 wins to open this pack.)",
		WinRequirement = 10;
		DateConstraint = {
			month = {12};
		};
		Cards = {
			"Unwanted Gift",
			"Baba Yaga",
			"Zombie Santa",
			"Zombie Elf",
			"JackinatorMG-C",
			"StickMasterLukeV2",
			"Tomspick-C",
			"Tombstone-C",
			"Icy Drake",
			"Baker",
			"Hot Chocolate",
			"GRAND CLAUS",
			"Gingerbread Man",
			"Sugarlord",
			"CrazyEggNoggin",
			"Eggnog",
			"MyDadIsASanta",
			"Wooden Toy Train",
			"RoboSanta",
			"Eleemosynary Beneficient",
			"Elfdevin",
			"Entangling Lights",
			"Wolfbitten Elf",
			"SantaSorin",
			"Santa Doge",
			"Fruit Cake",
		},
	};
	
	{
		Name = "Tough Love", --VALENTINES & WHITE DAY!
		Hidden = false;
		PriceInBloxBux = 1000;
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 654911255,
		Description = "Over 40 special edition Valentine themed cards! Can your heart resist them? <3 (Minimum 10 wins. Stalker and Combine Garrison are only found in the Art Box.)",
		WinRequirement = 10;
		DateConstraint = {
			month = {2, 3};
			day = {14, 15, 16, 17, 18, 19, 20};
		};
		Cards = {
			"Ejob-Val",
			"The Hugger",
			"PencilWizard-Val",
			"Chef-Val",
			"PixelPistol-Val",
			"TeeVee-Val",
			"Newbie-Val",
			"RiceStorage-Val",
			"Bowl of Greed-Val",
			"Lord of Greed-Val",
			"DeadZoneHark-Val",
			"Sorry-Val",
			"Pilot-Val",
			"Hamstermon-Val",
			"Pirate-Val",
			"Gato Luz-Val",
			"Burning Phoenix-Val",
			"Hallows Treats-Val",
			"Dr.Fave-Val",
			"SuperCloud9-Val",
			"Vitality Potion-Val",
			"Pancake Break-Val",
			"Uncreativename123-Val",
			"IlIll-Val",
			"MiloCortez-Val",
			"Sylrath-Val",
			"KingCactaur-Val",
			"Korblox Deathknight-Val",
			"BlackSymphony-Val",
			"Forbidden Power-Val",
			"Cupid's Eye Wing Flock",
			"Cupid's Eye Cultist",
			"Cupid's Eye Heart Stealer",
			"Cupid's Eye Nexus",
			"Cupid's Eye, Master of Romance",
			"Evil Prince-Val",
			"SoulSearch-Val",
		},
	};
	
	{
		Name = "Summer Salt", --SUMMER!
		PriceInBloxBux = 1000;
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 899630666,
		Description = "From the vast ocean to vibrant rainforests, this pack contains a wide variety of stunning Summer themed alt arts. Come and enjoy the outdoors with us! (requires 10 wins)",
		WinRequirement = 10;
		DateConstraint = {
			month = {7, 8};
		};
		Cards = {
			"Ambamby-Sun",
			"AntiSammeh-Sun",
			"AVote-Sun",
			"Heavy Rain-Sun",
			"DominiusConfabricor-Sun",
			"Eisenhower-Sun",
			"Guest-Sun",
			"Fenrier-Sun",
			"Froot Ninja-Sun",
			"GemInNight-Sun",
			"Grand Meeboid Totem-Sun",
			"Grand Pirate King-Sun",
			"Hallow, the Sugarlord-Sun",
			"Haunted Mansion-Sun",
			"HuntarioRBLX-Sun",
			"Jeptem-Sun",
			"Jimminus-Sun",
			"Lady RedNight-Sun",
			"Latchie-Sun",
			"LeetWizard-Sun",
			"Luck o The Lobsters-Sun",
			"MarissaKitty04-Sun",
			"Meebling-Sun",
			"Meebling Infestation-Sun",
			"Meeboid King-Sun",
			"Meeboid-Sun",
			"Meeboid Champion-Sun",
			"Meeboid Surfer-Sun",
			"Mitpaul-Sun",
			"Oozlebachr-Sun",
			"Pixellus-Sun",
			"RachelDubs-Sun",
			"Satyr Firemaster-Sun",
			"Snowskateer-Sun",
			"Spooky Caverns-Sun",
			"Titano-Sun",
			"Valletta-Sun",
			"Weaven-Sun",
			"Widgeon-Sun",
		},
	};
	
	{
		Name = "Easter Feast",
		Hidden = false;
		PriceInBloxBux = 1000;
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 1574596642,
		Description = "Go on a hunt to find these special Easter themed alts. Will you be able to collect them all? (requires 10 wins)",
		WinRequirement = 10;
		DateConstraint = {
			month = {4};
			day = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25};
		};
		Cards = {
			"Jeeeeesus-E",
			"Eye of Heaven-E",
			"Mlgloga-E",
			"Script Robber-E",
			"Dayren-E",
			"Lyv-E",
			"Langz-E",
			"SharpTH-E",
			"Chef-E",
			"Dued1-E",
			"Zolerus-E",
			"TheChakraTree-E",
			"Visleaf-E",
			"Blockerwiz-E",
			"Titan's Stone-E",
			"Recruiter-E",
			"Titan of the Infernal Abyss-E",
			"Titan of the Deep Below-E",
			"Titan of the Dying Forest-E",
			"Titan of the Fried One-E",
			"Titan of the Holy Chamber-E",
			"Plushie Mummy-E",
			"JJ5x5-E",
			"ReverseBackwards-E",
			"Wer8888-E",
			"Card Hoarder-E",
			"Western Bandit-E",
			"Mafia Grunt-E",
		},
	};
	
}

return packs
