--main 1
local packs = {
	{
		Name = "Exine", --STAPLES!
		PriceInBloxBux = 25,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 596205187,
		Description = "Curated by the best players of the game, Exine contains only good cards.",
		Cards = {
			"CalmFoxz",
			"Lyv",
			"Samksoon321",
			"Brycen27",
			"AsrielMemer",
			"Razuatix",
			"Korblox Shaman",
			"Spiderboy",
			"2Hex",
			"Card Hoarder",
			"Pizzablawk",
			"FatalWing",
			"VetexGames",
			"tbradm",
			"Olafisawesome100",
			"DairingPoopHead",
			"ROBLOX",
			"TheGamer101",
			"StayBlue",
			"Taymaster",
			"Rinicye",
			"Chef",
			"PEEPSTERS",
			"mickymack",
			"WarbearNomkins",
			"HatdaCat",
			"Grand Pirate King",
			"Typheus the Whelp",
			"Nymn the Redrune Leader",
			"Megalodon the Dragon-Shark",
			"Plushie Mummy",
			"Divine Favor",
			"Ozzypig",
			"Weaven",
			"Murtic",
			"Arceusdon",
			"Chiefjustus",
			"Cindering",
			"Toy Truck",
			"Necromantic Acolyte",
			"Acolyte of the Rift",
			"Infernal Acolyte",
			"Lunar Acolyte",
			"Fried Acolyte",
			"Lady RedNight",
			"KingShadowCrow",
			"Burning Phoenix",
			"Spikle",
			"Gato Luz",
			"Jayson13",
			"Berezaa",
			"Titano's Cavern",
			"PolyHex",
			"Ripull",
			"JackInTheBlox",
			"zPikmon",
			"Pirate",
			"Odin",
			"KasoduS",
			"Cluck Buck",
			"Blockerwiz",
			"ShyLightness",
			"Redcliff Messenger",
			"Psychotic",
			"Tomfl",
			"Lord Tethamet",
			"Leitris",
			"Crossroads",
			"Shamrock Doge",
			"Korblox Deathknight",
			"Korblox Archer",
			"Byte",
			"DrKig",
			"Ejob",
			"Zombie Summoner",
			"Zombie Cultist",
			"Stud",
			"Mitpaul",
			"KrocoStar",
			"DerpDerpyness",
			"Bloxy Tea Party",
			"Visleaf",
			"TheChakraTree",
			"Sylrath",
			"SimpleBeings",
			"Player",
			"Oz",
			"Oozlebachr",
			"Guest",
			"Mag",
			"Maelstronomer",
			"JackinatorMG",
			"ZacAttackk",
			"Assist Trophy",
			"Rukiryo",
			"XiaoXiaoMan",
			"Thunder Bolt",
			"Rhysmon",
			"Nexx",
			"Lohit",
			"Ambamby",
			"Cowboy",
			"Rad",
			"Anderson",
			"FatherChristmaz",
			"DerptasticDevil",
			"Langz",
			"Bob",
			"Cillow",
			"Glaecium",
			"Life Potion",
			"Zolerus",
			"Ice",
			"RiceStorage",
			"Regimen",
			"Finland",
			"TeeVee",
			"Robic",
			"Tarfful",
			"Latchie",
			"SoftCollision",
			"Uias",
			"Valletta",
			"GemInNight",
			"Bowl of Greed",
			"Froot Ninja",
			"Glaciem Mage",
			"DeadZoneHark",
			"Dayren",
			"Damaging26",
			"PixelPistol",
			"Ninja Elite",
			"AntiSammeh",
			"Meebling Infestation",
			"MekaX",
			"Duckywow",
			"Inventor1116",
			"Preston",
			"Toxic",
			"Loogi",
			"Qdhxx",
			"Pikachukiller101",
			"Noob Attack! Ninja Stars!",
			"Wustard",
			"SharpTH",
			"Mike",
			"Fuchsia Eyes Red Dragon",
			"Luck o The Lobsters",
			"Dignity",
			"Blue Eyes Indigo Dragon",
			"Sand Eyes Yellow Dragon",
			"Dued1",
			"Widgeon",
			"MisterObvious",
			"Teal Eyes Green Dragon",
			"Mass Epidemic",
			"Exine",
			"IcyTea",
			"Drager",
			"Eye Spy",
			"FuryBlocks",
		},
	}; 
	{
		Name = "Dominion", --RED!
		PriceInBloxBux = 30,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 842435184, --721400845,
		Description = "Red is the colour of power, ambition, and control. Dominion packs contain cards that cost red!",
		Cards = {
			"ProjectSlayer",
			"Histor, Blood Warrior",
			"superkicker2005",
			"Shard Master",
			"Beyondthegong",
			"Damaging26",
			"MarissaKitty04",
			"ChaoticCommando",
			"how_inconvenient",
			"TheJazzCat22",
			"Cindering",
			"SoulSearch",
			"Eye of Heaven",
			"UHunterU",
			"Roblox Gift Card",
			"MagikalYawn",
			"SubZeroExtaByte0",
			"Javier Killer",
			"Peika Sammai",
			"Treas0ner",
			"74Riley",
			"Thesupernessiiiii",
			"Has",
			"LeTruth",
			"AVote",
			"Epic Sauce",
			"NullSenseStudio",
			"Forestfire Butterflies",
			"Burning Tree",
			"Dodgeball Gambler Red",
			"Kinnis97",
			"Tone",
			"Ninja Kitty",
			"KnitJa",
			"Fire Fighter",
			"Drager Bot",
			"Epic Sauce",
			"NullSenseStudio",
			"Forestfire Butterflies",
			"Burning Tree",
			"Dodgeball Gambler Red",
			"Kinnis97",
			"Supersky712",
			"BoomAtack",
			"Mafia Grunt",
			"Tricky Magician",
			"iiMasant",
			"Dwarvern Sentry: MAX",
			"Dwarvern Sentry: Delta",
			"Dwarvern Sentry: Gamma",
			"Dwarvern Sentry: Beta",
			"Dwarvern Sentry: Alpha",
			"Dwarvern Captain",
			"Dwarvern Scientist",
			"Dwarvern Mathematician",
			"Dwarvern Engineer",
			"Dwarvern Energist",
			"Dwarvern Miner",
			"Winchester Rotomo",
			"mrawesomecarter",
			"JavierCollin88Poppin",
			"Mohawk2275",
			"Prisman",
			"FabulousMettaton123",
			"666",
			"WoodReviewer",
			"One4utwo4me",
			[[One_Thousand_Deaths]],
			"Burning_Soul_Blade",
			"Cooldude4851",
			"Cotton Cavalier",
			"Arashi Pikemen",
			"HeyItsColin",
			"BerskererPredator450",
			"DrPepperSlayer",
			"MUTO2014",
			"Meeboid Champion",
			"NerfModder",
			"Beam Sword",
			"ClanAtlas",
			"KurosakiDXenos",
			"Doneyes",
			"Skarra the DragonSlayer",
			"Forbidden Power",
			"Sibs",
			"SomaticMizuSan",
			"Moon Rabbit's Rage",
			"UAE",
			"Kit of Deception",
			"Robloxian255",
			"UristMcSparks",
			"zKevin",
			"Explode1",
			"Ultoris Tenebrae",
			"Ultoris NOOBrae",
			"TheSteelEagle",
			"ROBLOXADOR!!",
			"XxFreezerFlamesxX",
			"LordVasco",
			"Isaac0333",
			"Alkalola",
			"Nikilis",
			"Rockybow",
			"Crazynoggin",
			"Hoshpup",
			"Aife",
			"Duel Axe Monster",
			"ScriptMasTime",
			"Redcliff Rogue",
			"Anti-Fave",
			"Super Bacon",
			"legoseed",
			"Taymaster",
			"TheAmazeMan",
			"Rinicye",
			"AllStarBren",
			"Paranormanbiggestfan",
			"Deathaman211",
			"Grand Ignis Mage",
			"MrDoombringer",
			"Fleskhjerta",
			"Dragon's Charm",
			"Nymn the Redrune Leader",
			"Titan of the Infernal Abyss",
			"Inferno!",
			"Redcliff: Decimate!",
			"Redcliff: Rise!",
			"Divine Favor",
			"Dodgeball Player Red",
			"Ozzypig",
			"Papasmurf",
			"Redrune Raider",
			"The Vlad",
			"Chiefjustus",
			"Infernal Acolyte",
			"SirAdurite",
			"Totem of Pixel",
			"PassTheToiletPaper",
			"Luck o The Lobsters",
			"Lady RedNight",
			"FishBubble1002",
			"Fallen Guardian",
			"BuzzHamtaro",
			"Primal Gato",
			"Jayson13",
			"The Stalker",
			"Zedreadr",
			"Drakobloxxer",
			"WafflzDude",
			"Odin",
			"KennedyLeDog",
			"Connoisseur",
			"ChosenCoast",
			"Blockerwiz",
			"Redcliff Enforcer",
			"Redcliff Mauler",
			"Redcliff Elite Commander",
			"Redcliff Messenger",
			"SkySpell",
			"Tomfl",
			"Grandmasters Ninja Dojo",
			"Redcliff Archer",
			"DrKig",
			"Right Leg of the Fried One",
			"Mitpaul",
			"WhiteScarf",
			"RoboticMob",
			"Player",
			"Plankton124",
			"Pixellus",
			"Oz",
			"Mag",
			"HyperVoxel",
			"DataRaven",
			"BUTQUNA",
			"ZacAttackk",
			"Sorry",
			"HashtagWatermelon",
			"Ambamby",
			"Cowboy",
			"Ignis Mage",
			"Kamov",
			"Ninja",
			"Rad",
			"Anderson",
			"Cherie",
			"FatherChristmaz",
			"Tomspick",
			"DerptasticDevil",
			"PixelFlame",
			"FuuTuu",
			"BloodSpilled",
			"Hodif",
			"Ninja Elite",
			"Ninja Trainee",
			"Ninja Assailant",
			"Ninja Combatant",
			"Teeny Ninja",
			"AntiSammeh",
			"Sammeh",
			"Noob Attack! Ninja Stars!",
			"SirDapper",
			"DIY Biggerhead",
			"BlazerC",
			"Fuchsia Eyes Red Dragon",
			"Dignity",
			"Fave",
			"Exine",
			"Bloxy Victory",
		},
	}; 
	{
		Name = "Vitality", --GREEN!
		PriceInBloxBux = 30,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 721399805,
		Description = "Green is the colour of life, growth, and the primal forces. Vitality packs contain cards that cost green!",
		Cards = {
			"Superland6",
			"iSpaceDonut",
			"Enderlox1",
			"Lord_Gizmo",
			"iiSmolToaster",
			"Saprasam",
			"BonesMcCormick",
			"Kariu",
			"madattak",
			"CrazyCaleb77",
			"Uncreation",
			"WebGL3D",
			"CorgiParade",
			"brickmason",
			"Classy Bear",
			"Cat Ears Maid",
			"HyperBlue",
			"rhomlevko",
			"__________",
			"Smart Planner",
			"Zombie",
			"Brick_Man",
			"Uncreativename123",
			"pa00",
			"Overseer Drake",
			"Tankbomer",
			"InceptionTime",
			"Aceguy100",
			"Mariochocolatemilk",
			"HasTheHero",
			"Korblox Shadowmage",
			"Redcliff Heretic",
			"stereoplexus",
			"Cat's Eye Wing Flock",
			"Cat's Eye Corpse Stealer",
			"Cat's Eye, Master of Perception",
			"iAsuka",
			"TigerCode",
			"APlayerOfGames",
			"Samksoon321",
			"ST Leader Keeler1",
			"Brymmy",
			"Brycen27",
			"Bad Bread",
			"Razuatix",
			"Mrbeanbean2",
			"Bearded Captain",
			"Keeler1",
			"FatalWing",
			"EfanPlayz",
			"inechi",
			"BroRubik",
			"1337",
			"Picopicoman",
			"Beeism",
			"Alapz",
			"Blockhaak",
			"MLGSPONGE",
			"GreenHearted",
			"ReverseBackwards",
			"Gangmanstyle556",
			"Vermin's Caress",
			"Accursed Gate",
			"Rat King",
			"Grand Meeboid Totem",
			"Myrmiredon",
			"JJ5x5",
			"Monkey",
			"Zerax the Untameable",
			"Overseer's Steed",
			"Oddman's Gambit",
			"Titan of the Dying Forest",
			"Mass Epidemic",
			"Divine Favor",
			"Mummy Peasant",
			"Zom-nobi",
			"XxWonderzxX",
			"Witch's True Brew",
			"Murtic",
			"Fancy Arachnid",
			"Construction Zombie",
			"Traumatic Clown",
			"Jeptem",
			"Necromantic Acolyte",
			"Eye of Overseer",
			"Overseer Beast",
			"Overseer General",
			"Overseer Prophet",
			"LuckyTux",
			"Medic Kit",
			"KingShadowCrow",
			"Bereghost",
			"PolyHex",
			"Spikle",
			"1x1x1x1",
			"Biostream",
			"Ripull",
			"Pirate",
			"KasoduS",
			"WaddleTom",
			"Leitris",
			"Boogerguy123",
			"Byte",
			"Left Leg of the Fried One",
			"Zombie King",
			"Zombie Summoner",
			"Zombie Cultist",
			"KingCactaur",
			"DerpDerpyness",
			"Pillager",
			"Oozlebachr",
			"MrMaxi23",
			"Nicolas1015",
			"MiloCortez",
			"StickMasterLuke",
			"XiaoXiaoMan",
			"Quenty",
			"MyDadIsAGuest",
			"IlIll",
			"Meeboid",
			"Langz",
			"Krazy Koala",
			"Bob",
			"Chef",
			"Cillow",
			"Otub",
			"Robber",
			"BO0M",
			"Burglar",
			"Glaecium",
			"Life Potion",
			"Zolerus",
			"Meeboid Cultist",
			"Meebling",
			"NatzHakz",
			"Faultful",
			"Saiier",
			"MekaX",
			"Duckywow",
			"Inventor1116",
			"Luchador",
			"TZSara",
			"BadBreadMaker",
			"Calirolls",
			"Camo Joe",
			"Chaoszeroomega",
			"Meeboid King",
			"Summon! Meeboid Titano!",
			"Hoote",
			"NICCO",
			"Wustard",
			"Tom's Beans",
			"PhireFox",
			"Awful Good",
			"Deadeye",
			"DIY Dominus",
			"Teal Eyes Green Dragon",
			"Icepielover23",
			"Fate_Sealed",
		},
	}; 
	{
		Name = "Thought", --BLUE!
		PriceInBloxBux = 30,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 721399466,
		Description = "Blue is the colour of logic, order, and structure. Thought packs contain cards that cost blue!",
		Cards = {
			"kickertoken",
			"ImaUMBREON",
			"caone",
			"xiVirtual",
			"Killar1234567",
			"EvilJacobthehero2013",
			"Regular_Talkshow",
			"wikiwakiwoirier",
			"Your_Name",
			"Friaza",
			"Deadly Dicey Duo",
			"hyp3rdeath",
			"Steam Razikai",
			"Wooden Chair",
 			"Rollernaut",
			"SONICTHEHEDGEHOGXXX",
			"Razikai's Exploration",
			"Ghost Dragon",
			"madkey900",
			"RaveTea",
			"Xenotrent",
			"Deep Sea Diver",
			"Dicey Drake",
			"Stravant",
			"Ship Raider",
			"DJ Kangaroo",
			"Aesthetical",
			"CalmFoxz",
			"The Gentlemaniac",
			"ReeseMcBlox",
			"Yoshius",
			"Nopants99",
			"CIA Man",
			"FabulousBench",
			"Stevenl15",
			"B0BBA",
			"Razikai",
			"Fenrier",
			"JaikKaik",
			"Gravity Inspector",
			"LordFlanz",
			"TheEnderCorp",
			"ShockingRobux",
			"HuntarioRBLX",
			"Cyandude585",
			"Coordinated Attack",
			"Erik.Cassel",
			"Febrezer",
			"Paraselene Sage",
			"Luckymaxer",
			"Crystal Snare",
			"AsrielMemer",
			"RukatuKDH",
			"Gravity Collapse",
			"BuildIntoGames",
			"BlueShadic90",
			"Her0z",
			"xXVitalityVoidXx",
			"Dodgeball Player Blue",
			"Regular_Show",
			"Vitality Potion",
			"bengbeng14",
			"Korblox Shaman",
			"SuperCloud9",
			"Isaac0333-V2",
			"Brick Bacon",
			"Meme Thief",
			"Amber",
			"Materking",
			"tbradm",
			"4.0 Robloxian",
			"lando64000",
			"Owen0202",
			"VetexGames",
			"DrTrayBlox",
			"destruction5033",
			"Olafisawesome100",
			"puffytenter12",
			"ClanDrone",
			"Tinfoilbot",
			"bincent",
			"DairingPoopHead",
			"StayBlue",
			"Teaism",
			"Skullsten",
			"wer8888",
			"Voidsealer",
			"BlackSymphony",
			"HatdaCat",
			"BlizzardCreeper",
			"Consume Dream",
			"Traumaturge",
			"Bee",
			"Beehive",
			"Swarm",
			"Beekeeper",
			"Queen Bee",
			"True Hivemind",
			"Delusionist",
			"Grand Glaciem Mage",
			"LeetWizard",
			"Bebee2",
			"ItssPaladin",
			"Frosty The Snowman",
			"Megalodon the Dragon-Shark",
			"Titan of the Deep Below",
			"Depths of the Nether",
			"Divine Favor",
			"Alexnewtron",
			"Theawesomist19",
			"Skeleton Armada",
			"Arceusdon",
			"Acolyte of the Rift",
			"Witch",
			"Police Combatant",
			"Police Officer",
			"Serhat12",
			"Liz",
			"Hideaki",
			"Frozen Phoenix",
			"DominatedLegacy",
			"Bloo",
			"Gato Luz",
			"NobleDragon",
			"JackInTheBlox",
			"zPikmon",
			"Metal Bloxxer",
			"Cyclist",
			"GamesBloxx",
			"ShyLightness",
			"Psychotic",
			"Hamstermon",
			"Lord Tethamet",
			"Disaster Survival",
			"Korblox Archmage",
			"Korblox Deathknight",
			"Korblox Deathkeeper",
			"Korblox General",
			"Korblox Defender",
			"Korblox Archer",
			"JadeFlames",
			"Right Arm of the Fried One",
			"Soul Release",
			"Spiderboy",
			"KrocoStar",
			"Halo4master233",
			"FancyFame",
			"WildSpeedy",
			"Tiny Tank",
			"Sylrath",
			"SwatPhantom",
			"Spark",
			"SimpleBeings",
			"MICHIKUSCHI",
			"Luigifan103",
			"JackinatorMG",
			"DeathETM",
			"Thunder Bolt",
			"Master Josue",
			"Lebron",
			"Lohit",
			"Samurai Shock",
			"Daisy",
			"Ice",
			"Developer",
			"Newbie",
			"RiceStorage",
			"Salesman",
			"Bloated",
			"DDude",
			"Kago",
			"Regimen",
			"Froot Ninja",
			"Subata",
			"Glaciem Mage",
			"EzCheez",
			"Snowskateer",
			"Brunito",
			"Mackerel",
			"2Hex",
			"CinematicMind",
			"DeadZoneHark",
			"SharpTH",
			"Gaomon94",
			"Darpeh",
			"Mike",
			"KnightDude",
			"DIY Azurewrath",
			"Y05H1M4N",
			"Blue Eyes Indigo Dragon",
			"Dued1",
			"IcyTea",
			"EpicLatiosLord",
			"EXLatios",
			"Eye Spy",
			"FuryBlocks",
		},
	}; 
	{
		Name = "Revel", --YELLOW!
		PriceInBloxBux = 30,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 721400239,
		Description = "Yellow is the colour of chaos, emotion, and society. Revel packs contain cards that cost yellow!",
		Cards = {
			"Blitzwolfer",
			"Bigtank_s",
			"Dairingpoophead, Tix God",
			"AII_Dragon",
			"emilvita",
			"DominiusConfabricor",
			"Defaultio",
			"Histor",
			"Jeeeeesus",
			"Dicey Dave",
			"Wild Reporter Tracy",
			"Happy Clown",
			"Den_S",
			"Egg Eyes Batter Dragon",
			"CloneTrooper1019",
			"Safe Chat",
			"Noob Gunner",
			"Merely",
			"Golden Turkey",
			"Pilgrim",
			"Turkey Cannon",
			"Thanksgiving Feast",
			"Turkey",
			"Turkeytron",
			"Gobble Squad",
			"Frenemy's Bargain",
			"Happy Clown",
			"Den_S",
			"AII_Duck",
			"Helperbot",
			"PencilWizard",
			"YotamTiti",
			"Divine_Pengu",
			"JayTheCoder",
			"Monopoly Man",
			"Friend Request Spammer",
			"Luck Warrior of Pure Gold",
			"Zaquille",
			"The Piece Breaker",
			"Mr.O the Traveling Merchant",
			"Pancake Break",
			"BLOXER787",
			"Aurichalcum",
			"BrackioTops",
			"Cat's Eye Cultist",
			"Cat's Eye Nexus",
			"Lilmanofsalem",
			"animallogic",
			"Training Dummy",
			"Western Bandit",
			"Mzh3000",
			"NearMiss TFW",
			"Miked",
			"wi_sh",
			"Ultra Doregriffon",
			"Renaud800",
			"Uberubert",
			"Prestwick",
			"Lopous",
			"Dun_Goof",
			"John and Jane",
			"MustagedWorldYT",
			"President Duck",
			"Lorenzo77555",
			"Card Hoarder",
			"MinePix110",
			"SirSorin",
			"Flufflefunz",
			"One BLOX Man",
			"Lilly_S",
			"MuPower",
			"popcornhebe",
			"CellBloxTango",
			"MajorMattias",
			"Radello",
			"CALL OF DOGE!?!",
			"Doge Hound",
			"Maplestick",
			"Evil Wood Grain",
			"Uncomfortably",
			"Mysterious UFO",
			"ROBLOX",
			"Widgeon",
			"TheGamer101",
			"Seranok",
			"BrightEyes",
			"SolarCrane",
			"OstrichSized",
			"Spooksletsky",
			"agodlypancake",
			"zachattack83",
			"Eldevin",
			"PEEPSTERS",
			"Kolby2020",
			"Chickenduckbird",
			"mickymack",
			"WarbearNomkins",
			"Grand Chicken Lord",
			"Matt Dusek",
			"Gusmanak",
			"Plushie Santa",
			"Plushie Elf",
			"Plushie Snowman",
			"Typheus the Whelp",
			"Plushie Lion",
			"Plushie Mummy",
			"Plushie Panda",
			"Plushie Polar Bear",
			"Plushie Tiger",
			"Plushie Hula Dog",
			"Plushie Leprechaun",
			"Plushie Dino",
			"Plushie Unicorn",
			"Titan of the Fried One",
			"Divine Favor",
			"Wrath of the Fried One",
			"Telamon",
			"Sophisticated Bat",
			"JackofMostTrades",
			"HomingBeacon",
			"Hopelesssly",
			"Hallows Treats",
			"Jack-O-Bat",
			"Builderman",
			"Toy Plane",
			"Toy Teeth",
			"Toy Car",
			"Toy Train",
			"Toy Boss Dino",
			"Toy Remote",
			"Call of the Teddy Bear",
			"Toy Truck",
			"Fried Acolyte",
			"Guest",
			"Haydebug2003",
			"Burning Phoenix",
			"TrollTideTroll",
			"Ultimate Bowl of Greed",
			"Unlimxted",
			"Combine Garrison",
			"Cluck Buck",
			"Youngtan",
			"Scrub",
			"Shamrock Doge",
			"Uncle Doge",
			"Captain Doge",
			"Abraham Doge",
			"JoeDev",
			"Left Arm of the Fried One",
			"Ejob",
			"RandomRobloxTV",
			"PowerCat123",
			"Visleaf",
			"TheNStar",
			"TheChakraTree",
			"Split Ego",
			"Reggie",
			"Pilot",
			"Majora7",
			"Maelstronomer",
			"ChildofGiotto",
			"Xlzeck",
			"Rhysmon",
			"Nexx",
			"MahBucket",
			"Finland",
			"Noob",
			"TeeVee",
			"Robic",
			"Lyv",
			"Tarfful",
			"Latchie",
			"QuisMo",
			"SoftCollision",
			"Uias",
			"Valletta",
			"GemInNight",
			"Mister Tea",
			"Dextromer",
			"Bowl of Greed",
			"Preston",
			"Toxic",
			"Loogi",
			"Qdhxx",
			"Volttt",
			"DIY Headphones",
			"Sand Eyes Yellow Dragon",
			"Drager",
			"Lord of Greed",
			"Lord of Auctions",
			"Doge",
			"GalaxyFlame",
			"Weaven"
		},
	}; 
	{
		Name = "Exotic", --NEW / WHITE! All cards before Wingman8 rotate out once a new card comes in. Related cards rotate out at the same time.
		PriceInBloxBux = 50,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 434684079,
		Description = "Exotic new cards from the black market! White cards and joke cards! It's all yours, as long as you have 10 wins!",
		WinRequirement = 10;
		Cards = {
			"Blitzwolfer",
		        "kickertoken",
			"Superland6",
			"Bigtank_s",
			"ProjectSlayer",
			"iSpaceDonut",
			"ImaUMBREON",
			"caone",
			"Histor, Blood Warrior",
			"Enderlox1",
			"xiVirtual",
			"superkicker2005",
			"Killar1234567",
			"Shard Master",
			"EvilJacobthehero2013",
			"Regular_Talkshow",
			"Dairingpoophead, Tix God",
			"Roundawsome",
			"iamlogic",
			"Zabiehunter",
			"Wesker202",
			"Micpro1234",
			"Darklord1506",
			"Mlgloga",
			"MrEyeso",
			"Themediamogul99",
			"Wizardguy34",
			"DigitalSon",
			"BenCanova1",
			"RealPiggy1261",
			"Icerain",
			"Kcbeast666",
			"Walyn",
			"Pikachukiller101",
			"Cindering",
			"emilvita",
			"AII_Dragon",
			"Lord_Gizmo",
			"wikiwakiwoirier",
			"TheJazzCat22",
			"ChaoticCommando",
			"MarissaKitty04",
			"Damaging26",
			"iiSmolToaster",
			"Wrath of King Gecko",
			"Aesura",
			"Graalgamer",
			"Yoshilove574",
			"Shaylan007",
			"Indoorsnowball",
			"CjMcGamingYT",
			"AMerryCan",
			"Fenfie08",
			"BrandonOccult",
			"BandiheartYT",
			"SoulSearch",
			"Defaultio",
			"Deadly Dicey Duo",
			"hyp3rdeath",
			"DominiusConfabricor",
			"Eye of Heaven",
			"Steam Razikai",
			"UHunterU",
			"BonesMcCormick",
			"Wooden Chair",
 			"Rollernaut",
			"Exotic Murtic",
			"Suicide Bomber",
			"Roblox Gift Card",
			"MagikalYawn",
			"SubZeroExtaByte0",
			"Histor",
			"Javier Killer",
			"Kariu",
			"Beyondthegong",
			"Peika Sammai",
			"Jeeeeesus",
			"SONICTHEHEDGEHOGXXX",
			"madattak",
			"Razikai's Exploration",
			"Treas0ner",
			"CrazyCaleb77",
			"74Riley",
			"Thesupernessiiiii",
			"Ghost Dragon",
			"madkey900",
			"LeTruth",
			"Xenotrent",
			"Has",
			"RaveTea",
			"Fate_Sealed",
			"how_inconvenient",
			"Wingman8",
			"Games",
			"CanadianSanic",
			"Ultra Bestower",
			"Ultra Enhancer",
			"Ultra Otherer",
			"Ultra Beseecher",
			"Ultra Desirer",
			"Ultra Severer",
			"Ultra Depriver",
			"Ultra Vanquisher",
			"Ultra Orator",
			"Ultra Obliterator",
			"Ultra Annihilator",
			"Satyr Firemaster",
			"Great Paraselene Sage",
			"Delirious Ooze",
			"Confusion Elemental?",
			"colesans16",
			"Exotic Murtic",
			"wowwow2211",
			"BrokenBone",
			"Retro Gangster",
			"Rainbowjewelninga785",
			"Body Guards",
			"Giftsplosion",
			"DrPepperSlayer",
			"Blue Fanatic",
			"Heatlands Vortex",
			"Noob Golem",
			"Green Icon Tree",
			"Kmansong2",
			"Nova",
			"SaxoAttack",
			"Unwanted Trend",
			"Clockwork",
			"Calamity Box",
			"Xor's Lab",
			"Usering",
			"Imaginz00",
			"Scripter",
			"HatHelper",
			"GRAND DAD",
			"RachelDubs",
			"Bling Noob",
			"Clone Fave",
			"Dr.Fave",
			"Cow",
			"Cup O Tea",
			"Fat Cat",
			"Great Lord Egotist",
			"WishNite",
			"Grand Pirate King",
			"TheInnovative",
			"Robot",
			"Greygnarl",
			"Grimclaw the Unholy",
			"Titan's Stone",
			"Titan of the Holy Chamber",
			"Recruiter of the Titans",
			"Divine Favor",
			"Tweety The Twitter Bird",
			"Heavy Rain",
			"BlueTaslem",
			"Nenjas",
			"ASeal",
			"Sorcus",
			"MegaSmiley",
			"Bread Factory",
			"Dragon Horde",
			"Lunar Acolyte",
			"Lunar Warrior",
			"Mimic",
			"Berezaa",
			"Titano's Cavern",
			"Sword Fights on the Heights",
			"Haunted Mansion",
			"Crossroads",
			"Stud",
			"Bloxy Tea Party",
			"Birthday Suprise",
			"SonozakiRaito",
			"Bobaman1",
			"Rukiryo",
			"Moded",
			"Godlysinha",
			"Crystal Cultist",
			"MisterObvious",
			"Bloxikin Horde",
			"Shedletsky the Fried One",
			"FixingFailure",
			"Haggie125",
			"Lord of Auctions",
			"The Gentlemaniac",
		},
		
	};
	{
		Name = "Ancient Stirrings", --SPOOPY SCARY SKELETONS
		PriceInBloxBux = 60,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 721399106,
		Description = "Priestess Zanzel has corrupted this world. Do you have the gall to stop her? You must have 10 wins to open this pack.",
		WinRequirement = 10;
		--[[DateConstraint = {
			month = 10};
		};--]]
		Cards = {
			"Undead Teddy",
			"Treasured Unicorn",
			"Graboid",
			"LovecraftWizard",
			"Bedsheet Ghost",
			"DoeDoe",
			"Tooth Decay",
			"Carniverous Death Moth",
			"Dead Tree",
			"Possessed Skull",
			"Jason Voorhees",
			"Candy Robber",
			"DIY: Dark Dominus",
			"Abhorrant Skull",
			"Fearmiredon",
			"Victor Sinister",
			"Kalman Sinister",
			"Ghoost",
			"Korblox Skeleton",
			"Glaciem Knight",
			"Patric Sinister",
			"Slenderman",
			"Pyramid Head",
			"Haunted Redcliff Armor",
			"Headless Horseman",
			"Ignis Knight",
			"Gentle Elder",
			"Infected Mushrooms",
			"KillCactaur",
			"Haunted Overseer Armor",
			"Haunted Doge Head",
			"Hacker",
			"Apheliotropic Syzygy",
			"Waspism",
			"Smiling Golem",
			"Unresting Tombstone",
			"Mitcrawl",
			"Beast Within",
			"Sugar Skull",
			"Supercomputer's Skull",
			"Pumpkin Bomb",
			"RoboLoleris",
			"Unplumbed Lead",
			"Pumpkin Carver",
			"Stormchaser's Gambit",
			"Verisimilitudal Dissonance",
			"Swarm of Bats",
			"Nerf Zombie",
			"Psychotic Freak",
			"Spicy Lollipop",
			"The Skull Collector",
			"Priestess Zanzel, the Promised One",
			"Stranglevines",
			"Toxic Goo",
			"Noxious Gas",
			"Quan Sinister",
			"Terry Sinister",
			"Script Robber",
			"Disturbing Thoughts",
			"Mad Scientist",
			"Ye Old Arte",
			"Horse Breeder",
			"Trick or Treat",
			"Hidden Razor",
			"Hallow, the Sugarlord",
			"Horrarceusdon",
			"Horrarceusdon",
			"Gooplast",
			"Inexorable Goo Tide",
			"Haunted Korblox Armor",
			"Grim Reaper",
			"Grey Goo Scenario",
			"Eisenhower, the Alchemist",
			"Evil Prince",
			"Lumberjack",
			"Wolfbitten Noob",
			"Paraselene Ascetic",
			"Blessed Acolyte",
			"Homeless Man",
			"Wolven Blitz",
			"Unspeakable Summoning",
			"It that was Silenced",
			"Final Tree",
			"Groucho Mask",
			"Goo Golem",
			"Hallow's Enforcer",
			"Explosive Toad",
			"Death-Defying Demon",
			"Doll House",
			"Edgelord",
			"Frankenstein",
			"Final Revels",
			"Enrage",
			"Fried One Cultist",
			"Failed Expirement",
			"Dredger980",
			"Dun_Boof",
			"Cheshire Cat",
			"Bribery",
			"Cringeleaf",
			"Brothers Grotesque",
			"Claudia Sinister",
			"Cotton Candy Lion",
			"Creepy Toy",
			"Corrupt Guest",
			"DairingSpookHead",
			"Cereal Killer",
			"Dark Book of Spells",
			"Little Girl",
			"Liechtenauer's Sophistry",
		},
	};
	
	{
		Name = "Tribal", --ARCHETYPES!
		PriceInBloxBux = 50,
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 622832971,
		Description = "Filled with only cards belonging to an archetype, this pack can help you finish your deck provided you have at least 10 wins.",
		WinRequirement = 10;
		Cards = {
			"Themediamogul99",
			"Abhorrant Skull",
			"Possessed Skull",
			"Frankenstein",
			"Psychotic Freak",
			"StayBlue",
			"Glaciem Knight",
			"JaikKaik",
			"Her0z",
			"Eisenhower, the Alchemist",
			"Edgelord",
			"Ignis Knight",
			"Fleskhjerta",
			"__________",
			"Captain Doge",
			"Shamrock Doge",
			"Abraham Doge",
			"Uncle Doge",
			"Doge",
			"PEEPSTERS",
			"TrollTideTroll",
			"Doge Hound",
			"Haunted Doge Head",
			"Kolby2020",
			"CALL OF DOGE!?!",
			"Nova",
			"Lunar Warrior",
			"Lunar Acolyte",
			"Dragon Horde",
			"Egg Eyes Batter Dragon",
			"Grimclaw the Unholy",
			"Greygnarl",
			"Acolyte of the Rift",
			"Blue Eyes Indigo Dragon",
			"Megalodon the Dragon-Shark",
			"NobleDragon",
			"Infernal Acolyte",
			"Dragon's Charm",
			"Redrune Raider",
			"Fuchsia Eyes Red Dragon",
			"Skarra the DragonSlayer",
			"Nymn the Redrune Leader",
			"Necromantic Acolyte",
			"Teal Eyes Green Dragon",
			"Zerax the Untameable",
			"Fried Acolyte",
			"Sand Eyes Yellow Dragon",
			"Typheus the Whelp",
			"Dwarvern Sentry: MAX",
			"Dwarvern Sentry: Delta",
			"Dwarvern Sentry: Gamma",
			"Dwarvern Sentry: Beta",
			"Dwarvern Sentry: Alpha",
			"Dwarvern Captain",
			"Dwarvern Scientist",
			"Dwarvern Mathematician",
			"Dwarvern Engineer",
			"Dwarvern Energist",
			"Dwarvern Miner",
			"Korblox Archer",
			"Korblox General",
			"Korblox Skeleton",
			"Korblox Shadowmage",
			"Korblox Defender",
			"Haunted Korblox Armor",
			"Korblox Shaman",
			"Serhat12",
			"Korblox Archmage",
			"Korblox Deathkeeper",
			"Korblox Deathknight",
			"Meeboid",
			"Meebling",
			"Meeboid Cultist",
			"Meebling Infestation",
			"Meeboid Champion",
			"Jeptem",
			"Grand Meeboid Totem",
			"Meeboid King",
			"Summon! Meeboid Titano!",
			"Toxic Goo",
			"Gooplast",
			"Ghoost",
			"Goo Golem",
			"Inexorable Goo Tide",
			"Grey Goo Scenario",
			"Verisimilitudal Dissonance",
			"Liechtenauer's Sophistry",
			"Apheliotropic Syzygy",
			"Great Lord Egotist",
			"Ye Old Arte",
			"Traumaturge",
			"Delusionist",
			"Consume Dream",
			"Gravity Collapse",
			"Disturbing Thoughts",
			"Forbidden Power",
			"Rat King",
			"Vermin's Caress",
			"Accursed Gate",
			"Uncreativename123",
			"Uncreation",
			"Grandmasters Ninja Dojo",
			"Froot Ninja",
			"Snowskateer",
			"Arashi Pikemen",
			"BlueShadic90",
			"KnitJa",
			"Ninja Kitty",
			"Ninja",
			"Teeny Ninja",
			"Ninja Assailant",
			"Ninja Elite",
			"Ninja Trainee",
			"Ninja Combatant",
			"Noob Attack! Ninja Stars!",
			"WhiteScarf",
			"BlazerC",
			"One_Thousand_Deaths",
			"Overseer Drake",
			"Eye of Overseer",
			"stereoplexus",
			"Overseer Prophet",
			"Overseer's Steed",
			"Haunted Overseer Armor",
			"Oddman's Gambit",
			"Overseer General",
			"Overseer Beast",
			"Bereghost",
			"Police Officer",
			"HatdaCat",
			"Luigifan103",
			"President Duck",
			"Isaac0333",
			"Isaac0333-V2",
			"Police Combatant",
			"Aesthetical",
			"Gravity Inspector",
			"Redcliff Messenger",
			"Redcliff Mauler",
			"Redcliff Archer",
			"Redcliff Heretic",
			"Redcliff: Rise!",
			"Redcliff: Decimate!",
			"Haunted Redcliff Armor",
			"Redcliff Enforcer",
			"Redcliff Rogue",
			"Redcliff Elite Commander",
			"Victor Sinister",
			"Kalman Sinister",
			"Patric Sinister",
			"Claudia Sinister",
			"Quan Sinister",
			"xXVitalityVoidXx",
			"Skullsten",
			"Skeleton Armada",
			"Supercomputer's Skull",
			"Sugar Skull",
			"The Skull Collector",
			"Titan's Stone",
			"Recruiter of the Titans",
			"Titan of the Holy Chamber",
			"Titan of the Deep Below",
			"Titan of the Infernal Abyss",
			"Titan of the Dying Forest",
			"Titan of the Fried One",
			"Toy Remote",
			"Toy Teeth",
			"Toy Plane",
			"Toy Truck",
			"Toy Car",
			"Toy Train",
			"Toy Boss Dino",
			"Call of the Teddy Bear",
			"Zombie",
			"Nerf Zombie",
			"Construction Zombie",
			"Unresting Tombstone",
			"Zombie Cultist",
			"Zombie Summoner",
			"Zom-nobi",
			"Zombie King",
			"Bee",
			"Swarm",
			"CalmFoxz",
			"Beehive",
			"Queen Bee",
			"Beekeeper",
			"Waspism",
			"True Hivemind",
			"Cat's Eye Wing Flock",
			"Cat's Eye Corpse Stealer",
			"Cat's Eye, Master of Perception",
			"Cat's Eye Cultist",
			"Cat's Eye Nexus",
			"Scripter",
			"Lebron",
			"wer8888",
			"Script Robber",
			"Mad Scientist",
			"destruction5033",
			"MICHIKUSCHI",
			"Grand Glaciem Mage",
			"Erik.Cassel",
			"JaikKaik",
			"Stravant",
			"Tinfoilbot",
			"Tomspick",
			"LordVasco",
			"mrawesomecarter",
			"Paraselene Sage",
			"Grand Ignis Mage",
			"PassTheToiletPaper",
			"MUTO2014",
			"TheSteelEagle",
			"Tone",
			"Master Josue",
			"Has",
			"Forbidden Power",
			"Cherie",
			"HashtagWatermelon",
			"PixelFlame",
			"zKevin",
			"666",
			"NerfModder",
			"HeyItsColin",
			"UAE",
			"Majora7",
			"Lopous",
			"Scrub",
			"Lilly_S",
			"CloneTrooper1019",
			"DDude",
			"DominatedLegacy",
			"Fancy Arachnid",
			"NatzHakz",
			"KillCactaur",
			"HyperBlue",
			"InceptionTime",
			"Ghost Dragon",
			"madattak",
		},
	};
	
	{
		Name = "Teaism's Gifts", --CHRISTMAS!
		Hidden = true;
		PriceInBloxBux = 0;
		PriceInRobux = 50;
		CardsInPack = 4,
		CardPackId = 585626122,
		Description = "Teaism's special gift, just for you. Merry Christmas. (You need 10 wins to open this pack.)",
		WinRequirement = 10;
		DateConstraint = {
			month = {12};
		};
		Cards = {
			"Baker",
			"Hot Chocolate",
			"GRAND CLAUS",
			"Gingerbread Man",
			"Sugarlord",
			"CrazyEggNoggin",
			"Eggnog",
			"MyDadIsASanta",
			"Wooden Toy Train",
			"RoboSanta",
			"Eleemosynary Beneficient",
			"Elfdevin",
			"Entangling Lights",
			"Wolfbitten Elf",
			"SantaSorin",
			"Santa Doge",
			"Fruit Cake",
		},
	};
	
	{
		Name = "Tough Love", --VALENTINES!
		Hidden = true;
		PriceInBloxBux = 1000;
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 654911255,
		Description = "Over 40 special edition Valentine themed cards! Can your heart resist them? <3 (Minimum 10 wins. Stalker and Combine Garrison are only found in the Art Box.)",
		WinRequirement = 10;
		DateConstraint = {
			month = {2};
		};
		Cards = {
			"Ejob-Val",
			"The Hugger",
			"PencilWizard-Val",
			"Chef-Val",
			"PixelPistol-Val",
			"TeeVee-Val",
			"Newbie-Val",
			"RiceStorage-Val",
			"Bowl of Greed-Val",
			"Lord of Greed-Val",
			"DeadZoneHark-Val",
			"Sorry-Val",
			"Pilot-Val",
			"Hamstermon-Val",
			"Pirate-Val",
			"Gato Luz-Val",
			"Burning Phoenix-Val",
			"Hallows Treats-Val",
			"Dr.Fave-Val",
			"SuperCloud9-Val",
			"Vitality Potion-Val",
			"Pancake Break-Val",
			"Uncreativename123-Val",
			"IlIll-Val",
			"MiloCortez-Val",
			"Sylrath-Val",
			"KingCactaur-Val",
			"Korblox Deathknight-Val",
			"BlackSymphony-Val",
			"Forbidden Power-Val",
			"Cupid's Eye Wing Flock",
			"Cupid's Eye Cultist",
			"Cupid's Eye Heart Stealer",
			"Cupid's Eye Nexus",
			"Cupid's Eye, Master of Romance",
			"Evil Prince-Val",
			"SoulSearch-Val",
		},
		
		Name = "Summer Salt", --SUMMER!
		PriceInBloxBux = 1000;
		PriceInRobux = 0;
		CardsInPack = 4,
		CardPackId = 654911255,
		Description = "",
		WinRequirement = 10;
		DateConstraint = {
			month = {8};
		};
		Cards = {
			"Ambamby-Sun",
			"AntiSammeh-Sun",
			"AVote-Sun",
			"Heavy Rain-Sun",
			"DominiusConfabricor-Sun",
			"Eisenhower-Sun",
			"Guest-Sun",
			"Fenrier-Sun",
			"Froot Ninja-Sun",
			"GemInNight-Sun",
			"Grand Meeboid Totem-Sun",
			"Grand Pirate King-Sun",
			"Hallow, the Sugarlord-Sun",
			"Haunted Mansion-Sun",
			"HuntarioRBLX-Sun",
			"Jeptem-Sun",
			"Jimminus-Sun",
			"Lady RedNight-Sun",
			"Latchie-Sun",
			"LeetWizard-Sun",
			"Luck o The Lobsters-Sun",
			"MarissaKitty04-Sun",
			"Meebling Infestation-Sun",
			"Meeboid King-Sun",
			"Meeboid-Sun",
			"Meeboid Champion-Sun",
			"Meeboid Surfer-Sun",
			"Mitpaul-Sun",
			"Oozlebachr-Sun",
			"Pixellus-Sun",
			"RachelDubs-Sun",
			"Satyr Firemaster-Sun",
			"Snowskateer-Sun",
			"Spooky Caverns-Sun",
			"Titano-Sun",
			"Valletta-Sun",
			"Weaven-Sun",
			"Widgeon-Sun",
		},
	};
	
}

return packs

		
