local tentwelvesixteen = { -- CARD_ID, NAME, POWER, HEALTH, RARITY,BIO	
	["LeTruth"] = {
		["Id"] = 585558515,
		["Name"] = "LeTruth",
		["Health"] = 250,
		["Power"] = 250,
		["Rarity"] = "Common",
		["AttackEffect"] = "Dash",
		["Color"] = "Red", 
		["Cost"] = {["Red"] = 3,},
		["Charge"] = true,
		["Effect"] = {
			Name = "Haydoscale",
			Description = "Haste. Whenever your opponent loses life, LeTruth gains 200 power.",
			["Type"] = "OnEnemyHealthLoss",
			["Power"] = {{"Strengthen",200}},
			Target = "Self",
		},
		["Bio"] = "To know something requires three things. You must know why it's true, it must be true, and you must believe it's true.",
	},
	
	["Xenotrent"] = {
		["Id"] = 573807351,
		["Name"] = "Xenotrent",
		["Health"] = 600,
		["Power"] = 500,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "Dash",
		["Color"] = "Blue", 
		["Cost"] = {["Neutral"] = 1, ["Blue"] = 4,},
		["Effect"] = {
			Name = "Haydoscale",
			Description = "Whenever your opponent casts an action or terrain spell, end the turn.",
			["Type"] = "OnEnemyCast",
			["Power"] = {{"EndTurn",1}},
			Target = "Self",
		},
		["Bio"] = "He rocks your world. Literally.",
	},
	
	["Deep Sea Diver"] = {
		["Id"] = 543830736,
		["Name"] = "Deep Sea Diver",
		["Health"] = 600,
		["Power"] = 400,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "Dash",
		["Color"] = "Blue", 
		["Cost"] = {["Blue"] = 3,["Neutral"] = 1},
		["Effect"] = {
			Name = "Massive Stamaina",
			Description = "Whenever you cast an action or terrain spell, generate a white icon.",
			["Type"] = "OnAllyCast",
			["Power"] = {{"Neutral",1}},
			Target = "Ally",
		},
		["Bio"] = "Yes, diving 100 meters without a scuba gear is totally fine.",
	},
	
	["Dicey Dave"] = {
		["Id"] = 543830125,
		["Name"] = "Dicey Dave",
		["Health"] = 800,
		["Power"] = 400,
		["Rarity"] = "Epic",
		["AttackEffect"] = "Dash",
		["Color"] = "Yellow", 
		["Cost"] = {["Yellow"] = 4,["Neutral"] = 1},
		["Effect"] = {
			Name = "Gamble till you drop",
			Description = "Both players lose 400 life each turn.",
			["Type"] = "OnEnd",
			["Power"] = {{"Inflict",400}},
			Target = "All",
		},
		["Bio"] = "You up for a gamble?.",
	},
	
	["Dicey Drake"] = {
		["Id"] = 543830416,
		["Name"] = "Dicey Drake",
		["Health"] = 400,
		["Power"] = 400,
		["Rarity"] = "Epic",
		["AttackEffect"] = "Dash",
		["Color"] = "Blue", 
		["Cost"] = {["Blue"] = 4,["Neutral"] = 2},
		["Effect"] = {
			Name = "Gamble till you drop",
			Description = "When summoned, lock all enemy fighters for 1 turn. All enemy fighters enter play with 150 less power.",
			["Type"] = "OnSummon",
			["Power"] = {{"Lock",1},{"Summon","Dicey Drake Token","Ally"},{"Damage",9999,"Self"}},
			Target = "Opponent",
		},
		["Bio"] = "A hammer wielding former Korblox fighter that's itching for a gamble of the century.",
	},
	
	["Dicey Drake Token"] = {
		["Id"] = 543830416,
		["Name"] = "Dicey Drake",
		["Health"] = 400,
		["Power"] = 400,
		["Rarity"] = "Token",
		["AttackEffect"] = "Dash",
		["Color"] = "Blue", 
		["Cost"] = {["Blue"] = 4,["Neutral"] = 2},
		["Effect"] = {
			Name = "Gamble till you drop",
			Description = "When summoned, lock all enemy fighters for 1 turn. All enemy fighters enter play with 150 less power.",
			["Type"] = "OnEnemySummon",
			["Power"] = {{"Weaken",150}},
			Target = "Aggressor",
		},
		["Bio"] = "A hammer wielding fighter that's itching for a gamble of the century.",
	},
	
	["Wild Reporter Tracy"] = {
		["Id"] = 627301021,
		["Name"] = "Reporter Tracy",
		["AltCards"] = {
			["WildReporterTracyV2"] = {
				["Name"] = "Wild Reporter Tracy",
				["Id"] = 556338220,
				["AltArt"] = true,
			}
		},
		["Health"] = 750,
		["Power"] = 525,
		["Rarity"] = "Epic",
		["AttackEffect"] = "Dash",
		["Color"] = "Yellow", 
		["Cost"] = {["Blue"] = 2,["Neutral"] = 2,["Yellow"] = 4},
		["Effect"] = {
			Name = "Hot Ancient News",
			Description = "When this card attacks, put a random epic into your hand.",
			["Type"] = "OnAttack",
			["Power"] = {{"RandomAdd","Epic"}},
			Target = "Ally",
		},
		["Bio"] = "Hot Ancient News.",
	},

	["Has"] = {
		["Id"] = 574173044,
		["Name"] = "Has",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "Dash",
		["Color"] = "Red", 
		["Cost"] = {["Red"] = 6,},
		["Effect"] = {
			Name = "Hot Ancient News",
			Description = "Summon a 450/750 fighter. Whenever you cast an action or terrain spell, increase the power of all allied fighters by 100.",
			["Type"] = "OnSummon",
			["Power"] = {{"Summon","Has Token"}},
			Target = "Ally",
		},
		["Bio"] = "You can hasard a guess as to how this is going to end.",
	},

	["Has Token"] = {
		["Id"] = 574173044,
		["Name"] = "Has",
		["Health"] = 450,
		["Power"] = 750,
		["Rarity"] = "Token",
		["AttackEffect"] = "Dash",
		["Color"] = "Red", 
		["Cost"] = {["Red"] = 6,},
		["Effect"] = {
			Name = "Hot Ancient News",
			Description = "Summon a 450/750 fighter. Whenever you cast an action or terrain spell, increase the power of all allied fighters by 100.",
			["Type"] = "OnAllyCast",
			["Power"] = {{"Strengthen",100}},
			Target = "Ally",
		},
		["Bio"] = "You can hasard a guess as to how this is going to end.",
	},

	["RaveTea"] = {
		["Id"] = 626083911,
		["Name"] = "RaveTea",
		["Health"] = 450,
		["Power"] = 450,
		["Rarity"] = "Epic",
		["AttackEffect"] = "Dash",
		["Color"] = "Blue", 
		["Cost"] = {["Neutral"] = 3, ["Blue"] = 3,},
		["Effect"] = {
			Name = "Join The Rave",
			Description = "Enemy fighters enter play as a copy of RaveTea, without this effect.",
			["Type"] = "OnEnemySummon",
			["Power"] = {{"Damage",9999,"Aggressor"},{"Summon","RaveTea Token"}},
			Target = "Opponent",
		},
		["Bio"] = "The mind does not control the tea. The tea controls the mind.",
	},

	["RaveTea Token"] = {
		["Id"] = 626083911,
		["Name"] = "RaveTea",
		["Health"] = 450,
		["Power"] = 450,
		["Rarity"] = "Token",
		["AttackEffect"] = "Dash",
		["Color"] = "Blue", 
		["Cost"] = {["Neutral"] = 3, ["Blue"] = 3,},
		["Bio"] = "The mind does not control the body. The tea controls the body.",
	},

	["Uncreation"] = {
		["Id"] = 574356556,
		["Name"] = "Uncreation",
		["Health"] = 1000,
		["Power"] = 1000,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "Dash",
		["CounterBlock"] = true,
		["Color"] = "Green", 
		["Cost"] = {["Neutral"] = 5, ["Blue"] = 1, ["Green"] = 5,},
		["Archetype"] = "Nightmare",
		["Effect"] = {
			Name = "Hot Ancient News",
			Description = "Can't counterattack. Whenever a fighter dies, shuffle a nightmare into your opponent's deck.",
			["Type"] = "OnAnyDeath",
			["Power"] = {{"DeckAdd","Nightmare"}},
			Target = "Opponent",
		},
		["Bio"] = "Soon.",
	},
	
		
	["madkey900"] = {
		["Id"] = 581847885,
		["Name"] = "madkey900",
		["Health"] = 300,
		["Power"] = 200,
		["Rarity"] = "Common",
		["AttackEffect"] = "Slash",
		["Color"] = "Blue",
		["Cost"] = {["Neutral"] = 1,["Blue"] = 2,},
		["Effect"] = {
			Name = "Thug Life",
			Description = "Shuffle a Dairingpoophead into your deck.",
			["Type"] = "OnSummon",
			["Power"] = {{"DeckAdd","DairingPoopHead"}},
			Target = "Ally",
		},
		["Bio"] = "The maddest of keys.",
	},				
	
	["Ghost Dragon"] = {
		["Id"] = 581907836,
		["Name"] = "Ghost Dragon",
		["Archetype"] = "Saprasam",
		["Health"] = 400,
		["Power"] = 400,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Fire",
		["Color"] = "Blue",
		["Cost"] = {["Neutral"] = 3,["Blue"] = 2,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "When this card attacks, what it attacked loses 200 power.",
			["Type"] = "OnAttack",
			["Power"] = {{"Weaken",200,"Aggressor"}},
			Target = "Self",
		},
		["Bio"] = "Legend says this was the soul that once inhabited NobleDragon's original dragon.",
	},		
	
	["madattak"] = {
		["Id"] = 581907237,
		["Name"] = "madattak",
		["Health"] = 1500,
		["Power"] = 150,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "Slash",
		["Archetype"] = "Zombie",
		["Color"] = "Green",
		["Cost"] = {["Neutral"] = 5,["Green"] = 3,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "Whenever an enemy fighter dies, summon a zombie.",
			["Type"] = "OnEnemyDeath",
			["Power"] = {{"Summon","Zombie"}},
			Target = "Ally",
		},
		["Bio"] = "MY EXPERIMENT IS COMPLETE! ZOMBIES RUNNING LEFT AND RIGHT ACROSS THE WORLD! HAHAHAHAHAHAA!.",
	},	

	["Treas0ner"] = {
		["Id"] = 581970144,
		["Name"] = "Treas0ner",
		["Health"] = 1500,
		["Power"] = 0,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Slash",
		["Color"] = "Red",
		["Cost"] = {["Neutral"] = 9,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "At the end of your turns, Treas0ner gains 300 health and 100 power.",
			["Type"] = "OnEnd",
			["Power"] = {{"Heal",300},{"Strengthen",100}},
			Target = "Self",
		},
		["Bio"] = "I was expecting something spicier.",
	},	

	["Jeeeeesus"] = {
		["Id"] = 581984573,
		["Name"] = "Jeeeeesus",
		["Health"] = 222,
		["Power"] = 2222.22,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "Gun",
		["Color"] = "Yellow",
		["Cost"] = {["Yellow"] = 5,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "Your opponent draws 4 cards. End the turn.",
			["Type"] = "OnSummon",
			["Power"] = {{"Draw",4},{"EndTurn",030,"Ally"}},
			Target = "Opponent",
		},
		["Bio"] = "Christ!",
	},	

	["Razikai's Exploration"] = {
		["Id"] = 581970386,
		["Name"] = "Razikai's Exploration",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Common",
		["AttackEffect"] = "Slash",
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 9, ["Green"] = 4,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "Summon two space monsters.",
			["Type"] = "OnSummon",
			["Power"] = {{"Summon","Otub"},{"Summon","Otub"}},
			Target = "Ally",
		},
		["Bio"] = "NOT THE OTUBS! ANYTHING BUT THAT!",
	},	

	["MurticUnicorn 5"] = {
		["Id"] = 585561705,
		["Name"] = "Exotic Murtic",
		["Health"] = 800,
		["Power"] = 0,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "Slash",
		["Color"] = "Neutral",
		["Cost"] = {["Neutral"] = 7,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "5 charges. At the end of your turns, remove a charge. When you remove the last, add 5 charges and return all non-white fighters to their owner's hand.",
			["Type"] = "OnEnd",
			["Power"] = {{"Summon", "MurticUnicorn 4"},{"Damage",9999,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "A small erosion leaves a mark!",
	},	

	["MurticUnicorn 4"] = {
		["Id"] = 585561705,
		["Name"] = "Exotic Murtic",
		["Health"] = 800,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Color"] = "Neutral",
		["Cost"] = {["Neutral"] = 7,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "4 charges. At the end of your turns, remove a charge. When you remove the last, add 5 charges and return all non-white fighters to their owner's hand.",
			["Type"] = "OnEnd",
			["Power"] = {{"Summon", "MurticUnicorn 3"},{"Damage",9999,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "To become woven...",
	},	

	["MurticUnicorn 3"] = {
		["Id"] = 585561705,
		["Name"] = "Exotic Murtic",
		["Health"] = 800,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Color"] = "Neutral",
		["Cost"] = {["Neutral"] = 7,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "3 charges. At the end of your turns, remove a charge. When you remove the last, add 5 charges and return all non-white fighters to their owner's hand.",
			["Type"] = "OnEnd",
			["Power"] = {{"Summon", "MurticUnicorn 2"},{"Damage",9999,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "and we can scream into the dark!",
	},	

	["MurticUnicorn 2"] = {
		["Id"] = 585561705,
		["Name"] = "Exotic Murtic",
		["Health"] = 800,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Color"] = "Neutral",
		["Cost"] = {["Neutral"] = 7,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "2 charges. At the end of your turns, remove a charge. When you remove the last, add 5 charges and return all non-white fighters to their owner's hand.",
			["Type"] = "OnEnd",
			["Power"] = {{"Summon", "MurticUnicorn 1"},{"Damage",9999,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "Until it hears us, we want it near us!",
	},	

	["MurticUnicorn 1"] = {
		["Id"] = 596217210,
		["Name"] = "Exotic Murtic",
		["Health"] = 800,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Color"] = "Neutral",
		["Cost"] = {["Neutral"] = 7,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "1 charge. At the end of your turns, remove a charge. When you remove the last, add 5 charges and return all non-white fighters to their owner's hand.",
			["Type"] = "OnEnd",
			["Power"] = {{"Return",030,"ColorRed"},{"Return",030,"ColorYellow"},{"Return",030,"ColorBlue"},{"Return",030,"ColorGreen"},{"Summon", "MurticUnicorn 5"},{"Damage",9999,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "To help us FADE!",
	},	

	["74Riley"] = {
		["Id"] = 596205364,
		["Name"] = "74Riley",
		["Health"] = 450,
		["Power"] = 650,
		["Rarity"] = "Common",
		["AttackEffect"] = "Slash",
		["Color"] = "Red",
		["Cost"] = {["Red"] = 4,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "Whenever an enemy fighter dies, your opponent loses 100 life.",
			["Type"] = "OnEnemyDeath",
			["Power"] = {{"Inflict",100,"Opponent"}},
			Target = "Ally",
		},
		["Bio"] = "The first 73 Rilies caused him trouble.",
	},	

	["CrazyCaleb"] = {
		["Id"] = 596217027,
		["Name"] = "CrazyCaleb77",
		["Health"] = 400,
		["Power"] = 400,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Slash",
		["Color"] = "Green",
		["Cost"] = {["Green"] = 3,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "Summon a lattice of green crystals, each with different effects. Crystals don't generate icons.",
			["Type"] = "OnSummon",
			["Power"] = {{"Summon","Crystal of Reality's Fractal"},{"Summon","Crystal of Nature's Surge"},{"Summon","Crystal of Heaven's Pulse"},{"Add","Targeting Blip"}},
			Target = "Ally",
		},
		["Bio"] = "Heaven. Earth. The realities inbetween. This is what I stand for.",
	},	

	["Crystal of Reality's Fractal"] = {
		["Id"] = 596217083,
		["Name"] = "Crystal of Reality's Fractal",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Archetype"] = "Crystal",
		["Color"] = "Green",
		["Cost"] = {["Green"] = 1,},
		["Token"] = true,
		["Effect"] = {
			Name = "Reincarnation",
			Description = "When this card is targeted, all allied fighters gain 100 health, then destroy all crystals.",
			["Type"] = "OnTarget",
			["Power"] = {{"Heal",150},{"Damage",9999,"Archetype"}},
			Target = "Ally",
		},
		["Bio"] = "The realities inbetween. This is what I need.",
	},

	["Crystal of Nature's Surge"] = {
		["Id"] = 596216999,
		["Name"] = "Crystal of Nature's Surge",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Archetype"] = "Crystal",
		["Color"] = "Green",
		["Cost"] = {["Green"] = 1,},
		["Token"] = true,
		["Effect"] = {
			Name = "Reincarnation",
			Description = "When this card is targeted, gain 500 life, then destroy all crystals.",
			["Type"] = "OnTarget",
			["Power"] = {{"Cost",-500},{"Damage",9999,"Archetype"}},
			Target = "Ally",
		},
		["Bio"] = "Earth. This is what I need.",
	},	

	["Crystal of Heaven's Pulse"] = {
		["Id"] = 596217205,
		["Name"] = "Crystal of Heaven's Pulse",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Archetype"] = "Crystal",
		["Color"] = "Green",
		["Cost"] = {["Green"] = 1,},
		["Token"] = true,
		["Effect"] = {
			Name = "Reincarnation",
			Description = "When this card is targeted, generate a white icon, then destroy all crystals.",
			["Type"] = "OnTarget",
			["Power"] = {{"Neutral",1},{"Damage",9999,"Archetype"}},
			Target = "Ally",
		},
		["Bio"] = "Heaven. This is what I need.",
	},	

	["SONICTHEHEDGEHOGXXX"] = {
		["Id"] = 596217036,
		["Name"] = "SONICTHEHEDGEHOGXXX",
		["Health"] = 400,
		["Power"] = 600,
		["Rarity"] = "Epic",
		["AttackEffect"] = "Slash",
		["Color"] = "Blue",
		["Cost"] = {["Neutral"] = 3, ["Blue"] = 2,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "Deal 700 damage to all other blue fighters.",
			["Type"] = "OnSummon",
			["Power"] = {{"Heal",700,"Self"},{"Damage",700,"ColorBlue"}},
			Target = "Ally",
		},
		["Bio"] = "SCREAM IN ALL CAPS! INDEED! MAXIMUM LOGIC!",
	},

	["Thesupernessiiiii"] = {
		["Id"] = 596217136,
		["Name"] = "Thesupernessiiiii",
		["Health"] = 300,
		["Power"] = 300,
		["Rarity"] = "Common",
		["AttackEffect"] = "Slash",
		["Color"] = "Red",
		["Cost"] = {["Neutral"] = 1, ["Red"] = 2,},
		["Effect"] = {
			Name = "Pyrotechnics",
			Description = "Whenever your opponent acts an action or terrain spell, deal 700 damage to this card and end the turn.",
			["Type"] = "OnEnemyCast",
			["Power"] = {{"Damage",700,"Self"},{"EndTurn",1}},
			Target = "Ally",
		},
		["Bio"] = "A wandering bard, playing his music.",
	}, 

	["MagikalYawn"] = {
		["Id"] = 616082575,
		["Name"] = "MagikalYawn",
		["Health"] = 700,
		["Power"] = 700,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Slash",
		["Color"] = "Red",
		["Cost"] = {["Neutral"] = 3, ["Red"] = 5,},
		["Effect"] = {
			Name = "Pyrotechnics",
			Description = "Whenever you lose life, generate a white icon.",
			["Type"] = "OnHealthLoss",
			["Power"] = {{"Neutral",1}},
			Target = "Ally",
		},
		["Bio"] = "Let's... Get this show on the road, eh...? *Flop*",
	}, 

	["SubZeroExtaByte0"] = {
		["Id"] = 616082672,
		["Name"] = "SubZeroExtaByte0",
		["Health"] = 1200,
		["Power"] = 200,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "Slash",
		["Color"] = "Red",
		["Cost"] = {["Neutral"] = 3, ["Red"] = 3,},
		["Effect"] = {
			Name = "Pyrotechnics",
			Description = "After this card finishes attacking a fighter, a target fighter gains 200 power.",
			["Type"] = "OnAttackEnd",
			["Power"] = {{"Strengthen",200}},
			Target = "Single",
		},
		["Bio"] = "Fatality.",
	}, 

	["Histor"] = {
		["Id"] = 616082705,
		["Name"] = "Histor",
		["Health"] = 350,
		["Power"] = 700,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Slash",
		["Color"] = "Red",
		["Cost"] = {["Yellow"] = 3,},
		["Effect"] = {
			Name = "Pyrotechnics",
			Description = "Whenever you lose life, summon a noob.",
			["Type"] = "OnHealthLoss",
			["Power"] = {{"Summon","Noob"}},
			Target = "Ally",
		},
		["Bio"] = "Historically, you're a scrub.",
	}, 


	["Javier Killer"] = {
		["Id"] = 616082761,
		["Name"] = "xXJavier_killer1xX",
		["Health"] = 200,
		["Power"] = 600,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Slash",
		["Color"] = "Red",
		["Cost"] = {["Red"] = 2,},
		["Effect"] = {
			Name = "Pyrotechnics",
			Description = "Whenever you lose life, Deal 50 damage to all enemy fighters.",
			["Type"] = "OnHealthLoss",
			["Power"] = {{"Damage",50,"Opponent"}},
			Target = "Ally",
		},
		["Bio"] = "I will destroy all new houses.",
	}, 

	["Kariu"] = {
		["Id"] = 627331996,
		["Name"] = "Kariu",
		["AltCards"] = {
			["Kariu-ArtV"] = {
				["Id"] = 620408233,
				["Effect"] = {
					Name = "Pyrotechnics",
					Description = "You gain 1000 life. Whenever you gain life, set your white and green icons to 3.",
					["Type"] = "OnSummon",
					["Power"] = {{"Summon","Kariu2-ArtV"},{"Cost",-1000},{"Damage",9999,"Self"}},
					Target = "Ally",
				},
				["AltArt"] = true,
			}
		},
		["Health"] = 600,
		["Power"] = 150,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Slash",
		["Color"] = "Green",
		["Cost"] = {["Green"] = 4,},
		["Effect"] = {
			Name = "Pyrotechnics",
			Description = "You gain 1000 life. Whenever you gain life, set your white and green icons to 3.",
			["Type"] = "OnSummon",
			["Power"] = {{"Summon","Kariu2"},{"Cost",-1000},{"Damage",9999,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "Consider me blessed.",
	}, 

	["Kariu2"] = {
		["Id"] = 627331996,
		["Name"] = "Kariu",
		["AltCards"] = {
			["Kariu2-ArtV"] = {
				["Id"] = 620408233,
				["AltArt"] = true,
			}
		},
		["Health"] = 600,
		["Power"] = 150,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Color"] = "Green",
		["Cost"] = {["Green"] = 4,},
		["Effect"] = {
			Name = "Pyrotechnics",
			Description = "You gain 1000 life. Whenever you gain life, set your white and green icons to 3.",
			["Type"] = "OnHealthGain",
			["Power"] = {{"SetNeutral",3},{"SetGreen",3}},
			Target = "Ally",
		},
		["Bio"] = "Consider us blessed.",
	}, 

	["Beyondthegong"] = {
		["Id"] = 626451013,
		["Name"] = "Beyondthegong",
		["Health"] = 100,
		["Power"] = 500,
		["Rarity"] = "Common",
		["AttackEffect"] = "Slash",
		["Color"] = "Red",
		["Cost"] = {["Neutral"] = 1, ["Red"] = 3,},
		["Effect"] = {
			Name = "Nerve Buster",
			Description = "Whenever your opponent loses life, this card gains 100 health.",
			["Type"] = "OnEnemyHealthLoss",
			["Power"] = {{"Heal",100}},
			Target = "Self",
		},
		["Bio"] = "Helmsmasher in one timeline. Bellstriker in another.",
	}, 

	["Peika Sammai"] = {
		["Id"] = 662457643,
		["Name"] = "Peika Sammai",
		["Health"] = 600,
		["Power"] = 600,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "Slash",
		["Color"] = "Red",
		["Cost"] = {["Red"] = 4,},
		["Effect"] = {
			Name = "Pyrotechnics",
			Description = "At the end of your turns, lose two white icons. Peika Sammai gains 100 health and power. This effect can cause negative icons.",
			["Type"] = "OnEnd",
			["Power"] = {{"Neutral",-2},{"Heal",100,"Self"},{"Strengthen",100,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "THIS IS A LATE BIRTHDAY GIFT, ISN'T IT",
	}, 

	["FixingFailure"] = {
		["Id"] = 622210137,
		["Name"] = "FixingFailure",
		["Health"] = 700,
		["Power"] = 700,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "Slash",
		["Color"] = "Neutral",
		["Cost"] = {["Neutral"] = 7,},
		["Effect"] = {
			Name = "Pyrotechnics",
			Description = "Whenever your opponent summons a fighter, FixingFailure gains 200 health.",
			["Type"] = "OnEnemySummon",
			["Power"] = {{"Heal",200,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "If he fixes failure, why hasn't he fixed himself?",
	}, 
	
	["BonesMcCormick"] = {
		["Id"] = 627903698,
		["Name"] = "BonesMcCormick",
		["Health"] = 300,
		["Power"] = 125,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "Fire",
		["Color"] = "Green",
		["Cost"] = {["Green"] = 3,},
		["Effect"] = {
			Name = "moo",
			Description = "When this card is targeted, it gains 300 health and power. End the turn.",
			["Type"] = "OnTarget",
			["Power"] = {{"Heal","300"},{"Strengthen","300"},{"EndTurn",1}},
			Target = "Self",
		},
		["Bio"] = "His gum is as strong as his bones!",
	}, 	
	
	["UHunterU"] = {
		["Id"] = 638721475,
		["Name"] = "UHunterU",
		["Health"] = 600,
		["Power"] = 200,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "GunShot",
		["Color"] = "Red",
		["Cost"] = {["Red"] = 3,},
		["Effect"] = {
			Name = "moo",
			Description = "Whenever this card attacks, you lose 200 life and UHunterU gains 100 power.",
			["Type"] = "OnAttack",
			["Power"] = {{"Cost",200},{"Strengthen",100,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "UHunt, ULive.",
	},
	
	["Eye of Heaven"] = {
		["Id"] = 638044941,
		["Name"] = "Eye of Heaven",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "GunShot",
		["Color"] = "Red", 
		["Cost"] = {["Red"] = 60,},
		["Effect"] = {
			Name = "Rebuilding The Place",
			Description = "You win the game.",
			["Type"] = "OnSummon",
			["Power"] = {{"Inflict",999999,"Opponent"}},
			Target = "Opponent",
		},
		["Bio"] = "",
	},	
	
	["Steam Razikai"] = {
		["Id"] = 630010945,
		["Name"] = "Steam Razikai",
		["Health"] = 200,
		["Power"] = 200,
		["Rarity"] = "Common",
		["AttackEffect"] = "Dash",
		["Color"] = "Blue", 
		["Cost"] = {["Blue"] = 3, ["Yellow"] = 1,},
		["Effect"] = {
			Name = "Sticks and Stones and Steam",
			Description = "Whenever your opponent summons a fighter, return Steam Razikai and that fighter to their owner's hand.",
			["Type"] = "OnEnemySummon",
			["Power"] = {{"Return",030},{"Return",030,"Aggressor"}},
			Target = "Self",
		},
		["Bio"] = "Not to be confused with Valve's premier gaming service.",
	},
	
	["PlaceRebuilder"] = {
		["Id"] = 670422221,
		["Name"] = "PlaceRebuilder",
		["Health"] = 1200,
		["Power"] = 100,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "GunShot",
		["Color"] = "Blue", 
		["Cost"] = {["Neutral"] = 4, ["Blue"] = 6,},
		["Effect"] = {
			Name = "Rebuilding The Place",
			Description = "When PlaceRebuilder attacks, return the attacked fighter to it owners hand, then lock PlaceReBuilder for 2 turns.",
			["Type"] = "OnAttack",
			["Power"] = {{"Return",030},{"Lock",2,"Self"}},
			Target = "Aggressor",
		},
		["Bio"] = "He can easily tear a place down, then rebuild it.",
	},	
	
	["DominiusConfabricor"] = {
		["Id"] = 645386479,
		["Name"] = "DominiusConfabricor",
		["Health"] = 900,
		["Power"] = 0,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Gust",
		["Color"] = "Yellow",
		["Cost"] = {["Neutral"] = 3,["Yellow"] = 1,},
		["Effect"] = {
			Name = "Pacifist",
			Description = "At the end of your turns, both players draw a card and generate two white icons.",
			["Type"] = "OnEnd",
			["Power"] = {{"Neutral",2},{"Draw",1}},
			Target = "All",
		},
		["Bio"] = "Love your neighbor as you love yourself. There is no greater commandment.",
	},
	
	["SoulSearch"] = {
		["Id"] = 701066662,
		["Name"] = "SoulSearch",
		["AltCards"] = {
			["SoulSearch-Val"] = {
				["Id"] = 701782288,
				["Name"] = "SoulMateSearch",
			["Bio"] = "Always searching for the perfect soulmate.",
			}
		},
		["Health"] = 1000,
		["Power"] = 300,
		["Rarity"] = "Epic",
		["AttackEffect"] = "Gust",
		["Color"] = "Red",
		["Cost"] = {["Red"] = 7,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Each time this fighter attacks, it gains 300 Power.",
			["Type"] = "OnAttack",
			["Power"] = {"Strengthen",300,"Self"},
			Target = "Ally",
		},
		["Bio"] = "Always searching for the perfect soul.",
	},
	
	["hyp3rdeath"] = {
		["Id"] = 650933716,
		["Name"] = "hyp3rdeath",
		["Health"] = 1750,
		["Power"] = 500,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "GunShot",
		["Color"] = "Blue",
		["Cost"] = {["Neutral"] = 6, ["Blue"] = 5, ["Red"] = 1,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "When this fighter is targeted, destroy it and spawn three Voidsealers.",
			["Type"] = "OnTarget",
			["Power"] = {{"Summon","Voidsealer"},{"Summon","Voidsealer"},{"Summon","Voidsealer"},{"Damage",9999,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "I'm sorry, what were we doing? I was procrastinating so much that I kicked your butt on accident.",
	},
		
	["Deadly Dicey Duo"] = {
		["Id"] = 677356865,
		["Name"] = "Deadly Dicey Duo",
		["Health"] = 1400,
		["Power"] = 650,
		["Rarity"] = "Epic",
		["AttackEffect"] = "Gust",
		["Color"] = "Blue",
		["Cost"] = {["Neutral"] = 2, ["Yellow"] = 5, ["Blue"] = 5,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Enemy fighters are locked for one turn. At the end of your turn, lower the power of all enemy fighters by 50, gain 1 yellow icon, then both players lose 200 life.",
			["Type"] = "OnSummon",
			["Power"] = {{"Lock",1},{"Summon","Dicey Token","Ally"},{"Damage",9999,"Self"}},
			Target = "Opponent",
		},
		["Bio"] = "Together as one, we gamble the night away!.",
	},
	
	["Dicey Token"] = {
		["Id"] = 677356865,
		["Name"] = "Deadly Dicey Duo",
		["Health"] = 1400,
		["Power"] = 650,
		["Rarity"] = "Token",
		["AttackEffect"] = "Gust",
		["Color"] = "Blue",
		["Cost"] = {["Neutral"] = 2, ["Yellow"] = 5, ["Blue"] = 5,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Enemy fighters are locked for one turn. At the end of your turn, lower the power of all enemy fighters by 50, gain 1 yellow icon, then both players lose 200 life.",
			["Type"] = "OnEnd",
			["Power"] = {{"Yellow",1},{"Weaken",50,"Opponent"},{"Cost",200},{"Inflict",200,"Opponent"}},
			Target = "Opponent",
		},
		["Bio"] = "Together as one, we gamble the night away!.",
	},
	
	["Defaultio"] = {
		["Id"] = 677334267,
		["Name"] = "Defaultio",
		["Health"] = 800,
		["Power"] = 650,
		["Rarity"] = "Epic",
		["AttackEffect"] = "SlashDiagonal",
		["Color"] = "Yellow",
		["Cost"] = {["Neutral"] = 4, ["Yellow"] = 3,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Whenever your opponent casts an action or terrain spell, allied fighters gain 300 health.",
			["Type"] = "OnEnemyCast",
			["Power"] = {{"Heal",300}},
			Target = "Ally",
		},
		["Bio"] = "Although WoodReviewer loves his axe, it's Defaultio's taste in wood grain that keeps them from being friends...",
	},	
	
	["Your_Name"] = {
		["Id"] = 679500982,
		["Name"] = "Your_Name",
		["Health"] = 450,
		["Power"] = 450,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "SlashDiagonal",
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 3,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "Summon a lattice of blue crystals, each with different effects. Crystals don't generate icons.",
			["Type"] = "OnSummon",
			["Power"] = {{"Summon","Crystal of Knowledge's Thirst"},{"Summon","Crystal of Logic's Will"},{"Summon","Crystal of Intellect's Scheme"},{"Add","Targeting Blip"}},
			Target = "Ally",
		},
		["Bio"] = "Give me knowledge, logic, and intellect, and I'll give you the game.",
	},	
	
	["Crystal of Knowledge's Thirst"] = {
		["Id"] = 675456600,
		["Name"] = "Crystal of Knowledge's Thirst",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Archetype"] = "Crystal",
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 1,},
		["Token"] = true,
		["Effect"] = {
			Name = "Reincarnation",
			Description = "When this card is targeted, draw a card, then destroy all crystals.",
			["Type"] = "OnTarget",
			["Power"] = {{"Draw",1},{"Damage",9999,"Archetype"}},
			Target = "Ally",
		},
		["Bio"] = "Right now, you need knowledge.",
	},

	["Crystal of Logic's Will"] = {
		["Id"] = 675456879,
		["Name"] = "Crystal of Logic's Will",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Archetype"] = "Crystal",
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 1,},
		["Token"] = true,
		["Effect"] = {
			Name = "Ending",
			Description = "When this card is targeted, lock a target fighter for 1 turn, then destroy all crystals.",
			["Type"] = "OnTarget",
			["Power"] = {{"Lock",1,"Single"},{"Damage",9999,"Archetype"}},
			Target = "Ally",
		},
		["Bio"] = "Right now, you need logic.",
	},	

	["Crystal of Intellect's Scheme"] = {
		["Id"] = 675456755,
		["Name"] = "Crystal of Intellect's Scheme",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Archetype"] = "Crystal",
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 1,},
		["Token"] = true,
		["Effect"] = {
			Name = "Reincarnation",
			Description = "When this card is targeted, enemy fighters lose 100 power, then destroy all crystals.",
			["Type"] = "OnTarget",
			["Power"] = {{"Weaken",100,"Opponent"},{"Damage",9999,"Archetype"}},
			Target = "Ally",
		},
		["Bio"] = "Right now, you need intellect.",
	},	
	
	["Friaza"] = {
		["Id"] = 668506369,
		["Name"] = "Friaza",
		["Health"] = 1000,
		["Power"] = 400,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "PunchKick",		
		["Color"] = "Blue",
		["Cost"] = {["Neutral"] = 2, ["Blue"] = 6,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Whenever you cast an action or terrain spell, unlock this fighter.",
			["Type"] = "OnAllyCast",
			["Power"] = {{"Unlock",9999}},
			Target = "Self",
		},
		["Bio"] = "THIS ISN'T EVEN MY FINAL FORM!",
	},
	
	["Ultra Bestower"] = {
		["Id"] = 675456403,
		["Name"] = "Ultra Bestower",
		["Health"] = 150,
		["Power"] = 200,
		["Rarity"] = "Common",
		["AttackEffect"] = "Flood",		
		["Color"] = "Neutral",
		["Token"] = true,
		["DiscardBlock"] = true,
		["Archetype"] = "Ultra",
		["Cost"] = {["Neutral"] = 0,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Lose all coloured icons. All Ultras gain 100 health.",
			["Type"] = "OnSummon",
			["Power"] = {{"SetYellow",0},{"SetGreen",0},{"SetBlue",0},{"SetRed",0},{"Heal",100,"Archetype"},{"Unlock",1,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "The four fundamental icons dictate what can be and what cannot be, yet the most alien of forces transcend colour altogether.",
	},	
	
	["Ultra Enhancer"] = {
		["Id"] = 675456688,
		["Name"] = "Ultra Enhancer",
		["Health"] = 200,
		["Power"] = 150,
		["Rarity"] = "Common",
		["AttackEffect"] = "Flood",		
		["Color"] = "Neutral",
		["Token"] = true,
		["DiscardBlock"] = true,
		["Archetype"] = "Ultra",
		["Cost"] = {["Neutral"] = 0,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Lose all coloured icons. All Ultras gain 100 power.",
			["Type"] = "OnSummon",
			["Power"] = {{"SetYellow",0},{"SetGreen",0},{"SetBlue",0},{"SetRed",0},{"Strengthen",100,"Archetype"},{"Unlock",1,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "White icons are icons already used by mages. Icons can be used multiple times, but lose their colour after the first use.",
	},	
	
	["Ultra Otherer"] = {
		["Id"] = 675456335,
		["Name"] = "Ultra Otherer",
		["Health"] = 300,
		["Power"] = 300,
		["Rarity"] = "Common",
		["AttackEffect"] = "Flood",		
		["Color"] = "Neutral",
		["Token"] = true,
		["DiscardBlock"] = true,
		["Archetype"] = "Ultra",
		["Cost"] = {["Neutral"] = 0,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Lose all coloured icons. (This helps cast stronger Ultras.)",
			["Type"] = "OnSummon",
			["Power"] = {{"SetYellow",0},{"SetGreen",0},{"SetBlue",0},{"SetRed",0},{"Unlock",1,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "Many things can survive enviroments filled with coloured icons, especially green ones. But white-icon enviroments can only be survived by Ultras. Named for their survival.",
	},	
	
	["Ultra Beseecher"] = {
		["Id"] = 675456676,
		["Name"] = "Ultra Beseecher",
		["Health"] = 300,
		["Power"] = 300,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Flood",		
		["Color"] = "Neutral",
		["Token"] = true,
		["DiscardBlock"] = true,
		["Archetype"] = "Ultra",
		["Requirement"] = {"Archetype",1},
		["Cost"] = {["Neutral"] = 0,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Summon only if you control 1 or more Ultras. Draw a card and lock all other Ultras for a turn.",
			["Type"] = "OnSummon",
			["Power"] = {{"Draw",1},{"Lock",1},{"Unlock",1,"Self"},{"EndTurn",1}},
			Target = "Ally",
		},
		["Bio"] = "Only primitive Ultras were seen among the edges of their territories, before a breakthrough in technology happened. Now a properly trained person can delve as deeply as they want.",
	},	

	["Ultra Desirer"] = {
		["Id"] = 675456632,
		["Name"] = "Ultra Desirer",
		["Health"] = 300,
		["Power"] = 300,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Flood",		
		["Color"] = "Neutral",
		["Token"] = true,
		["DiscardBlock"] = true,
		["Archetype"] = "Ultra",
		["Requirement"] = {"Archetype",2},
		["Cost"] = {["Neutral"] = 0,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Summon only if you control 2 or more Ultras. Summon a copy of this card, then end the turn.",
			["Type"] = "OnSummon",
			["Power"] = {{"Summon","Ultra Desirer"},{"EndTurn",1}},
			Target = "Ally",
		},
		["Bio"] = "Ultras warp the limits of energy. What would only be found with certain colours of icons can also be found in Ultras.",
	},	

	["Ultra Severer"] = {
		["Id"] = 675456511,
		["Name"] = "Ultra Severer",
		["Health"] = 600,
		["Power"] = 600,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Flood",		
		["Color"] = "Neutral",
		["Token"] = true,
		["DiscardBlock"] = true,
		["Archetype"] = "Ultra",
		["Requirement"] = {"Archetype",3},
		["Cost"] = {["Neutral"] = 0,},
		["Effect"] = {
			Name = "Bleeding Reality",
			Description = "Summon only if you control 3 or more Ultras. Deal 300 damage to a target fighter, then end the turn.",
			["Type"] = "OnSummon",
			["Power"] = {{"Damage",300,"Single"},{"EndTurn",1}},
			Target = "Ally",
		},
		["Bio"] = "Ultras do not take intrusions to their hives lightly.",
	},	

	["Ultra Depriver"] = {
		["Id"] = 675456540,
		["Name"] = "Ultra Depriver",
		["Health"] = 700,
		["Power"] = 700,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Flood",		
		["Color"] = "Neutral",
		["Token"] = true,
		["DiscardBlock"] = true,
		["Archetype"] = "Ultra",
		["Requirement"] = {"Archetype",4},
		["Cost"] = {["Neutral"] = 0,},
		["Effect"] = {
			Name = "Bleeding Reality",
			Description = "Summon only if you control 4 or more Ultras. Your opponent loses two white icons, then end the turn.",
			["Type"] = "OnSummon",
			["Power"] = {{"Neutral",-2,"Opponent"},{"EndTurn",1}},
			Target = "Ally",
		},
		["Bio"] = "Some mages have attempted to summon Ultras in other environments. They only thrive when nothing else does.",
	},	

	["Ultra Vanquisher"] = {
		["Id"] = 675456630,
		["Name"] = "Ultra Vanquisher",
		["Health"] = 1200,
		["Power"] = 1200,
		["Rarity"] = "Rare",
		["AttackEffect"] = "Flood",		
		["Color"] = "Neutral",
		["Token"] = true,
		["DiscardBlock"] = true,
		["Archetype"] = "Ultra",
		["Requirement"] = {"Archetype",5},
		["Cost"] = {["Neutral"] = 0,},
		["Effect"] = {
			Name = "Bleeding Reality",
			Description = "Summon only if you control 5 or more Ultras. End the turn.",
			["Type"] = "OnSummon",
			["Power"] = {{"EndTurn",1}},
			Target = "Ally",
		},
		["Bio"] = "When Ultras set up a new hive, Vanquishers are spawned to defend it. A single vanquisher takes a single army to remove.",
	},	

	["Ultra Orator"] = {
		["Id"] = 675456679,
		["Name"] = "Ultra Orator",
		["Health"] = 900,
		["Power"] = 900,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "Flood",		
		["Color"] = "Neutral",
		["Token"] = true,
		["DiscardBlock"] = true,
		["Archetype"] = "Ultra",
		["Requirement"] = {"Archetype",6},
		["Cost"] = {["Neutral"] = 0,},
		["Effect"] = {
			Name = "Bleeding Reality",
			Description = "Summon only if you control 6 or more Ultras. Lock all enemy fighters for 2 turns, then end the turn.",
			["Type"] = "OnSummon",
			["Power"] = {{"Lock",2,"Opponent"},{"EndTurn",1}},
			Target = "Ally",
		},
		["Bio"] = "The intelligence of Ultras was questionable at best until reports of a species resembling a religious figure surfaced.",
	},	

	["Ultra Obliterator"] = {
		["Id"] = 675456546,
		["Name"] = "Ultra Obliterator",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Epic",
		["AttackEffect"] = "Flood",		
		["Color"] = "Neutral",
		["Token"] = true,
		["DiscardBlock"] = true,
		["Archetype"] = "Ultra",
		["Requirement"] = {"Archetype",8},
		["Cost"] = {["Neutral"] = 0,},
		["Effect"] = {
			Name = "Bleeding Reality",
			Description = "Cast only if you control 8 Ultras. All Ultras gain 500 health and power. Return this card to your hand, then end the turn.",
			["Type"] = "OnSummon",
			["Power"] = {{"Heal",500},{"Strengthen",500}},
			Target = "Archetype",
		},
		["Bio"] = "Ultras share a hivemind that allow others to be summoned. When this hivemind reaches a critical mass, regions get torn asunder from the sheer pressure.",
	},	

	["Ultra Annihilator"] = {
		["Id"] = 675456614,
		["Name"] = "Ultra Annihilator",
		["Health"] = 1500,
		["Power"] = 1500,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "Erasure", -- Grey the opposing card out.	
		["Color"] = "Neutral",
		["Token"] = true,
		["DiscardBlock"] = true,
		["Archetype"] = "Ultra",
		["Requirement"] = {"Archetype",7},
		["Cost"] = {["Neutral"] = 0,},
		["Effect"] = {
			Name = "Bleeding Reality",
			Description = "Summon only if you control 7 or more Ultras. Whenever an allied fighter dies, put an Ultra Enhancer into your hand.",
			["Type"] = "OnAllyDeath",
			["Power"] = {{"Add","Ultra Enhancer"}},
			Target = "Ally",
		},
		["Bio"] = "A single glimpse of perfection taught Zanzel all she had to do in life.",
	},	

	["AII_Dragon"] = {
        ["Id"] = 679504969,
       	["Name"] = "AII_Dragon",
       	["Health"] = 700,
       	["Power"] = 300,
       	["Rarity"] = "Rare",
       	["AttackEffect"] = "Fire",
       	["Color"] = "Yellow",
       	["Cost"] = {["Yellow"] = 6,},
       	["Effect"] = {
			Name = "Hellfire",
			Description = "When this fighter finishes attacking a fighter with less than 300 Power, destroy that fighter.",
			["Type"] = "OnAttackEnd",
			["Power"] = {{"Swap",030},{"Damage",300},{"Heal",300},{"Swap",030}},
            Target = "Aggressor",
       	},	
        ["Bio"] = "100% Pure Dragon.",
    },
	
	["colesans16"] = {
        ["Id"] = 679503783,
       	["Name"] = "colesans16",
       	["Health"] = 400,
       	["Power"] = 400,
       	["Rarity"] = "Common",
       	["AttackEffect"] = "PunchKick",
       	["Color"] = "Neutral",
		["Token"] = true,
		["Cost"] = {["Neutral"] = 4,},
        ["Effect"] = {
			Name = "Hellfire",
			Description = "When this card dies, gain 4 White icons. This card can't generate icons naturally.",
			["Type"] = "OnDeath",
			["Power"] = {{"Neutral",4}},
			Target = "Ally",
		},
		["Bio"] = "I'll be keeping those under locks.",
    },	
		
	["Cindering"] = {
        ["Id"] = 689606486,
       	["Name"] = "Cindering",
       	["Health"] = 600,
       	["Power"] = 600,
       	["Rarity"] = "Legendary",
       	["AttackEffect"] = "Fire",
		["Archetype"] = "Cindering",
		["Color"] = "Red",
		["Cost"] = {["Red"] = 6,},
		["Effect"] = {
			Name = "Hellfire",
           	Description = "Haste. When this card enters the battlefield or dies, deal 600 damage to your opponent.",
			["Type"] = "OnSummon",
			["Power"] = {{"Summon","Cindering Token"},{"Unlock",1,"Archetype"},{"Inflict",600,"Opponent"},{"Damage",9999,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "He certainly isn't.",
    },
	
	["Cindering Token"] = {
		["Id"] = 689606486,
		["Name"] = "Cindering",
		["Health"] = 600,
		["Power"] = 600,
		["Rarity"] = "Token",
		["AttackEffect"] = "Fire",
		["Archetype"] = "Cindering",
		["Color"] = "Red",
		["Cost"] = {["Red"] = 6,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Haste. When this card enters the battlefield or dies, deal 600 damage to your opponent.",
			["Type"] = "OnDeath",
			["Power"] = {{"Inflict",600,"Opponent"}},
			Target = "Ally",
		},
		["Bio"] = "He certainly isn't.",
	},
	
	["emilvita"] = {
		["Id"] = 695206120,
		["Name"] = "emilvita",
		["Health"] = 300,
		["Power"] = 300,
		["Rarity"] = "Common",
		["AttackEffect"] = "UziShot",
		["Color"] = "Yellow",
		["Cost"] = {["Neutral"] = 2,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "When emilvita is targeted by a creature, turn that creature into emilvita. This effect can only be used once.",
			["Type"] = "OnTarget",
			["Power"] = {{"Summon","emiltoken"},{"Summon","emiltoken","Ally"},{"Damage",9999,"Aggressor"},{"Damage",9999,"Self"}},
			Target = "Opponent",
		},
		["Bio"] = "SQUAT! SQUAT! SQUAT LUNGE SQUAT!",
	},

   	["emiltoken"] = {
		["Id"] = 695206120,
		["Name"] = "emilvita",
		["Health"] = 300,
		["Power"] = 300,
		["Rarity"] = "Token",
		["AttackEffect"] = "UziShot",
		["Color"] = "Yellow",
		["Cost"] = {["Neutral"] = 2,},
		["Bio"] = "SQUAT! SQUAT! SQUAT LUNGE SQUAT!",
	},
	
	["Lord_Gizmo"] = {
		["Id"] = 695207622,
		["Name"] = "Lord_Gizmo",
		["Health"] = 500,
		["Power"] = 500,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "UziShot",
		["Color"] = "Green",
		["Cost"] = {["Neutral"] = 4,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "When this card is attacked and survives, generate a green icon.",
			["Type"] = "OnAttacked",
			["Power"] = {{"Green",1}},
			Target = "Ally",
		},
		["Bio"] = "OMG COMMANDO PENGU 030",
	},
	
	["wikiwakiwoirier"] = {
		["Id"] = 695209999,
		["Name"] = "wikiwakiwoirier",
		["Health"] = 600,
		["Power"] = 100,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "PunchKick",
		["Color"] = "Blue",
		["Cost"] = {["Neutral"] = 2, ["Blue"] = 3,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "When this card is attacked, lock the card that attacked it for two turns.",
			["Type"] = "OnAttacked",
			["Power"] = {{"Lock",2}},
			Target = "Aggressor",
		},
		["Bio"] = "Truth lies beyond the plane of existance, and stretches out further beyond to the endless grasp of the universe.",
	},	
	
	["TheJazzCat22"] = {
		["Id"] = 695209226,
		["Name"] = "TheJazzCat22",
		["Health"] = 300,
		["Power"] = 300,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "Fire",
		["Color"] = "Red",
		["Requirement"] = {"Opponent",2},
		["Cost"] = {["Neutral"] = 2, ["Red"] = 1,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Can only be summoned if your opponent has 2 or more fighters. Whenever this card is attacked, TheJazzCat22 gains 150 power and 150 health.",
			["Type"] = "OnAttacked",
			["Power"] = {{"Strengthen",150},{"Heal",150}},
			Target = "Self",
		},
		["Bio"] = "Ya' like jazz?",
	},
	
	["ChaoticCommando"] = {
		["Id"] = 697663303,
		["Name"] = "ChaoticCommando",
		["Health"] = 1200,
		["Power"] = 500,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "Slash",
		["Color"] = "Red",
		["Cost"] = {["Red"] = 4,},
		["Effect"] = {
			Name = "Hellfire",
			Description = "Whenever you summon a fighter, deal 400 damage to ChaoticCommando and give that fighter 100 power.",
			["Type"] = "OnAllySummon",
			["Power"] = {{"Damage",400},{"Strengthen",100,"Aggressor"}},
			Target = "Self",
		},
		["Bio"] = "If chaos could ever be controlled, word peace would be restored. *It* begs to differ...",
	},	
		
	["MarissaKitty04"] = {
		["Id"] = 689606519,
		["Name"] = "MarissaKitty04",
		["Health"] = 450,
		["Power"] = 450,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "SlashDiagonal",
		["Color"] = "Red",
		["Cost"] = {["Red"] = 3,},
		["Effect"] = {
			Name = "Reincarnation",
			Description = "Summon a lattice of red crystals, each with different effects. Crystals don't generate icons.",
			["Type"] = "OnSummon",
			["Power"] = {{"Summon","Crystal of Power's Exploit"},{"Summon","Crystal of Ambition's End"},{"Summon","Crystal of Death's Vengence"},{"Add","Targeting Blip"}},
			Target = "Ally",
		},
		["Bio"] = "Power. Ambition. Death. Choose. <3",
	},	
	
	["Crystal of Power's Exploit"] = {
		["Id"] = 689606510,
		["Name"] = "Crystal of Power's Exploit",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Archetype"] = "Crystal",
		["Color"] = "Red",
		["Cost"] = {["Red"] = 1,},
		["Token"] = true,
		["Effect"] = {
			Name = "Reincarnation",
			Description = "When this card is targeted, your opponent loses two White icons, then destroy all crystals.",
			["Type"] = "OnTarget",
			["Power"] = {{"Neutral",-2,"Opponent"},{"Damage",9999,"Archetype"}},
			Target = "Ally",
		},
		["Bio"] = "One batch of power coming right up.",
	},

	["Crystal of Ambition's End"] = {
		["Id"] = 689606490,
		["Name"] = "Crystal of Ambition's End",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Archetype"] = "Crystal",
		["Color"] = "Red",
		["Cost"] = {["Red"] = 1,},
		["Token"] = true,
		["Effect"] = {
			Name = "Ending",
			Description = "When this card is targeted, deal 350 damage to the opponent, then destroy all crystals.",
			["Type"] = "OnTarget",
			["Power"] = {{"Inflict",350,"Opponent"},{"Damage",9999,"Archetype"}},
			Target = "Ally",
		},
		["Bio"] = "One batch of ambition coming right up.",
	},	

	["Crystal of Death's Vengence"] = {
		["Id"] = 689606434,
		["Name"] = "Crystal of Death's Vengence",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Slash",
		["Archetype"] = "Crystal",
		["Color"] = "Red",
		["Cost"] = {["Red"] = 1,},
		["Token"] = true,
		["Effect"] = {
			Name = "Bloodstone",
			Description = "When this card is targeted, deal 250 damage to a target fighter, then destroy all crystals.",
			["Type"] = "OnTarget",
			["Power"] = {{"Damage",250,"Single"},{"Damage",9999,"Archetype"}},
			Target = "Ally",
		},
		["Bio"] = "One batch of SUBMISSION TO THE ALMIGHTY GOD-EMPEROR coming right up.",
	},		

	["Broken Dreams"] = {
		["Id"] = 689622877,
		["Name"] = "Broken Dreams",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Slash",
		["Color"] = "Neutral",
		["Cost"] = {["Neutral"] = 10,},
		["Effect"] = {
			Name = "Bloodstone",
			Description = "If you have this card, it's because you made an OP deck. The fireworks display you're about to get is condolences. -Myrm",
			["Type"] = "OnSummon",
			["Power"] = {{"Damage",99999,"All"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"Red",1},{"Yellow",1},{"Blue",-1},{"Yellow",-1},{"Green",1},{"Red",-1},{"Blue",1},{"Green",-1},{"Damage",99999,"All"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"Red",1},{"Yellow",1},{"Blue",-1},{"Yellow",-1},{"Green",1},{"Red",-1},{"Blue",1},{"Green",-1},{"Damage",99999,"All"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"RandomSummon","Any","Ally"},{"RandomSummon","Any","Opponent"},{"Red",1},{"Yellow",1},{"Blue",-1},{"Yellow",-1},{"Green",1},{"Red",-1},{"Blue",1},{"Green",-1},{"Cost",999999999,"Self"}},
			Target = "Ally",
		},
		["Bio"] = "",
	},
	
	["Damaging26"] = {
		["Id"] = 701255714,
		["Name"] = "Damaging26",
		["Health"] = 500,
		["Power"] = 400,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Dash",
		["Color"] = "Red", 
		["Cost"] = {["Red"] = 1,["Neutral"] = 3,},
		["Effect"] = {
			Name = "Redead",
			Description = "When this fighter dies, deal 100 damage to all non-red fighters",
			["Type"] = "OnDeath",
			["Power"] = {{"Damage",100,"NotColorRed"}},
			Target = "All",
		},
		["Bio"] = "If I'm to die, I'll try to bring you with me.",
	},
	
	["iiSmolToaster"] = {
		["Id"] = 709047246,
		["Name"] = "iiSmolToaster",
		["Health"] = 750,
		["Power"] = 200,
		["Rarity"] = "Common",
		["AttackEffect"] = "Dash",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 2,["Neutral"] = 2,},
		["Effect"] = {
			Name = "Toasty",
			Description = "When this fighter is attacked and survives, you gain 300 Life.",
			["Type"] = "OnAttacked",
			["Power"] = {{"Cost",-300}},
			Target = "Ally",
		},
		["Bio"] = "SmolToasters are sold withouth smol bread or batteries included.",
	},

	["Wrath of King Gecko"] = {
		["Id"] = 712737504,
		["Name"] = "Wrath of King Gecko",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "Dash",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 7,},
		["Effect"] = {
			Name = "Toasty",
			Description = "Summon King Gecko and its attendant.",
			["Type"] = "OnSummon",
			["Power"] = {{"Summon","King Gecko"},{"Summon","Gecko Attendant"}},
			Target = "Ally",
		},
		["Bio"] = "Anger is an illusion",
	},

	["King Gecko"] = {
		["Id"] = 712738306,
		["Name"] = "King Gecko",
		["Health"] = 2000,
		["Power"] = 1000,
		["Rarity"] = "Token",
		["AttackEffect"] = "Dash",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 7,},
		["Archetype"] = "Gecko",
		["Effect"] = {
			Name = "Toasty",
			Description = "At the end of your turns, King Gecko and its Attendant gain 200 health.",
			["Type"] = "OnEnd",
			["Power"] = {{"Heal",200}},
			Target = "Archetype",
		},
		["Bio"] = "JARVIS! Fetch me my favourite chair and garments! Do so in a timely fashion, and you may get to eat tonight!",
	},

	["Gecko Attendant"] = {
		["Id"] = 712737427,
		["Name"] = "Gecko Attendant",
		["Health"] = 1000,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = "Dash",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 7,},
		["Archetype"] = "Gecko",
		["Effect"] = {
			Name = "Toasty",
			Description = "When this card dies, Set King Gecko's health to 200.",
			["Type"] = "OnDeath",
			["Power"] = {{"SetHealth",200}},
			Target = "Archetype",
		},
		["Bio"] = [["He treats me poorly, but I accept it. He'd be nowhere without me."]],
	},

	["Aesura"] = {
		["Id"] = 712737665,
		["Name"] = "Aesura",
		["Health"] = 1000,
		["Power"] = 1000,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "Uzi",
		["Color"] = "Red", 
		["Cost"] = {["Red"] = 7,},
		["Effect"] = {
			Name = "Toasty",
			Description = "Whenever Aesura survives being attacked, destroy what attacked it.",
			["Type"] = "OnAttacked",
			["Power"] = {{"Damage",4000}},
			Target = "Aggressor",
		},
		["Bio"] = [[Do you deserve a snappy "Boom, Headshot?"]],
	},

	["Graalgamer"] = {
		["Id"] = 712737781,
		["Name"] = "Graalgamer",
		["Health"] = 400,
		["Power"] = 600,
		["Rarity"] = "Common",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Yellow", 
		["Cost"] = {["Neutral"] = 1, ["Yellow"] = 3,},
		["Effect"] = {
			Name = "Toasty",
			Description = "Whenever Graalgamer attacks a fighter, that fighter loses 100 power.",
			["Type"] = "OnAttack",
			["Power"] = {{"Weaken",100}},
			Target = "Aggressor",
		},
		["Bio"] = [[Now, to make a martini, you first need two parts lemon, three parts ma - *PEW!* - three parts mango, and four parts oyster.]],
	},

	["Yoshilove574"] = {
		["Id"] = 714689059,
		["Name"] = "Yoshilove574",
		["Health"] = 400,
		["Power"] = 0,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 4,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "A target fighter gains 400 health and power.",
			["Type"] = "OnSummon",
			["Power"] = {{"Heal",400},{"Strengthen",400}},
			Target = "Single",
		},
		["Bio"] = [[A lover of virtue. What, you thought he loved dinosaurs? Think again.]],
	},

	["Shaylan007"] = {
		["Id"] = 712738238,
		["Name"] = "Shaylan007",
		["Health"] = 500,
		["Power"] = 500,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Green", 
		["Cost"] = {["Neutral"] = 3, ["Green"] = 3,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "Haste. Whenever another allied fighter dies, reset Shay's stats and return it to its owner's hand.",
			["Type"] = "OnAllyDeath",
			["Power"] = {{"SetHealth",500},{"SetPower",500},{"Unlock",9999},{"Return",1}},
			Target = "Self",
		},
		["Bio"] = [[His hoverboard is fuelled with the souls of the dead.]],
	},

	["Indoorsnowball"] = {
		["Id"] = 712738101,
		["Name"] = "Indoorsnowball",
		["Health"] = 600,
		["Power"] = 600,
		["Rarity"] = "Legendary",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 8,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "When this card dies, summon two smaller versions of it. When those cards die, summon two smaller versions of those.",
			["Type"] = "OnDeath",
			["Power"] = {{"Summon","Snowball1"},{"Summon","Snowball1"}},
			Target = "Ally",
		},
		["Bio"] = [[Even robots have souls.]],
	},

	["Snowball1"] = {
		["Id"] = 712738263,
		["Name"] = "Indoorsnowball",
		["Health"] = 300,
		["Power"] = 300,
		["Rarity"] = "Token",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 8,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "When this card dies, summon two smaller versions of it.",
			["Type"] = "OnDeath",
			["Power"] = {{"Summon","Snowball2"},{"Summon","Snowball2"}},
			Target = "Ally",
		},
		["Bio"] = [[And if you can mass produce robots, you can mass produce souls.]],
	},

	["Snowball2"] = {
		["Id"] = 712738281,
		["Name"] = "Indoorsnowball",
		["Health"] = 150,
		["Power"] = 150,
		["Rarity"] = "Token",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 8,},
		["Bio"] = [[But even souls must end someday.]],
	},

	["CjMcGamingYT"] = {
		["Id"] = 712737664,
		["Name"] = "CjMcGamingYT",
		["Health"] = 350,
		["Power"] = 350,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Green", 
		["Cost"] = {["Neutral"] = 1, ["Green"] = 2,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "Whenever any fighter is summoned, destroy CjMcGamingYT and lower that fighter's power by 600.",
			["Type"] = "OnAnySummon",
			["Power"] = {{"Damage",9999,"Self"},{"Weaken",600,"Aggressor"}},
			Target = "Ally",
		},
		["Bio"] = [[I'm hunting wabbits. Weeboids, too.]],
	},


	["AMerryCan"] = {
		["Id"] = 714801845,
		["Name"] = "AMerryCan",
		["Health"] = 150,
		["Power"] = 50,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Red", 
		["Cost"] = {["Neutral"] = 2, ["Red"] = 2, ["Blue"] = 2,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "All red fighters gain 100 power. All blue fighters gain 100 health. All non-archetype rare fighters gain 100 health and power.",
			["Type"] = "OnSummon",
			["Power"] = {{"Heal",100,"ColorBlue"},{"Strengthen",100,"ColorRed"},{"Heal",100},{"Strengthen",100}},
			Target = "Archetype",
		},
		["Bio"] = [[AMerryCan! Eat Fresh!]],
	},

	["Fenfie08"] = {
		["Id"] = 714801834,
		["Name"] = "Fenfie08",
		["Health"] = 400,
		["Power"] = 250,
		["Rarity"] = "Common",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Blue", 
		["Cost"] = {["Neutral"] = 1, ["Blue"] = 2,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "Put a nightmare into your opponent's hand.",
			["Type"] = "OnSummon",
			["Power"] = {{"Add","Nightmare"}},
			Target = "Opponent",
		},
		["Bio"] = [[The happiest people always have the darkest secrets.]],
	},

	["BrandonOccult"] = {
		["Id"] = 714801871,
		["Name"] = "BrandonOccult",
		["Health"] = 800,
		["Power"] = 0,
		["Rarity"] = "Common",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Yellow", 
		["Cost"] = {["Yellow"] = 4,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "When this card is targeted, draw a card.",
			["Type"] = "OnTarget",
			["Power"] = {{"Draw",1}},
			Target = "Ally",
		},
		["Bio"] = [[Come to the dark side. We have famous people.]],
	},

	["BandiheartYT"] = {
		["Id"] = 714801837,
		["Name"] = "BandiheartYT",
		["Health"] = 1000,
		["Power"] = 0,
		["Rarity"] = "Epic",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 8,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "When this card dies, resurrect it with 200 more power and 200 less health.",
			["Type"] = "OnDeath",
			["Power"] = {{"Summon","Bandi1"}},
			Target = "Ally",
		},
		["Bio"] = [[Inb4 complaints that this isn't an overseer card.]],
	},

	["Bandi1"] = {
		["Id"] = 714801837,
		["Name"] = "BandiheartYT",
		["Health"] = 800,
		["Power"] = 200,
		["Rarity"] = "Token",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 8,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "When this card dies, resurrect it with 200 more power and 200 less health.",
			["Type"] = "OnDeath",
			["Power"] = {{"Summon","Bandi2"}},
			Target = "Ally",
		},
		["Bio"] = [[Or a zombie card.]],
	},

	["Bandi2"] = {
		["Id"] = 714801837,
		["Name"] = "BandiheartYT",
		["Health"] = 600,
		["Power"] = 400,
		["Rarity"] = "Token",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 8,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "When this card dies, resurrect it with 200 more power and 200 less health.",
			["Type"] = "OnDeath",
			["Power"] = {{"Summon","Bandi3"}},
			Target = "Ally",
		},
		["Bio"] = [[Or a rare card.]],
	},

	["Bandi3"] = {
		["Id"] = 714801837,
		["Name"] = "BandiheartYT",
		["Health"] = 400,
		["Power"] = 600,
		["Rarity"] = "Token",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 8,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "When this card dies, resurrect it with 200 more power and 200 less health.",
			["Type"] = "OnDeath",
			["Power"] = {{"Summon","Bandi4"}},
			Target = "Ally",
		},
		["Bio"] = [[Or a fun card.]],
	},

	["Bandi4"] = {
		["Id"] = 714801837,
		["Name"] = "BandiheartYT",
		["Health"] = 200,
		["Power"] = 800,
		["Rarity"] = "Token",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Green", 
		["Cost"] = {["Green"] = 8,},
		["Bio"] = [[Or a good card.]],
	},


	["Satyr Firemaster"] = {
		["Id"] = 714689069,
		["Name"] = "Satyr Firemaster",
		["Health"] = 400,
		["Power"] = 600,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Yellow", 
		["Cost"] = {["Red"] = 4, ["Yellow"] = 4, ["Green"] = 4,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "At the end of your turns, deal 250 damage to the opponent, then put a copy of Satyr Firemaster into play. You lose all of your red icons.",
			["Type"] = "OnEnd",
			["Power"] = {{"SetBlue",0},{"Summon","Satyr Firemaster"},{"Inflict",250,"Opponent"}},
			Target = "Ally",
		},
		["Bio"] = [[I was feeling lonely one day, so I made a friend out of charcoal! Then I thought, hey, why not make a party out of charcoal!? :D :D]],
	},

	["Great Paraselene Sage"] = {
		["Id"] = 714689056,
		["Name"] = "Great Paraselene Sage",
		["Health"] = 1700,
		["Power"] = 1700,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "Punchkick",
		["Stealth"] = true,
		["Color"] = "Blue", 
		["Cost"] = {["Green"] = 4, ["Blue"] = 4, ["Red"] = 4,},
		["Effect"] = {
			Name = "Lunar Rays",
			Description = "Whenever you summon another fighter, destroy that fighter and deal 500 damage to a target fighter. Your lose all of your yellow icons.",
			["Type"] = "OnAllySummon",
			["Power"] = {{"SetYellow",0},{"Damage",9999,"Aggressor"},{"Damage",500,"Single"}},
			Target = "Ally",
		},
		["Bio"] = [["The noble work of our order is to give free energy to all from the moon's rays. The emotional cries of our detractors is... Depressing."]],
	},

	["Delirious Ooze"] = {
		["Id"] = 714689056,
		["Name"] = "Delirious Ooze",
		["Health"] = 1500,
		["Power"] = 1500,
		["Rarity"] = "Rare",
		["Archetype"] = "Hero",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Red", 
		["Cost"] = {["Blue"] = 4, ["Red"] = 4, ["Yellow"] = 4,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "Whenever a player summons a fighter, that player summons an additional random fighter. Its effect triggers and you lose all of your green icons.",
			["Type"] = "OnAnySummon",
			["Power"] = {{"RandomSummonWithEffect","Any","Aggressor"},{"SetGreen",0}},
			Target = "Ally",
		},
		["Bio"] = [[Let it show you everything nature cannot do.]],
	},

	["Confusion Elemental?"] = {
		["Id"] = 714689077,
		["Name"] = "Confusion Elemental?",
		["Health"] = 6025,
		["Power"] = 0,
		["Rarity"] = "Rare",
		["Archetype"] = "Sometimes I like to throw ice on the ground and pretend to be a walrus",
		["AttackEffect"] = "Erasure",
		["Color"] = "Green", 
		["Cost"] = {["Blue"] = 4, ["Green"] = 4, ["Yellow"] = 4,},
		["Effect"] = {
			Name = "befriending of scaly mutts",
			Description = "SURPRISE! Lose all of your red icons and end the turn! How will your opponent react!?",
			["Type"] = "OnSummon",
			["Power"] = {{"SetRed",0},{"Summon","Insult!"},{"Summon","Participate in Quiz!"},{"Summon","Clap! Clap!"},{"Summon","Shine!"},{"Add","Cast Your Vote!","Opponent"},{"EndTurn",1}},
			Target = "Ally",
		},
		["Bio"] = [[]],
	},

	["Cast Your Vote!"] = {
		["Id"] = 715061556,
		["Name"] = "Cast Your Vote!",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["Archetype"] = "Sometimes I like to throw ice on the ground and pretend to be a walrus",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Yellow", 
		["Cost"] = {["Blue"] = 0,},
		["Effect"] = {
			Name = "let's roleplay",
			Description = "Target any fighter you want! How do you choose to react to the Confusion Elemental??",
			["Type"] = "OnSummon",
			["Power"] = {{"Heal",0}},
			Target = "Single",
		},
		["Bio"] = [[I recommend the blue one for beginners. o3o]],
	},

	["Insult!"] = {
		["Id"] = 712738182,
		["Name"] = "Insult!",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["Archetype"] = "Sometimes I like to throw ice on the ground and pretend to be a walrus",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Red", 
		["Cost"] = {["Blue"] = 0,},
		["Effect"] = {
			Name = "let's roleplay",
			Description = "Say something rude about the elemental's mother! In a fit of rage, it deals 3000 damage to all its friends and gains 3000 power!",
			["Type"] = "OnTarget",
			["Power"] = {{"Strengthen",3000,"Archetype"},{"Damage",3025,"Ally"}},
			Target = "Single",
		},
		["Bio"] = [[]],
	},

	["Participate in Quiz!"] = {
		["Id"] = 712738061,
		["Name"] = "Participate in Quiz!",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["Archetype"] = "Sometimes I like to throw ice on the ground and pretend to be a walrus",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Red", 
		["Cost"] = {["Blue"] = 0,},
		["Effect"] = {
			Name = "let's roleplay",
			Description = "Ask the elemental for counselling about your life choices! It gains 500 power, loses 2000 health, and locks everything for six turns so it can answer!",
			["Type"] = "OnTarget",
			["Power"] = {{"Strengthen",500,"Archetype"},{"Lock",6,"All"},{"Damage",2025,"Archetype"}},
			Target = "Single",
		},
		["Bio"] = [[]],
	},

	["Shine!"] = {
		["Id"] = 712738149,
		["Name"] = "Shine!",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["Archetype"] = "Sometimes I like to throw ice on the ground and pretend to be a walrus",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Red", 
		["Cost"] = {["Blue"] = 0,},
		["Effect"] = {
			Name = "let's roleplay",
			Description = "Do a dance for the elemental! In awe at your moves, it can't do anything else!",
			["Type"] = "OnTarget",
			["Power"] = {{"Damage",25,"Archetype"}},
			Target = "Single",
		},
		["Bio"] = [[]],
	},

	["Clap! Clap!"] = {
		["Id"] = 712738213,
		["Name"] = "Clap! Clap!",
		["Health"] = 25,
		["Power"] = 0,
		["Rarity"] = "Token",
		["Archetype"] = "Sometimes I like to throw ice on the ground and pretend to be a walrus",
		["AttackEffect"] = "Punchkick",
		["Color"] = "Red", 
		["Cost"] = {["Blue"] = 0,},
		["Effect"] = {
			Name = "let's roleplay",
			Description = "Clap sarcastically at the elemental! Annoyed, it gains 1000 power, loses 3000 health, and drains 1000 life from you!",
			["Type"] = "OnTarget",
			["Power"] = {{"Strengthen",1000,"Archetype"},{"Inflict",1000,"Opponent"},{"Inflict",-1000,"Self"},{"Damage",3025,"Archetype"}},
			Target = "Single",
		},
		["Bio"] = [[]],
	},
}

return tentwelvesixteen
